import type { FormPdfMapping, FillContext } from "../types";
import { sbCheck, officer, currency } from "../types";

const PAGE1 = "topmostSubform[0].Page1[0].";
const HEADER = `topmostSubform[0].Page1[0].HeaderAddress_ReadOrder[0].CalendarName_ReadOrder[0].`;

export const F1065_MAPPING: FormPdfMapping = {
  formCode: "1065",
  pdfFileName: "f1065.pdf",
  taxYear: 2024,
  fields: [
    // ── Calendar year header ──────────────────────────────────────────────────
    {
      pdfFieldName: `${HEADER}f1_01[0]`,
      compute: (ctx: FillContext) => String(ctx.meta.taxYear),
      format: "string",
      irsLine: "header",
      description: "Tax year begin",
    },
    {
      pdfFieldName: `${HEADER}f1_02[0]`,
      compute: (ctx: FillContext) => String(ctx.meta.taxYear),
      format: "string",
      irsLine: "header",
      description: "Tax year end year",
    },
    {
      pdfFieldName: `${HEADER}f1_03[0]`,
      compute: (ctx: FillContext) => String(ctx.meta.taxYear),
      format: "string",
      irsLine: "header",
      description: "Calendar year footer",
    },

    // ── Entity header ─────────────────────────────────────────────────────────
    {
      pdfFieldName: `${HEADER}f1_04[0]`,
      compute: (ctx: FillContext) => ctx.meta.companyName,
      format: "string",
      irsLine: "header",
      description: "Partnership name",
    },
    {
      pdfFieldName: `${HEADER}f1_05[0]`,
      compute: (ctx: FillContext) => ctx.meta.address,
      format: "string",
      irsLine: "header",
      description: "Street address",
    },
    {
      pdfFieldName: `${HEADER}f1_06[0]`,
      compute: (ctx: FillContext) => ctx.meta.city,
      format: "string",
      irsLine: "header",
      description: "City",
    },
    {
      pdfFieldName: `${HEADER}f1_07[0]`,
      compute: (ctx: FillContext) => ctx.meta.state,
      format: "string",
      irsLine: "header",
      description: "State",
    },
    {
      pdfFieldName: `${HEADER}f1_08[0]`,
      compute: (ctx: FillContext) => ctx.meta.zip,
      format: "string",
      irsLine: "header",
      description: "ZIP code",
    },
    {
      pdfFieldName: `${HEADER}f1_09[0]`,
      compute: (ctx: FillContext) => ctx.meta.ein,
      format: "string",
      irsLine: "header",
      description: "Employer Identification Number (EIN)",
    },
    {
      pdfFieldName: `${HEADER}f1_10[0]`,
      compute: (ctx: FillContext) => ctx.meta.businessStartDate ?? "",
      format: "string",
      irsLine: "header",
      description: "Date business started",
    },

    // ── Entity info fields ────────────────────────────────────────────────────
    {
      pdfFieldName: `${PAGE1}f1_11[0]`,
      compute: (ctx: FillContext) => ctx.meta.principalBusinessActivity ?? "",
      format: "string",
      irsLine: "A",
      description: "Principal business activity",
    },
    {
      pdfFieldName: `${PAGE1}f1_12[0]`,
      compute: (ctx: FillContext) => ctx.meta.principalProductService ?? "",
      format: "string",
      irsLine: "B",
      description: "Principal product or service",
    },
    {
      pdfFieldName: `${PAGE1}f1_13[0]`,
      compute: (ctx: FillContext) => ctx.meta.naicsCode ?? "",
      format: "string",
      irsLine: "C",
      description: "Business code number",
    },
    {
      pdfFieldName: `${PAGE1}f1_14[0]`,
      compute: (ctx: FillContext) => String(ctx.meta.numberOfPartners ?? 0),
      format: "integer",
      irsLine: "header",
      description: "Number of Schedules K-1 attached",
    },
    {
      pdfFieldName: `${PAGE1}f1_15[0]`,
      manual: true,
      format: "string",
      irsLine: "header",
      description: "Additional info field 1",
    },
    {
      pdfFieldName: `${PAGE1}f1_16[0]`,
      manual: true,
      format: "string",
      irsLine: "header",
      description: "Additional info field 2",
    },

    // ── Income (Lines 1a – 8) ─────────────────────────────────────────────────
    {
      pdfFieldName: `${PAGE1}f1_19[0]`,
      factName: "gross_receipts_total",
      format: "currency",
      irsLine: "1a",
      description: "Gross receipts or sales",
    },
    {
      pdfFieldName: `${PAGE1}f1_20[0]`,
      factName: "returns_allowances_total",
      format: "currency",
      irsLine: "1b",
      description: "Returns and allowances",
    },
    {
      pdfFieldName: `${PAGE1}f1_21[0]`,
      compute: (ctx: FillContext) => { const gr = Number(ctx.facts.gross_receipts_total ?? 0); const ra = Number(ctx.facts.returns_allowances_total ?? 0); return String(gr - ra); },
      format: "currency",
      irsLine: "1c",
      description: "Balance (Line 1a minus 1b)",
    },
    {
      pdfFieldName: `${PAGE1}f1_22[0]`,
      factName: "cogs_total",
      format: "currency",
      irsLine: "2",
      description: "Cost of goods sold (Schedule A)",
    },
    {
      pdfFieldName: `${PAGE1}f1_23[0]`,
      factName: "gross_profit",
      format: "currency",
      irsLine: "3",
      description: "Gross profit (Line 1c minus Line 2)",
    },
    {
      pdfFieldName: `${PAGE1}f1_24[0]`,
      manual: true,
      format: "currency",
      irsLine: "4",
      description: "Ordinary income (loss) from other partnerships, estates, and trusts",
    },
    {
      pdfFieldName: `${PAGE1}f1_25[0]`,
      manual: true,
      format: "currency",
      irsLine: "5",
      description: "Net farm profit (loss)",
    },
    {
      pdfFieldName: `${PAGE1}f1_26[0]`,
      manual: true,
      format: "currency",
      irsLine: "6",
      description: "Net gain (loss) from Form 4797",
    },
    {
      pdfFieldName: `${PAGE1}f1_27[0]`,
      factName: "other_income_total",
      format: "currency",
      irsLine: "7",
      description: "Other income (loss)",
    },
    {
      pdfFieldName: `${PAGE1}f1_28[0]`,
      factName: "total_income",
      format: "currency",
      irsLine: "8",
      description: "Total income (loss) (Lines 3 through 7)",
    },

    // ── Deductions (Lines 9 – 22) ─────────────────────────────────────────────
    {
      pdfFieldName: `${PAGE1}f1_29[0]`,
      factName: "wages_total",
      format: "currency",
      irsLine: "9",
      description: "Salaries and wages (other than to partners, less employment credits)",
    },
    {
      pdfFieldName: `${PAGE1}f1_30[0]`,
      factName: "guaranteed_payments_total",
      format: "currency",
      irsLine: "10",
      description: "Guaranteed payments to partners",
    },
    {
      pdfFieldName: `${PAGE1}f1_31[0]`,
      factName: "repairs_total",
      format: "currency",
      irsLine: "11",
      description: "Repairs and maintenance",
    },
    {
      pdfFieldName: `${PAGE1}f1_32[0]`,
      factName: "bad_debt_total",
      format: "currency",
      irsLine: "12",
      description: "Bad debts",
    },
    {
      pdfFieldName: `${PAGE1}f1_33[0]`,
      factName: "rent_building_total",
      format: "currency",
      irsLine: "13",
      description: "Rent",
    },
    {
      pdfFieldName: `${PAGE1}f1_34[0]`,
      factName: "taxes_licenses_total",
      format: "currency",
      irsLine: "14",
      description: "Taxes and licenses",
    },
    {
      pdfFieldName: `${PAGE1}f1_35[0]`,
      factName: "interest_expense_total",
      format: "currency",
      irsLine: "15",
      description: "Interest",
    },
    {
      pdfFieldName: `${PAGE1}f1_36[0]`,
      factName: "depreciation_total",
      format: "currency",
      irsLine: "16a",
      description: "Depreciation (if required, attach Form 4562)",
    },
    {
      pdfFieldName: `${PAGE1}f1_37[0]`,
      manual: true,
      format: "currency",
      irsLine: "16b",
      description: "Less depreciation reported on Schedule A and elsewhere on return",
    },
    {
      pdfFieldName: `${PAGE1}f1_38[0]`,
      compute: (ctx: FillContext) => String(Number(ctx.facts.depreciation_total ?? 0)),
      format: "currency",
      irsLine: "16c",
      description: "Net depreciation (Line 16a minus 16b)",
    },
    {
      pdfFieldName: `${PAGE1}f1_39[0]`,
      factName: "depletion_total",
      format: "currency",
      irsLine: "17",
      description: "Depletion (do not deduct oil and gas depletion)",
    },
    {
      pdfFieldName: `${PAGE1}f1_40[0]`,
      factName: "pension_profitsharing_total",
      format: "currency",
      irsLine: "18",
      description: "Retirement plans, etc.",
    },
    {
      pdfFieldName: `${PAGE1}f1_41[0]`,
      factName: "employee_benefits_total",
      format: "currency",
      irsLine: "19",
      description: "Employee benefit programs",
    },
    {
      pdfFieldName: `${PAGE1}f1_42[0]`,
      factName: "general_deduction_total",
      format: "currency",
      irsLine: "20",
      description: "Other deductions (attach statement)",
    },
    {
      pdfFieldName: `${PAGE1}f1_43[0]`,
      factName: "total_deductions",
      format: "currency",
      irsLine: "21",
      description: "Total deductions (add Lines 9 through 20)",
    },
    {
      pdfFieldName: `${PAGE1}f1_44[0]`,
      factName: "ordinary_business_income",
      format: "currency",
      irsLine: "22",
      description: "Ordinary business income (loss) (Line 8 minus Line 21)",
    },

    // ── Auto-generated mappings (remaining fields) ──────────────────
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_6[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q6"), format: "boolean", description: "Checkbox: p1_q6" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_6[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q6"), format: "boolean", description: "Checkbox: p1_q6" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_6[2]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q6"), format: "boolean", description: "Checkbox: p1_q6" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_7[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q7"), format: "boolean", description: "Checkbox: p1_q7" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_8[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q8"), format: "boolean", description: "Checkbox: p1_q8" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_9[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q9"), format: "boolean", description: "Checkbox: p1_q9" },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_52[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_53[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_54[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_10[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q10"), format: "boolean", description: "Checkbox: p1_q10" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_10[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q10"), format: "boolean", description: "Checkbox: p1_q10" },
    { pdfFieldName: "topmostSubform[0].Page1[0].AccountNo[0].f1_56[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_11[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q11"), format: "boolean", description: "Checkbox: p1_q11" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_11[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q11"), format: "boolean", description: "Checkbox: p1_q11" },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_57[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_12[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q12"), format: "boolean", description: "Checkbox: p1_q12" },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_58[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_60[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_61[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_62[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_1[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q1"), format: "boolean", description: "Checkbox: p2_q1" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_1[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q1"), format: "boolean", description: "Checkbox: p2_q1" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_1[2]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q1"), format: "boolean", description: "Checkbox: p2_q1" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_1[3]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q1"), format: "boolean", description: "Checkbox: p2_q1" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_1[4]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q1"), format: "boolean", description: "Checkbox: p2_q1" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_1[5]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q1"), format: "boolean", description: "Checkbox: p2_q1" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_01[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_2[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q2"), format: "boolean", description: "Checkbox: p2_q2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_2[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q2"), format: "boolean", description: "Checkbox: p2_q2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_3[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q3"), format: "boolean", description: "Checkbox: p2_q3" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_3[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q3"), format: "boolean", description: "Checkbox: p2_q3" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_4[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q4"), format: "boolean", description: "Checkbox: p2_q4" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_4[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q4"), format: "boolean", description: "Checkbox: p2_q4" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3a[0].Row1[0].f2_02[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3a[0].Row1[0].f2_03[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3a[0].Row1[0].f2_04[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3a[0].Row1[0].f2_05[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3a[0].Row2[0].f2_06[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3a[0].Row2[0].f2_07[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3a[0].Row2[0].f2_08[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3a[0].Row2[0].f2_09[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3a[0].Row3[0].f2_10[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3a[0].Row3[0].f2_11[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3a[0].Row3[0].f2_12[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3a[0].Row3[0].f2_13[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3a[0].Row4[0].f2_14[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3a[0].Row4[0].f2_15[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3a[0].Row4[0].f2_16[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3a[0].Row4[0].f2_17[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3a[0].Row5[0].f2_18[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3a[0].Row5[0].f2_19[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3a[0].Row5[0].f2_20[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3a[0].Row5[0].f2_21[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_5[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q5"), format: "boolean", description: "Checkbox: p2_q5" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_5[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q5"), format: "boolean", description: "Checkbox: p2_q5" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3b[0].BodyRow1[0].f2_22[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3b[0].BodyRow1[0].f2_23[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3b[0].BodyRow1[0].f2_24[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3b[0].BodyRow1[0].f2_25[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3b[0].BodyRow1[0].f2_26[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3b[0].BodyRow2[0].f2_27[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3b[0].BodyRow2[0].f2_28[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3b[0].BodyRow2[0].f2_29[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3b[0].BodyRow2[0].f2_30[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3b[0].BodyRow2[0].f2_31[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3b[0].BodyRow3[0].f2_32[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3b[0].BodyRow3[0].f2_33[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3b[0].BodyRow3[0].f2_34[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3b[0].BodyRow3[0].f2_35[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3b[0].BodyRow3[0].f2_36[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3b[0].BodyRow4[0].f2_37[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3b[0].BodyRow4[0].f2_38[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3b[0].BodyRow4[0].f2_39[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3b[0].BodyRow4[0].f2_40[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3b[0].BodyRow4[0].f2_41[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3b[0].BodyRow5[0].f2_42[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3b[0].BodyRow5[0].f2_43[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3b[0].BodyRow5[0].f2_44[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3b[0].BodyRow5[0].f2_45[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line3b[0].BodyRow5[0].f2_46[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_6[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q6"), format: "boolean", description: "Checkbox: p2_q6" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_6[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q6"), format: "boolean", description: "Checkbox: p2_q6" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_7[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q7"), format: "boolean", description: "Checkbox: p2_q7" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_7[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q7"), format: "boolean", description: "Checkbox: p2_q7" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_8[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q8"), format: "boolean", description: "Checkbox: p2_q8" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_8[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q8"), format: "boolean", description: "Checkbox: p2_q8" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_9[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q9"), format: "boolean", description: "Checkbox: p2_q9" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_9[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q9"), format: "boolean", description: "Checkbox: p2_q9" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_47[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_10[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q10"), format: "boolean", description: "Checkbox: p2_q10" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_10[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q10"), format: "boolean", description: "Checkbox: p2_q10" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_11[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q11"), format: "boolean", description: "Checkbox: p2_q11" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_11[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q11"), format: "boolean", description: "Checkbox: p2_q11" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_48[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_12[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q12"), format: "boolean", description: "Checkbox: p2_q12" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_12[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q12"), format: "boolean", description: "Checkbox: p2_q12" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_49[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_50[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_13[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q13"), format: "boolean", description: "Checkbox: p2_q13" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_13[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q13"), format: "boolean", description: "Checkbox: p2_q13" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_1[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q1"), format: "boolean", description: "Checkbox: p3_q1" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_1[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q1"), format: "boolean", description: "Checkbox: p3_q1" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_2[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q2"), format: "boolean", description: "Checkbox: p3_q2" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_2[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q2"), format: "boolean", description: "Checkbox: p3_q2" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_3[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q3"), format: "boolean", description: "Checkbox: p3_q3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_3[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q3"), format: "boolean", description: "Checkbox: p3_q3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_4[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q4"), format: "boolean", description: "Checkbox: p3_q4" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_5[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q5"), format: "boolean", description: "Checkbox: p3_q5" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_5[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q5"), format: "boolean", description: "Checkbox: p3_q5" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_6[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q6"), format: "boolean", description: "Checkbox: p3_q6" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_6[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q6"), format: "boolean", description: "Checkbox: p3_q6" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_7[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q7"), format: "boolean", description: "Checkbox: p3_q7" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_7[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q7"), format: "boolean", description: "Checkbox: p3_q7" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_8[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q8"), format: "boolean", description: "Checkbox: p3_q8" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_8[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q8"), format: "boolean", description: "Checkbox: p3_q8" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_9[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q9"), format: "boolean", description: "Checkbox: p3_q9" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_9[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q9"), format: "boolean", description: "Checkbox: p3_q9" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_10[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q10"), format: "boolean", description: "Checkbox: p3_q10" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_10[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q10"), format: "boolean", description: "Checkbox: p3_q10" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_11[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q11"), format: "boolean", description: "Checkbox: p3_q11" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_11[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q11"), format: "boolean", description: "Checkbox: p3_q11" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_12[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q12"), format: "boolean", description: "Checkbox: p3_q12" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_12[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q12"), format: "boolean", description: "Checkbox: p3_q12" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_13[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q13"), format: "boolean", description: "Checkbox: p3_q13" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_13[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q13"), format: "boolean", description: "Checkbox: p3_q13" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_14[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q14"), format: "boolean", description: "Checkbox: p3_q14" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_14[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q14"), format: "boolean", description: "Checkbox: p3_q14" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_15[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q15"), format: "boolean", description: "Checkbox: p3_q15" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_15[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q15"), format: "boolean", description: "Checkbox: p3_q15" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_16[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q16"), format: "boolean", description: "Checkbox: p3_q16" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_16[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q16"), format: "boolean", description: "Checkbox: p3_q16" },
    { pdfFieldName: "topmostSubform[0].Page4[0].f4_01[0]", staticValue: "", description: "Unmapped — page 4" },
    { pdfFieldName: "topmostSubform[0].Page4[0].f4_02[0]", staticValue: "", description: "Unmapped — page 4" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_1[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q1"), format: "boolean", description: "Checkbox: p4_q1" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_1[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q1"), format: "boolean", description: "Checkbox: p4_q1" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_2[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q2"), format: "boolean", description: "Checkbox: p4_q2" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_2[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q2"), format: "boolean", description: "Checkbox: p4_q2" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_3[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q3"), format: "boolean", description: "Checkbox: p4_q3" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_3[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q3"), format: "boolean", description: "Checkbox: p4_q3" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_4[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q4"), format: "boolean", description: "Checkbox: p4_q4" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_4[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q4"), format: "boolean", description: "Checkbox: p4_q4" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_5[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q5"), format: "boolean", description: "Checkbox: p4_q5" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_6[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q6"), format: "boolean", description: "Checkbox: p4_q6" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_6[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q6"), format: "boolean", description: "Checkbox: p4_q6" },
    { pdfFieldName: "topmostSubform[0].Page4[0].f4_03[0]", staticValue: "", description: "Unmapped — page 4" },
    { pdfFieldName: "topmostSubform[0].Page4[0].f4_04[0]", staticValue: "", description: "Unmapped — page 4" },
    { pdfFieldName: "topmostSubform[0].Page4[0].f4_05[0]", staticValue: "", description: "Unmapped — page 4" },
    { pdfFieldName: "topmostSubform[0].Page4[0].f4_06[0]", staticValue: "", description: "Unmapped — page 4" },
    { pdfFieldName: "topmostSubform[0].Page4[0].f4_07[0]", staticValue: "", description: "Unmapped — page 4" },
    { pdfFieldName: "topmostSubform[0].Page4[0].f4_08[0]", staticValue: "", description: "Unmapped — page 4" },
    { pdfFieldName: "topmostSubform[0].Page4[0].f4_09[0]", staticValue: "", description: "Unmapped — page 4" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_01[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_02[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_03[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_04[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_05[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_06[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_07[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_08[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_09[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_10[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_18[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_21[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_22[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_24[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_25[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_26[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_29[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_30[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_32[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_33[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_34[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_37[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_38[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_40[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_1[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q1"), format: "boolean", description: "Checkbox: p5_q1" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_2[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q2"), format: "boolean", description: "Checkbox: p5_q2" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_41[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_42[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_44[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_45[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_46[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_49[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_50[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_51[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_52[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_53[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_54[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].f5_55[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page6[0].f6_01[0]", staticValue: "", description: "Unmapped — page 6" },
    { pdfFieldName: "topmostSubform[0].Page6[0].Table_Line2[0].BodyRowA[0].f6_02[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page6[0].Table_Line2[0].BodyRowA[0].f6_03[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page6[0].Table_Line2[0].BodyRowA[0].f6_04[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page6[0].Table_Line2[0].BodyRowA[0].f6_05[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page6[0].Table_Line2[0].BodyRowA[0].f6_06[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page6[0].Table_Line2[0].BodyRowA[0].f6_07[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page6[0].Table_Line2[0].BodyRowB[0].f6_08[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page6[0].Table_Line2[0].BodyRowB[0].f6_09[0]", staticValue: "", description: "Table  Line " },
  ],
};
