import type { FormPdfMapping, FillContext } from "../types";
import { sbCheck, officer, currency } from "../types";

export const F1120_MAPPING: FormPdfMapping = {
  formCode: "1120",
  pdfFileName: "f1120.pdf",
  taxYear: 2025,
  fields: [
    // -------------------------------------------------------------------------
    // Header fields
    // -------------------------------------------------------------------------
    {
      pdfFieldName:
        "topmostSubform[0].Page1[0].NameFieldsReadOrder[0].f1_4[0]",
      compute: (ctx: FillContext) => ctx.meta.companyName,
      format: "string",
      irsLine: "Header",
      description: "Company name",
    },
    {
      pdfFieldName:
        "topmostSubform[0].Page1[0].NameFieldsReadOrder[0].f1_5[0]",
      compute: (ctx: FillContext) => ctx.meta.address,
      format: "string",
      irsLine: "Header",
      description: "Street address",
    },
    {
      pdfFieldName:
        "topmostSubform[0].Page1[0].NameFieldsReadOrder[0].f1_6[0]",
      compute: (ctx: FillContext) => ctx.meta.city,
      format: "string",
      irsLine: "Header",
      description: "City",
    },
    {
      pdfFieldName:
        "topmostSubform[0].Page1[0].NameFieldsReadOrder[0].f1_7[0]",
      compute: (ctx: FillContext) => ctx.meta.state,
      format: "string",
      irsLine: "Header",
      description: "State",
    },
    {
      pdfFieldName:
        "topmostSubform[0].Page1[0].NameFieldsReadOrder[0].f1_8[0]",
      compute: (ctx: FillContext) => ctx.meta.zip,
      format: "string",
      irsLine: "Header",
      description: "ZIP code",
    },
    {
      pdfFieldName:
        "topmostSubform[0].Page1[0].NameFieldsReadOrder[0].f1_9[0]",
      compute: (ctx: FillContext) => ctx.meta.ein,
      format: "string",
      irsLine: "B",
      description: "Employer Identification Number (EIN)",
    },
    {
      pdfFieldName:
        "topmostSubform[0].Page1[0].NameFieldsReadOrder[0].f1_10[0]",
      compute: (ctx: FillContext) =>
        ctx.facts["date_incorporated"] != null
          ? String(ctx.facts["date_incorporated"])
          : undefined,
      format: "string",
      irsLine: "C",
      description: "Date incorporated",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_11[0]",
      factName: "total_assets",
      format: "currency",
      irsLine: "D",
      description: "Total assets",
    },

    // -------------------------------------------------------------------------
    // Income — Lines 1a through 11
    // -------------------------------------------------------------------------
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_14[0]",
      factName: "gross_receipts_total",
      format: "currency",
      irsLine: "1a",
      description: "Gross receipts or sales",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_15[0]",
      factName: "returns_allowances_total",
      format: "currency",
      irsLine: "1b",
      description: "Returns and allowances",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_16[0]",
      compute: (ctx: FillContext) => {
        const receipts = Number(ctx.facts["gross_receipts_total"] ?? 0);
        const returns = Number(ctx.facts["returns_allowances_total"] ?? 0);
        const balance = receipts - returns;
        return balance !== 0 ? String(balance) : undefined;
      },
      format: "currency",
      irsLine: "1c",
      description: "Balance (gross receipts minus returns and allowances)",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_17[0]",
      factName: "cogs_total",
      format: "currency",
      irsLine: "2",
      description: "Cost of goods sold (Schedule A, line 8)",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_18[0]",
      factName: "gross_profit",
      format: "currency",
      irsLine: "3",
      description: "Gross profit (line 1c minus line 2)",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_19[0]",
      factName: "dividend_income_total",
      format: "currency",
      irsLine: "4",
      description: "Dividends and inclusions (Schedule C, line 23, column (a))",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_20[0]",
      factName: "interest_income_total",
      format: "currency",
      irsLine: "5",
      description: "Interest",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_21[0]",
      factName: "rent_income_total",
      format: "currency",
      irsLine: "6",
      description: "Gross rents",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_22[0]",
      factName: "royalty_income_total",
      format: "currency",
      irsLine: "7",
      description: "Gross royalties",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_23[0]",
      factName: "capital_gain_total",
      format: "currency",
      irsLine: "8",
      description: "Capital gain net income (attach Schedule D)",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_24[0]",
      factName: "capital_gain_total",
      format: "currency",
      irsLine: "9",
      description: "Net gain or loss from Form 4797 (Part II, line 17)",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_25[0]",
      factName: "other_income_total",
      format: "currency",
      irsLine: "10",
      description: "Other income (attach statement)",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_26[0]",
      factName: "total_income",
      format: "currency",
      irsLine: "11",
      description: "Total income (add lines 3 through 10)",
    },

    // -------------------------------------------------------------------------
    // Deductions — Lines 12 through 27
    // -------------------------------------------------------------------------
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_27[0]",
      factName: "officer_compensation_total",
      format: "currency",
      irsLine: "12",
      description:
        "Compensation of officers (attach Form 1125-E if applicable)",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_28[0]",
      factName: "wages_total",
      format: "currency",
      irsLine: "13",
      description:
        "Salaries and wages (less employment credits)",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_29[0]",
      factName: "repairs_total",
      format: "currency",
      irsLine: "14",
      description: "Repairs and maintenance",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_30[0]",
      factName: "bad_debt_total",
      format: "currency",
      irsLine: "15",
      description: "Bad debts",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_31[0]",
      factName: "rent_building_total",
      format: "currency",
      irsLine: "16",
      description: "Rents",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_32[0]",
      factName: "taxes_licenses_total",
      format: "currency",
      irsLine: "17",
      description: "Taxes and licenses",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_33[0]",
      factName: "interest_expense_total",
      format: "currency",
      irsLine: "18",
      description: "Interest (see instructions)",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_34[0]",
      factName: "charitable_contributions_total",
      format: "currency",
      irsLine: "19",
      description:
        "Charitable contributions (see instructions for 10% limitation)",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_35[0]",
      factName: "depreciation_total",
      format: "currency",
      irsLine: "20",
      description:
        "Depreciation from Form 4562 not claimed on Schedule A or elsewhere",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_36[0]",
      factName: "depletion_total",
      format: "currency",
      irsLine: "21",
      description: "Depletion",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_37[0]",
      factName: "advertising_total",
      format: "currency",
      irsLine: "22",
      description: "Advertising",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_38[0]",
      factName: "pension_profitsharing_total",
      format: "currency",
      irsLine: "23",
      description:
        "Pension, profit-sharing, etc., plans",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_39[0]",
      factName: "employee_benefits_total",
      format: "currency",
      irsLine: "24",
      description: "Employee benefit programs",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_40[0]",
      format: "currency",
      irsLine: "25",
      staticValue: "",
      description: "Reserved for future use (intentionally blank)",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_41[0]",
      factName: "general_deduction_total",
      format: "currency",
      irsLine: "26",
      description: "Other deductions (attach statement)",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_42[0]",
      factName: "total_deductions",
      format: "currency",
      irsLine: "27",
      description: "Total deductions (add lines 12 through 26)",
    },

    // -------------------------------------------------------------------------
    // Tax Computation — Lines 28 through 35
    // -------------------------------------------------------------------------
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_43[0]",
      factName: "taxable_income_before_nol",
      format: "currency",
      irsLine: "28",
      description:
        "Taxable income before net operating loss deduction and special deductions (line 11 minus line 27)",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_44[0]",
      factName: "nol_deduction_total",
      format: "currency",
      irsLine: "29a",
      description: "Net operating loss (NOL) deduction",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_45[0]",
      factName: "special_deductions_drd",
      format: "currency",
      irsLine: "29b",
      description: "Special deductions (Schedule C, line 24, column (c))",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_46[0]",
      factName: "taxable_income",
      format: "currency",
      irsLine: "30",
      description:
        "Taxable income (line 28 minus lines 29a and 29b; see instructions)",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_47[0]",
      factName: "corporate_tax_21pct",
      format: "currency",
      irsLine: "31",
      description: "Total tax (Schedule J, Part I, line 11)",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_48[0]",
      factName: "estimated_tax_payments_total",
      format: "currency",
      irsLine: "32",
      description:
        "Total payments and credits (Schedule J, Part II, line 21)",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_49[0]",
      factName: "estimated_tax_penalty",
      format: "currency",
      irsLine: "33",
      description:
        "Estimated tax penalty (see instructions; check if Form 2220 is attached)",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_50[0]",
      factName: "amount_owed",
      format: "currency",
      irsLine: "34",
      description:
        "Amount owed (if line 31 plus line 33 is greater than line 32)",
    },
    {
      pdfFieldName: "topmostSubform[0].Page1[0].f1_51[0]",
      factName: "overpayment_amount",
      format: "currency",
      irsLine: "35",
      description:
        "Overpayment (if line 32 is larger than the total of lines 31 and 33)",
    },

    // ── Auto-generated mappings (remaining fields) ──────────────────
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_6[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q6"), format: "boolean", description: "Checkbox: p1_q6" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_7[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q7"), format: "boolean", description: "Checkbox: p1_q7" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_8[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q8"), format: "boolean", description: "Checkbox: p1_q8" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_9[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q9"), format: "boolean", description: "Checkbox: p1_q9" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_10[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q10"), format: "boolean", description: "Checkbox: p1_q10" },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_52[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_53[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_54[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RoutingNo[0].f1_56[0]", manual: true, description: "banking_info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_11[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q11"), format: "boolean", description: "Checkbox: p1_q11" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_11[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q11"), format: "boolean", description: "Checkbox: p1_q11" },
    { pdfFieldName: "topmostSubform[0].Page1[0].AccountNo[0].f1_57[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].SignHere-ReadOrder[0].f1_58[0]", manual: true, description: "signature_or_preparer" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_12[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q12"), format: "boolean", description: "Checkbox: p1_q12" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_12[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q12"), format: "boolean", description: "Checkbox: p1_q12" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_13[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q13"), format: "boolean", description: "Checkbox: p1_q13" },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_60[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_61[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_62[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_64[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line3[0].f2_7[0]", staticValue: "", description: "Table ScheduleC Line 3" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line3[0].f2_8[0]", staticValue: "", description: "Table ScheduleC Line 3" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line3[0].f2_9[0]", staticValue: "", description: "Table ScheduleC Line 3" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line4[0].f2_10[0]", staticValue: "", description: "Table ScheduleC Line 4" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line4[0].f2_11[0]", staticValue: "", description: "Table ScheduleC Line 4" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line4[0].f2_12[0]", staticValue: "", description: "Table ScheduleC Line 4" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line5[0].f2_13[0]", staticValue: "", description: "Table ScheduleC Line 5" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line5[0].f2_14[0]", staticValue: "", description: "Table ScheduleC Line 5" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line5[0].f2_15[0]", staticValue: "", description: "Table ScheduleC Line 5" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line6[0].f2_16[0]", staticValue: "", description: "Table ScheduleC Line 6" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line6[0].f2_17[0]", staticValue: "", description: "Table ScheduleC Line 6" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line6[0].f2_18[0]", staticValue: "", description: "Table ScheduleC Line 6" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line7[0].f2_19[0]", staticValue: "", description: "Table ScheduleC Line 7" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line7[0].f2_20[0]", staticValue: "", description: "Table ScheduleC Line 7" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line7[0].f2_21[0]", staticValue: "", description: "Table ScheduleC Line 7" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line8[0].f2_22[0]", staticValue: "", description: "Table ScheduleC Line 8" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line8[0].f2_23[0]", staticValue: "", description: "Table ScheduleC Line 8" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line8[0].f2_24[0]", staticValue: "", description: "Table ScheduleC Line 8" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line9[0].f2_25[0]", staticValue: "", description: "Table ScheduleC Line 9" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line9[0].f2_26[0]", staticValue: "", description: "Table ScheduleC Line 9" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line9[0].f2_27[0]", staticValue: "", description: "Table ScheduleC Line 9" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line10[0].f2_28[0]", staticValue: "", description: "Table ScheduleC Line 10" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line10[0].f2_29[0]", staticValue: "", description: "Table ScheduleC Line 10" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line10[0].f2_30[0]", staticValue: "", description: "Table ScheduleC Line 10" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line11[0].f2_31[0]", staticValue: "", description: "Table ScheduleC Line 11" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line11[0].f2_32[0]", staticValue: "", description: "Table ScheduleC Line 11" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line11[0].f2_33[0]", staticValue: "", description: "Table ScheduleC Line 11" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line12[0].f2_34[0]", staticValue: "", description: "Table ScheduleC Line 12" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line12[0].f2_35[0]", staticValue: "", description: "Table ScheduleC Line 12" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line12[0].f2_36[0]", staticValue: "", description: "Table ScheduleC Line 12" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line13[0].f2_37[0]", staticValue: "", description: "Table ScheduleC Line 13" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line13[0].f2_38[0]", staticValue: "", description: "Table ScheduleC Line 13" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line13[0].f2_39[0]", staticValue: "", description: "Table ScheduleC Line 13" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line14[0].f2_40[0]", staticValue: "", description: "Table ScheduleC Line 14" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line14[0].f2_41[0]", staticValue: "", description: "Table ScheduleC Line 14" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line14[0].f2_42[0]", staticValue: "", description: "Table ScheduleC Line 14" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line15[0].f2_43[0]", staticValue: "", description: "Table ScheduleC Line 15" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line15[0].f2_44[0]", staticValue: "", description: "Table ScheduleC Line 15" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line15[0].f2_45[0]", staticValue: "", description: "Table ScheduleC Line 15" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line16a[0].f2_46[0]", staticValue: "", description: "Table ScheduleC Line 16a" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line16a[0].f2_47[0]", staticValue: "", description: "Table ScheduleC Line 16a" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line16a[0].f2_48[0]", staticValue: "", description: "Table ScheduleC Line 16a" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line16b[0].f2_49[0]", staticValue: "", description: "Table ScheduleC Line 16b" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line16b[0].f2_50[0]", staticValue: "", description: "Table ScheduleC Line 16b" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line16b[0].f2_51[0]", staticValue: "", description: "Table ScheduleC Line 16b" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line16c[0].f2_52[0]", staticValue: "", description: "Table ScheduleC Line 16c" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line16c[0].f2_53[0]", staticValue: "", description: "Table ScheduleC Line 16c" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line16c[0].f2_54[0]", staticValue: "", description: "Table ScheduleC Line 16c" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line17[0].f2_55[0]", staticValue: "", description: "Table ScheduleC Line 17" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line17[0].f2_56[0]", staticValue: "", description: "Table ScheduleC Line 17" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line17[0].f2_57[0]", staticValue: "", description: "Table ScheduleC Line 17" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line18[0].f2_58[0]", staticValue: "", description: "Table ScheduleC Line 18" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line18[0].f2_59[0]", staticValue: "", description: "Table ScheduleC Line 18" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line18[0].f2_60[0]", staticValue: "", description: "Table ScheduleC Line 18" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line19[0].f2_61[0]", staticValue: "", description: "Table ScheduleC Line 19" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line19[0].f2_62[0]", staticValue: "", description: "Table ScheduleC Line 19" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line19[0].f2_63[0]", staticValue: "", description: "Table ScheduleC Line 19" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line20[0].f2_64[0]", staticValue: "", description: "Table ScheduleC Line 20" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line20[0].f2_65[0]", staticValue: "", description: "Table ScheduleC Line 20" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line20[0].f2_66[0]", staticValue: "", description: "Table ScheduleC Line 20" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line21[0].f2_67[0]", staticValue: "", description: "Table ScheduleC Line 21" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line21[0].f2_68[0]", staticValue: "", description: "Table ScheduleC Line 21" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line21[0].f2_69[0]", staticValue: "", description: "Table ScheduleC Line 21" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line22[0].f2_70[0]", staticValue: "", description: "Table ScheduleC Line 22" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line22[0].f2_71[0]", staticValue: "", description: "Table ScheduleC Line 22" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line22[0].f2_72[0]", staticValue: "", description: "Table ScheduleC Line 22" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line23[0].f2_73[0]", staticValue: "", description: "Table ScheduleC Line 23" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line23[0].f2_74[0]", staticValue: "", description: "Table ScheduleC Line 23" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_ScheduleC[0].Line23[0].f2_75[0]", staticValue: "", description: "Table ScheduleC Line 23" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_76[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_23[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_24[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_25[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_26[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_27[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_28[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_29[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_30[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_31[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_32[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_33[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_34[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_35[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_36[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_43[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_44[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_45[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_46[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_47[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_48[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_1[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q1"), format: "boolean", description: "Checkbox: p4_q1" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_1[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q1"), format: "boolean", description: "Checkbox: p4_q1" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_1[2]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q1"), format: "boolean", description: "Checkbox: p4_q1" },
    { pdfFieldName: "topmostSubform[0].Page4[0].f4_1[0]", staticValue: "", description: "Unmapped — page 4" },
    { pdfFieldName: "topmostSubform[0].Page4[0].f4_2[0]", staticValue: "", description: "Unmapped — page 4" },
    { pdfFieldName: "topmostSubform[0].Page4[0].f4_3[0]", staticValue: "", description: "Unmapped — page 4" },
    { pdfFieldName: "topmostSubform[0].Page4[0].f4_4[0]", staticValue: "", description: "Unmapped — page 4" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_2[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q2"), format: "boolean", description: "Checkbox: p4_q2" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_2[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q2"), format: "boolean", description: "Checkbox: p4_q2" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_3[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q3"), format: "boolean", description: "Checkbox: p4_q3" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_3[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q3"), format: "boolean", description: "Checkbox: p4_q3" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_4[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q4"), format: "boolean", description: "Checkbox: p4_q4" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_4[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q4"), format: "boolean", description: "Checkbox: p4_q4" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_5[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q5"), format: "boolean", description: "Checkbox: p4_q5" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_5[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q5"), format: "boolean", description: "Checkbox: p4_q5" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_6[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q6"), format: "boolean", description: "Checkbox: p4_q6" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_6[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q6"), format: "boolean", description: "Checkbox: p4_q6" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_7[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q7"), format: "boolean", description: "Checkbox: p4_q7" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_7[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q7"), format: "boolean", description: "Checkbox: p4_q7" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_8[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q8"), format: "boolean", description: "Checkbox: p4_q8" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_8[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q8"), format: "boolean", description: "Checkbox: p4_q8" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_9[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q9"), format: "boolean", description: "Checkbox: p4_q9" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_10[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q10"), format: "boolean", description: "Checkbox: p4_q10" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_1[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q1"), format: "boolean", description: "Checkbox: p5_q1" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_1[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q1"), format: "boolean", description: "Checkbox: p5_q1" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_2[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q2"), format: "boolean", description: "Checkbox: p5_q2" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_2[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q2"), format: "boolean", description: "Checkbox: p5_q2" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_3[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q3"), format: "boolean", description: "Checkbox: p5_q3" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_3[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q3"), format: "boolean", description: "Checkbox: p5_q3" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_4[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q4"), format: "boolean", description: "Checkbox: p5_q4" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_4[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q4"), format: "boolean", description: "Checkbox: p5_q4" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_5[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q5"), format: "boolean", description: "Checkbox: p5_q5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_5[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q5"), format: "boolean", description: "Checkbox: p5_q5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_6[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q6"), format: "boolean", description: "Checkbox: p5_q6" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_6[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q6"), format: "boolean", description: "Checkbox: p5_q6" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_7[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q7"), format: "boolean", description: "Checkbox: p5_q7" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_7[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q7"), format: "boolean", description: "Checkbox: p5_q7" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_8[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q8"), format: "boolean", description: "Checkbox: p5_q8" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_8[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q8"), format: "boolean", description: "Checkbox: p5_q8" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_9[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q9"), format: "boolean", description: "Checkbox: p5_q9" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_9[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q9"), format: "boolean", description: "Checkbox: p5_q9" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_10[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q10"), format: "boolean", description: "Checkbox: p5_q10" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_10[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q10"), format: "boolean", description: "Checkbox: p5_q10" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_11[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q11"), format: "boolean", description: "Checkbox: p5_q11" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_11[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q11"), format: "boolean", description: "Checkbox: p5_q11" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_12[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q12"), format: "boolean", description: "Checkbox: p5_q12" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_12[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q12"), format: "boolean", description: "Checkbox: p5_q12" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_13[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q13"), format: "boolean", description: "Checkbox: p5_q13" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_13[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q13"), format: "boolean", description: "Checkbox: p5_q13" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_14[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q14"), format: "boolean", description: "Checkbox: p5_q14" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_14[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q14"), format: "boolean", description: "Checkbox: p5_q14" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_15[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q15"), format: "boolean", description: "Checkbox: p5_q15" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_15[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q15"), format: "boolean", description: "Checkbox: p5_q15" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_16[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q16"), format: "boolean", description: "Checkbox: p5_q16" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_16[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q16"), format: "boolean", description: "Checkbox: p5_q16" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_17[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q17"), format: "boolean", description: "Checkbox: p5_q17" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_17[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q17"), format: "boolean", description: "Checkbox: p5_q17" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_18[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q18"), format: "boolean", description: "Checkbox: p5_q18" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_18[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q18"), format: "boolean", description: "Checkbox: p5_q18" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_19[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q19"), format: "boolean", description: "Checkbox: p5_q19" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_19[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q19"), format: "boolean", description: "Checkbox: p5_q19" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_20[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q20"), format: "boolean", description: "Checkbox: p5_q20" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_20[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q20"), format: "boolean", description: "Checkbox: p5_q20" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_21[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q21"), format: "boolean", description: "Checkbox: p5_q21" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_21[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q21"), format: "boolean", description: "Checkbox: p5_q21" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_22[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q22"), format: "boolean", description: "Checkbox: p5_q22" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_22[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q22"), format: "boolean", description: "Checkbox: p5_q22" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_23[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q23"), format: "boolean", description: "Checkbox: p5_q23" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_23[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q23"), format: "boolean", description: "Checkbox: p5_q23" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_24[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q24"), format: "boolean", description: "Checkbox: p5_q24" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_24[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q24"), format: "boolean", description: "Checkbox: p5_q24" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_25[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q25"), format: "boolean", description: "Checkbox: p5_q25" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_25[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q25"), format: "boolean", description: "Checkbox: p5_q25" },
  ],
};
