import type { FormPdfMapping, FillContext } from "../types";
import { sbCheck, officer, currency } from "../types";

const H = "topmostSubform[0].Page1[0].Header[0].";

export const F1120SSK_MAPPING: FormPdfMapping = {
  formCode: "Sch K-1 (S)",
  pdfFileName: "f1120ssk.pdf",
  taxYear: 2025,
  fields: [
    // -------------------------------------------------------------------------
    // Header — Calendar year
    // -------------------------------------------------------------------------
    {
      pdfFieldName: `${H}ForCalendarYear[0].f1_01[0]`,
      compute: (ctx: FillContext) => String(ctx.meta.taxYear),
      format: "string",
      irsLine: "Header",
      description: "Calendar year begin",
    },
    {
      pdfFieldName: `${H}ForCalendarYear[0].f1_02[0]`,
      compute: (ctx: FillContext) => String(ctx.meta.taxYear),
      format: "string",
      irsLine: "Header",
      description: "Calendar year end year",
    },
    {
      pdfFieldName: `${H}ForCalendarYear[0].f1_03[0]`,
      compute: (ctx: FillContext) => String(ctx.meta.taxYear),
      format: "string",
      irsLine: "Header",
      description: "Calendar year end month/day",
    },
    {
      pdfFieldName: `${H}ForCalendarYear[0].f1_04[0]`,
      compute: (ctx: FillContext) => String(ctx.meta.taxYear),
      format: "string",
      irsLine: "Header",
      description: "Calendar year footer",
    },

    // -------------------------------------------------------------------------
    // Header — Corporation info
    // -------------------------------------------------------------------------
    {
      pdfFieldName: `${H}f1_05[0]`,
      compute: (ctx: FillContext) => ctx.meta.companyName,
      format: "string",
      irsLine: "Header",
      description: "Corporation's name",
    },
    {
      pdfFieldName: `${H}f1_06[0]`,
      compute: (ctx: FillContext) => ctx.meta.address,
      format: "string",
      irsLine: "Header",
      description: "Corporation's street address",
    },
    {
      pdfFieldName: `${H}f1_07[0]`,
      compute: (ctx: FillContext) => ctx.meta.city,
      format: "string",
      irsLine: "Header",
      description: "Corporation's city",
    },
    {
      pdfFieldName: `${H}f1_08[0]`,
      compute: (ctx: FillContext) => ctx.meta.state,
      format: "string",
      irsLine: "Header",
      description: "Corporation's state",
    },
    {
      pdfFieldName: `${H}f1_09[0]`,
      compute: (ctx: FillContext) => ctx.meta.zip,
      format: "string",
      irsLine: "Header",
      description: "Corporation's ZIP code",
    },
    {
      pdfFieldName: `${H}f1_10[0]`,
      compute: (ctx: FillContext) => ctx.meta.ein,
      format: "string",
      irsLine: "Header",
      description: "Corporation's Employer Identification Number (EIN)",
    },

    // ── Auto-generated mappings (remaining fields) ──────────────────
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_01[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q01"), format: "boolean", description: "Checkbox: p1_q01" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_02[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q02"), format: "boolean", description: "Checkbox: p1_q02" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines1-12[0].f1_52[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines1-12[0].f1_53[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines1-12[0].f1_54[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines1-12[0].f1_56[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines1-12[0].f1_57[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines1-12[0].f1_58[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_60[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_61[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_62[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_64[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_65[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_66[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].c1_03[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q03"), format: "boolean", description: "Checkbox: p1_q03" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_72[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_73[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_74[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_75[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_76[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_77[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_78[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_79[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_80[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_81[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_82[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_83[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_84[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_85[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_87[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_88[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_89[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_90[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_91[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_92[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_93[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_94[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_95[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_96[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_97[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_98[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_99[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_100[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_101[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_102[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_103[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_104[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_105[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_106[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_107[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_108[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].Lines13-17[0].f1_109[0]", manual: true, description: "K-1 entity/owner info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].c1_04[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q04"), format: "boolean", description: "Checkbox: p1_q04" },
    { pdfFieldName: "topmostSubform[0].Page1[0].RightCol[0].c1_05[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q05"), format: "boolean", description: "Checkbox: p1_q05" },
  ],
};
