import type { FormPdfMapping, FillContext } from "../types";
import { sbCheck, officer, currency } from "../types";

const PAGE1 = "topmostSubform[0].Page1[0].";

export const F1120SM3_MAPPING: FormPdfMapping = {
  formCode: "Sch M-3",
  pdfFileName: "f1120sm3.pdf",
  taxYear: 2024,
  fields: [
    // ── Entity header ─────────────────────────────────────────────────────────
    {
      pdfFieldName: `${PAGE1}f1_1[0]`,
      compute: (ctx: FillContext) => ctx.meta.companyName,
      format: "string",
      irsLine: "header",
      description: "Name of corporation",
    },
    {
      pdfFieldName: `${PAGE1}f1_2[0]`,
      compute: (ctx: FillContext) => ctx.meta.ein,
      format: "string",
      irsLine: "header",
      description: "Employer Identification Number (EIN)",
    },

    // ── Part I – Financial Information and Net Income (Loss) Reconciliation ───
    // Line 4a – Total assets: available from QBO balance sheet
    {
      pdfFieldName: `${PAGE1}f1_10[0]`,
      factName: "total_assets",
      format: "currency",
      irsLine: "4a",
      description: "Total assets at end of tax year",
    },

    // Line 11 – Net income (loss) per income statement
    {
      pdfFieldName: `${PAGE1}f1_20[0]`,
      factName: "net_income_before_tax",
      format: "currency",
      irsLine: "11",
      description: "Net income (loss) per income statement",
    },

    // ── Part II – Reconciliation of Net Income (Loss) per Income Statement
    //              with Taxable Income per Return ──────────────────────────────
    // Lines 1–26 require book-to-tax difference detail per income/expense
    // category; most require manual analysis beyond QBO facts.
    // Key lines populated where facts are available:

    // Line 1 – Income (loss) from equity method foreign corporations (placeholder)
    {
      pdfFieldName: `${PAGE1}f1_31[0]`,
      compute: () => "0",
      format: "currency",
      irsLine: "Pt II, 1",
      description: "Income from equity method foreign corporations – book (placeholder)",
    },
    {
      pdfFieldName: `${PAGE1}f1_32[0]`,
      compute: () => "0",
      format: "currency",
      irsLine: "Pt II, 1",
      description: "Income from equity method foreign corporations – temp diff (placeholder)",
    },
    {
      pdfFieldName: `${PAGE1}f1_33[0]`,
      compute: () => "0",
      format: "currency",
      irsLine: "Pt II, 1",
      description: "Income from equity method foreign corporations – perm diff (placeholder)",
    },
    {
      pdfFieldName: `${PAGE1}f1_34[0]`,
      compute: () => "0",
      format: "currency",
      irsLine: "Pt II, 1",
      description: "Income from equity method foreign corporations – tax (placeholder)",
    },

    // ── Part III – Reconciliation of Net Income (Loss) per Income Statement
    //               with Taxable Income per Return – Expense/Deduction Items ───
    // Lines 1–38 require per-category book/tax differences; placeholders only.

    // Line 38 – Total expense/deduction items
    {
      pdfFieldName: `${PAGE1}f1_350[0]`,
      compute: () => "0",
      format: "currency",
      irsLine: "Pt III, 38",
      description: "Total expense/deduction items – book (placeholder)",
    },
    {
      pdfFieldName: `${PAGE1}f1_351[0]`,
      compute: () => "0",
      format: "currency",
      irsLine: "Pt III, 38",
      description: "Total expense/deduction items – temp diff (placeholder)",
    },
    {
      pdfFieldName: `${PAGE1}f1_352[0]`,
      compute: () => "0",
      format: "currency",
      irsLine: "Pt III, 38",
      description: "Total expense/deduction items – perm diff (placeholder)",
    },
    {
      pdfFieldName: `${PAGE1}f1_353[0]`,
      compute: () => "0",
      format: "currency",
      irsLine: "Pt III, 38",
      description: "Total expense/deduction items – tax (placeholder)",
    },

    // ── Auto-generated mappings (remaining fields) ──────────────────
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_5[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q5"), format: "boolean", description: "Checkbox: p1_q5" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_7[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q7"), format: "boolean", description: "Checkbox: p1_q7" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_7[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q7"), format: "boolean", description: "Checkbox: p1_q7" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_9[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q9"), format: "boolean", description: "Checkbox: p1_q9" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_9[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q9"), format: "boolean", description: "Checkbox: p1_q9" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_11[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q11"), format: "boolean", description: "Checkbox: p1_q11" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_11[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q11"), format: "boolean", description: "Checkbox: p1_q11" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_13[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q13"), format: "boolean", description: "Checkbox: p1_q13" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_13[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q13"), format: "boolean", description: "Checkbox: p1_q13" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_15[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q15"), format: "boolean", description: "Checkbox: p1_q15" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_15[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q15"), format: "boolean", description: "Checkbox: p1_q15" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_17[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q17"), format: "boolean", description: "Checkbox: p1_q17" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_17[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q17"), format: "boolean", description: "Checkbox: p1_q17" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_17[2]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q17"), format: "boolean", description: "Checkbox: p1_q17" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_17[3]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q17"), format: "boolean", description: "Checkbox: p1_q17" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_17[4]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q17"), format: "boolean", description: "Checkbox: p1_q17" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_1[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q1"), format: "boolean", description: "Checkbox: p2_q1" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_2[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q2"), format: "boolean", description: "Checkbox: p2_q2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_3[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q3"), format: "boolean", description: "Checkbox: p2_q3" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_4[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q4"), format: "boolean", description: "Checkbox: p2_q4" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_5[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q5"), format: "boolean", description: "Checkbox: p2_q5" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_6[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q6"), format: "boolean", description: "Checkbox: p2_q6" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_7[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q7"), format: "boolean", description: "Checkbox: p2_q7" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln1_Row[0].f2_7[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln1_Row[0].f2_R1[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln2_row[0].f2_8[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln2_row[0].f2_9[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln2_row[0].f2_10[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln2_row[0].f2_11[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln3_Row[0].f2_R2[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln3_Row[0].f2_12[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln3_Row[0].f2_13[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln3_Row[0].f2_14[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln4_Row[0].f2_R3[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln4_Row[0].f2_15[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln4_Row[0].f2_16[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln4_Row[0].f2_17[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln5_Row[0].f2_18[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln5_Row[0].f2_19[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln5_Row[0].f2_20[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln5_Row[0].f2_R4[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln6_Row[0].f2_21[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln6_Row[0].f2_22[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln6_Row[0].f2_23[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln6_Row[0].f2_R5[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln7_Row[0].f2_24[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln7_Row[0].f2_25[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln7_Row[0].f2_26[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln7_Row[0].f2_27[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln8_Row[0].f2_28[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln8_Row[0].f2_29[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln8_Row[0].f2_30[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln8_Row[0].f2_R6[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln9_Row[0].f2_31[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln9_Row[0].f2_32[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln9_Row[0].f2_33[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln9_Row[0].f2_34[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln10_Row[0].f2_35[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln10_Row[0].f2_36[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln10_Row[0].f2_37[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln10_Row[0].f2_38[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln11_Row[0].f2_39[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln11_Row[0].f2_40[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln11_Row[0].f2_41[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln11_Row[0].f2_42[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln12_Row[0].f2_43[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln12_Row[0].f2_44[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln12_Row[0].f2_45[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln12_Row[0].f2_46[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln13_Row[0].f2_47[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln13_Row[0].f2_48[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln13_Row[0].f2_49[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln13_Row[0].f2_50[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln14_Row[0].f2_51[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln14_Row[0].f2_52[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln14_Row[0].f2_53[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln14_Row[0].f2_54[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln15_Row[0].f2_55[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln15_Row[0].f2_56[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln15_Row[0].f2_57[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln15_Row[0].f2_58[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln16_Row[0].f2_59[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln16_Row[0].f2_60[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln16_Row[0].f2_61[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln16_Row[0].f2_62[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln17_Row[0].f2_63[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln17_Row[0].f2_64[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln17_Row[0].f2_65[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln17_Row[0].f2_66[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln18_Row[0].f2_67[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln18_Row[0].f2_68[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln18_Row[0].f2_69[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln18_Row[0].f2_70[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln19_Row[0].f2_R7[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln19_Row[0].f2_71[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln19_Row[0].f2_72[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln19_Row[0].f2_73[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln20_Row[0].f2_74[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln20_Row[0].f2_75[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln20_Row[0].f2_76[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln20_Row[0].f2_77[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln21_Row[0].f2_78[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln21_Row[0].f2_79[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln21_Row[0].f2_80[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln21_Row[0].f2_81[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln22_Row[0].f2_82[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln22_Row[0].f2_83[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln22_Row[0].f2_84[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln22_Row[0].f2_85[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln23a_Row[0].f2_83[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln23a_Row[0].f2_84[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln23a_Row[0].f2_85[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln23a_Row[0].f2_R8[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln23b_Row[0].f2_R9[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln23b_Row[0].f2_86[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln23b_Row[0].f2_87[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln23b_Row[0].f2_88[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln23c_Row[0].f2_R10[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln23c_Row[0].f2_89[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln23c_Row[0].f2_90[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln23c_Row[0].f2_91[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln23d_Row[0].f2_R11[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln23d_Row[0].f2_92[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln23d_Row[0].f2_93[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln23d_Row[0].f2_94[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln23e_Row[0].f2_R12[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln23e_Row[0].f2_95[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln23e_Row[0].f2_96[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln23e_Row[0].f2_97[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln23f_Row[0].f2_R13[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln23f_Row[0].f2_98[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln23f_Row[0].f2_99[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln23f_Row[0].f2_100[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln23g_Row[0].f2_R14[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln23g_Row[0].f2_101[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln23g_Row[0].f2_102[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln23g_Row[0].f2_103[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln24_Row[0].f2_R15[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln24_Row[0].f2_104[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln24_Row[0].f2_105[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln24_Row[0].f2_106[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln25_Row[0].f2_107[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln25_Row[0].f2_108[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln25_Row[0].f2_109[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln25_Row[0].f2_110[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln26_Row[0].f2_111[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln26_Row[0].f2_112[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln26_Row[0].f2_113[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln26_Row[0].f2_114[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln27_Row[0].f2_115[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln27_Row[0].f2_116[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln27_Row[0].f2_117[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln27_Row[0].f2_118[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln28_Row[0].f2_119[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln28_Row[0].f2_R16[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln28_Row[0].f2_R17[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln28_Row[0].f2_120[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln29a_Row[0].f2_121[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln29a_Row[0].f2_122[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln29a_Row[0].f2_123[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln29a_Row[0].f2_124[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln29b_Row[0].f2_125[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln29b_Row[0].f2_126[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln29b_Row[0].f2_127[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln29b_Row[0].f2_128[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln29c_Row[0].f2_129[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln29c_Row[0].f2_130[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln29c_Row[0].f2_131[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln29c_Row[0].f2_132[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln30_Row[0].f2_133[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln30_Row[0].f2_134[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln30_Row[0].f2_135[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2_Table[0].Ln30_Row[0].f2_136[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_1[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q1"), format: "boolean", description: "Checkbox: p3_q1" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_2[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q2"), format: "boolean", description: "Checkbox: p3_q2" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_3[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q3"), format: "boolean", description: "Checkbox: p3_q3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_4[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q4"), format: "boolean", description: "Checkbox: p3_q4" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_5[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q5"), format: "boolean", description: "Checkbox: p3_q5" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_6[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q6"), format: "boolean", description: "Checkbox: p3_q6" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_7[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q7"), format: "boolean", description: "Checkbox: p3_q7" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln1_Row[0].f3_R1[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln2_Row[0].f3_R2[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln4_Row[0].f3_R3[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln6_Row[0].f3_23[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln6_Row[0].f3_24[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln6_Row[0].f3_R4[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln7_Row[0].f3_25[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln7_Row[0].f3_26[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln7_Row[0].f3_27[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln7_Row[0].f3_28[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln8_Row[0].f3_29[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln8_Row[0].f3_30[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln8_Row[0].f3_31[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln8_Row[0].f3_32[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln9_Row[0].f3_33[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln9_Row[0].f3_34[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln9_Row[0].f3_35[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln9_Row[0].f3_36[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln11_Row[0].f3_43[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln11_Row[0].f3_44[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln12_Row[0].f3_45[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln12_Row[0].f3_46[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln12_Row[0].f3_47[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln12_Row[0].f3_48[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln13_Row[0].f3_49[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln13_Row[0].f3_50[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln13_Row[0].f3_51[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln13_Row[0].f3_52[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln14_Row[0].f3_53[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln14_Row[0].f3_54[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln14_Row[0].f3_55[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln14_Row[0].f3_56[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln15_Row[0].f3_57[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln15_Row[0].f3_58[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln15_Row[0].f3_59[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln15_Row[0].f3_60[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln16_Row[0].f3_61[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln16_Row[0].f3_62[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln16_Row[0].f3_63[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln16_Row[0].f3_64[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln17_Row[0].f3_65[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln17_Row[0].f3_66[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln17_Row[0].f3_67[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln17_Row[0].f3_68[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln18_Row[0].f3_69[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln18_Row[0].f3_70[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln18_Row[0].f3_71[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln18_Row[0].f3_72[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln19_Row[0].f3_73[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln19_Row[0].f3_74[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln19_Row[0].f3_75[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln19_Row[0].f3_76[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln20_Row[0].f3_77[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln20_Row[0].f3_78[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln20_Row[0].f3_79[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln20_Row[0].f3_80[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln21_Row[0].f3_R5[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln21_Row[0].f3_81[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln21_Row[0].f3_82[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln21_Row[0].f3_83[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln22_Row[0].f3_R6[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln22_Row[0].f3_84[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln22_Row[0].f3_85[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln22_Row[0].f3_86[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln23_Row[0].f3_87[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln23_Row[0].f3_88[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln23_Row[0].f3_89[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln23_Row[0].f3_90[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln24_Row[0].f3_91[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln24_Row[0].f3_92[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln24_Row[0].f3_93[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln24_Row[0].f3_94[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln25_Row[0].f3_95[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln25_Row[0].f3_96[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln25_Row[0].f3_97[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln25_Row[0].f3_98[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln26_Row[0].f3_99[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln26_Row[0].f3_100[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln26_Row[0].f3_101[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln26_Row[0].f3_102[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln27_Row[0].f3_103[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln27_Row[0].f3_104[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln27_Row[0].f3_105[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln27_Row[0].f3_106[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln28_Row[0].f3_107[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln28_Row[0].f3_108[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln28_Row[0].f3_109[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln28_Row[0].f3_110[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln29_Row[0].f3_111[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln29_Row[0].f3_112[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln29_Row[0].f3_113[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln29_Row[0].f3_114[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln30_Row[0].f3_115[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln30_Row[0].f3_116[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln30_Row[0].f3_117[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln30_Row[0].f3_118[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln31_Row[0].f3_119[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln31_Row[0].f3_120[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln31_Row[0].f3_121[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln31_Row[0].f3_122[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln32_Row[0].f3_123[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln32_Row[0].f3_124[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln32_Row[0].f3_125[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln32_Row[0].f3_126[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln33_Row[0].f3_127[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln33_Row[0].f3_128[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln33_Row[0].f3_129[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln33_Row[0].f3_130[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln34_Row[0].f3_131[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln34_Row[0].f3_132[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln34_Row[0].f3_133[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln34_Row[0].f3_134[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln35_Row[0].f3_135[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln35_Row[0].f3_136[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln35_Row[0].f3_137[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln35_Row[0].f3_138[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln36_Row[0].f3_139[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln36_Row[0].f3_140[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln36_Row[0].f3_141[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln36_Row[0].f3_142[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln37_Row[0].f3_143[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln37_Row[0].f3_144[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln37_Row[0].f3_145[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln37_Row[0].f3_146[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln38_Row[0].f3_147[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln38_Row[0].f3_148[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln38_Row[0].f3_149[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln38_Row[0].f3_150[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln39_Row[0].f3_151[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln39_Row[0].f3_152[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln39_Row[0].f3_153[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Part3_Table[0].Ln39_Row[0].f3_154[0]", staticValue: "", description: "Table  Line " },
  ],
};
