import type { FormPdfMapping, FillContext } from "../types";

const PAGE1 = "topmostSubform[0].Page1[0].";

export const F1125E_MAPPING: FormPdfMapping = {
  formCode: "1125-E",
  pdfFileName: "f1125e.pdf",
  taxYear: 2024,
  fields: [
    // ── Entity header ─────────────────────────────────────────────────────────
    {
      pdfFieldName: `${PAGE1}f1_1[0]`,
      compute: (ctx: FillContext) => ctx.meta.companyName,
      format: "string",
      irsLine: "header",
      description: "Name",
    },
    {
      pdfFieldName: `${PAGE1}f1_2[0]`,
      compute: (ctx: FillContext) => ctx.meta.ein,
      format: "string",
      irsLine: "header",
      description: "Employer Identification Number (EIN)",
    },

    // ── Line 1 – Officer table rows ───────────────────────────────────────────
    // Individual officer name / SSN / % ownership / amount fields require
    // per-officer payroll data not available from QBO aggregates.
    // Row 1 column fields (f1_3 through f1_9) are left as placeholders.
    {
      pdfFieldName: `${PAGE1}f1_3[0]`,
      compute: () => "",
      format: "string",
      irsLine: "1",
      description: "Officer 1 – name (placeholder)",
    },
    {
      pdfFieldName: `${PAGE1}f1_4[0]`,
      compute: () => "",
      format: "string",
      irsLine: "1",
      description: "Officer 1 – SSN (placeholder)",
    },
    {
      pdfFieldName: `${PAGE1}f1_5[0]`,
      compute: () => "",
      format: "percent",
      irsLine: "1",
      description: "Officer 1 – percent of time devoted to business (placeholder)",
    },
    {
      pdfFieldName: `${PAGE1}f1_6[0]`,
      compute: () => "",
      format: "percent",
      irsLine: "1",
      description: "Officer 1 – percent of stock owned – common (placeholder)",
    },
    {
      pdfFieldName: `${PAGE1}f1_7[0]`,
      compute: () => "",
      format: "percent",
      irsLine: "1",
      description: "Officer 1 – percent of stock owned – preferred (placeholder)",
    },
    {
      pdfFieldName: `${PAGE1}f1_8[0]`,
      compute: () => "",
      format: "currency",
      irsLine: "1",
      description: "Officer 1 – amount of compensation (placeholder)",
    },

    // ── Line 2 – Total compensation of officers ───────────────────────────────
    {
      pdfFieldName: `${PAGE1}f1_124[0]`,
      factName: "officer_compensation_total",
      format: "currency",
      irsLine: "2",
      description: "Total compensation of officers",
    },

    // ── Line 3 – Compensation of officers claimed on Schedule A or elsewhere ──
    {
      pdfFieldName: `${PAGE1}f1_125[0]`,
      compute: () => "0",
      format: "currency",
      irsLine: "3",
      description: "Compensation of officers claimed on Schedule A or elsewhere (placeholder)",
    },

    // ── Auto-generated mappings (remaining fields) ──────────────────
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow9[0].f1_52[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow9[0].f1_53[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow9[0].f1_54[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow9[0].f1_56[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow10[0].f1_57[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow10[0].f1_58[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow10[0].f1_60[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow10[0].f1_61[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow10[0].f1_62[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow11[0].f1_64[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow11[0].f1_65[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow11[0].f1_66[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow12[0].f1_72[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow12[0].f1_73[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow12[0].f1_74[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow13[0].f1_75[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow13[0].f1_76[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow13[0].f1_77[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow13[0].f1_78[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow13[0].f1_79[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow13[0].f1_80[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow14[0].f1_81[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow14[0].f1_82[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow14[0].f1_83[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow14[0].f1_84[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow14[0].f1_85[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow15[0].f1_87[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow15[0].f1_88[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow15[0].f1_89[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow15[0].f1_90[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow15[0].f1_91[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow15[0].f1_92[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow16[0].f1_93[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow16[0].f1_94[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow16[0].f1_95[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow16[0].f1_96[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow16[0].f1_97[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow16[0].f1_98[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow17[0].f1_99[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow17[0].f1_100[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow17[0].f1_101[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow17[0].f1_102[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow17[0].f1_103[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow17[0].f1_104[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow18[0].f1_105[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow18[0].f1_106[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow18[0].f1_107[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow18[0].f1_108[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow18[0].f1_109[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow18[0].f1_110[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow19[0].f1_111[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow19[0].f1_112[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow19[0].f1_113[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow19[0].f1_114[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow19[0].f1_115[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow19[0].f1_116[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow20[0].f1_117[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow20[0].f1_118[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow20[0].f1_119[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow20[0].f1_120[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow20[0].f1_121[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line1Table[0].BodyRow20[0].f1_122[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_123[0]", staticValue: "", description: "Unmapped — page 1" },
  ],
};
