import type { FormPdfMapping, FillContext } from "../types";
import { sbCheck, officer, currency } from "../types";

const PAGE1 = "topmostSubform[0].Page1[0].";

export const F1120S_MAPPING: FormPdfMapping = {
  formCode: "1120-S",
  pdfFileName: "f1120s.pdf",
  taxYear: 2024,
  fields: [
    // ── Calendar year header ──────────────────────────────────────────────────
    {
      pdfFieldName: `${PAGE1}f1_1[0]`,
      compute: (ctx: FillContext) => String(ctx.meta.taxYear),
      format: "string",
      irsLine: "header",
      description: "Tax year begin",
    },
    {
      pdfFieldName: `${PAGE1}f1_2[0]`,
      compute: (ctx: FillContext) => String(ctx.meta.taxYear),
      format: "string",
      irsLine: "header",
      description: "Tax year end year",
    },
    {
      pdfFieldName: `${PAGE1}f1_3[0]`,
      compute: (ctx: FillContext) => String(ctx.meta.taxYear),
      format: "string",
      irsLine: "header",
      description: "Calendar year footer",
    },

    // ── Entity header ─────────────────────────────────────────────────────────
    {
      pdfFieldName: `${PAGE1}f1_4[0]`,
      compute: (ctx: FillContext) => ctx.meta.companyName,
      format: "string",
      irsLine: "header",
      description: "Company / corporation name",
    },
    {
      pdfFieldName: `${PAGE1}f1_5[0]`,
      compute: (ctx: FillContext) => ctx.meta.address,
      format: "string",
      irsLine: "header",
      description: "Street address",
    },
    {
      pdfFieldName: `${PAGE1}f1_6[0]`,
      compute: (ctx: FillContext) => ctx.meta.city,
      format: "string",
      irsLine: "header",
      description: "City",
    },
    {
      pdfFieldName: `${PAGE1}f1_7[0]`,
      compute: (ctx: FillContext) => ctx.meta.state,
      format: "string",
      irsLine: "header",
      description: "State",
    },
    {
      pdfFieldName: `${PAGE1}f1_8[0]`,
      compute: (ctx: FillContext) => ctx.meta.zip,
      format: "string",
      irsLine: "header",
      description: "ZIP code",
    },
    {
      pdfFieldName: `${PAGE1}f1_9[0]`,
      compute: (ctx: FillContext) => ctx.meta.ein,
      format: "string",
      irsLine: "B",
      description: "Employer Identification Number (EIN)",
    },
    {
      pdfFieldName: `${PAGE1}f1_10[0]`,
      compute: (ctx: FillContext) => ctx.meta.sElectionDate ?? "",
      format: "string",
      irsLine: "header",
      description: "Date S-corporation election took effect",
    },

    // ── Income (Lines 1a – 6) ─────────────────────────────────────────────────
    {
      pdfFieldName: `${PAGE1}f1_14[0]`,
      factName: "gross_receipts_total",
      format: "currency",
      irsLine: "1a",
      description: "Gross receipts or sales",
    },
    {
      pdfFieldName: `${PAGE1}f1_15[0]`,
      factName: "returns_allowances_total",
      format: "currency",
      irsLine: "1b",
      description: "Returns and allowances",
    },
    {
      pdfFieldName: `${PAGE1}f1_16[0]`,
      compute: (ctx: FillContext) => { const gr = Number(ctx.facts.gross_receipts_total ?? 0); const ra = Number(ctx.facts.returns_allowances_total ?? 0); return String(gr - ra); },
      format: "currency",
      irsLine: "1c",
      description: "Balance (Line 1a minus 1b)",
    },
    {
      pdfFieldName: `${PAGE1}f1_17[0]`,
      factName: "cogs_total",
      format: "currency",
      irsLine: "2",
      description: "Cost of goods sold (Schedule A)",
    },
    {
      pdfFieldName: `${PAGE1}f1_18[0]`,
      factName: "gross_profit",
      format: "currency",
      irsLine: "3",
      description: "Gross profit (Line 1c minus Line 2)",
    },
    {
      pdfFieldName: `${PAGE1}f1_19[0]`,
      factName: "capital_gain_total",
      format: "currency",
      irsLine: "4",
      description: "Net gain (loss) from Form 4797",
    },
    {
      pdfFieldName: `${PAGE1}f1_20[0]`,
      factName: "other_income_total",
      format: "currency",
      irsLine: "5",
      description: "Other income (loss)",
    },
    {
      pdfFieldName: `${PAGE1}f1_21[0]`,
      factName: "total_income",
      format: "currency",
      irsLine: "6",
      description: "Total income (loss) (Lines 3 through 5)",
    },

    // ── Deductions (Lines 7 – 20) ─────────────────────────────────────────────
    {
      pdfFieldName: `${PAGE1}f1_22[0]`,
      factName: "officer_compensation_total",
      format: "currency",
      irsLine: "7",
      description: "Compensation of officers",
    },
    {
      pdfFieldName: `${PAGE1}f1_23[0]`,
      factName: "wages_total",
      format: "currency",
      irsLine: "8",
      description: "Salaries and wages (less employment credits)",
    },
    {
      pdfFieldName: `${PAGE1}f1_24[0]`,
      factName: "repairs_total",
      format: "currency",
      irsLine: "9",
      description: "Repairs and maintenance",
    },
    {
      pdfFieldName: `${PAGE1}f1_25[0]`,
      factName: "bad_debt_total",
      format: "currency",
      irsLine: "10",
      description: "Bad debts",
    },
    {
      pdfFieldName: `${PAGE1}f1_26[0]`,
      factName: "rent_building_total",
      format: "currency",
      irsLine: "11",
      description: "Rents",
    },
    {
      pdfFieldName: `${PAGE1}f1_27[0]`,
      factName: "taxes_licenses_total",
      format: "currency",
      irsLine: "12",
      description: "Taxes and licenses",
    },
    {
      pdfFieldName: `${PAGE1}f1_28[0]`,
      factName: "interest_expense_total",
      format: "currency",
      irsLine: "13",
      description: "Interest",
    },
    {
      pdfFieldName: `${PAGE1}f1_29[0]`,
      factName: "depreciation_total",
      format: "currency",
      irsLine: "14",
      description: "Depreciation not claimed on Schedule A or elsewhere",
    },
    {
      pdfFieldName: `${PAGE1}f1_30[0]`,
      factName: "depletion_total",
      format: "currency",
      irsLine: "15",
      description: "Depletion (do not deduct oil and gas depletion)",
    },
    {
      pdfFieldName: `${PAGE1}f1_31[0]`,
      factName: "advertising_total",
      format: "currency",
      irsLine: "16",
      description: "Advertising",
    },
    {
      pdfFieldName: `${PAGE1}f1_32[0]`,
      factName: "pension_profitsharing_total",
      format: "currency",
      irsLine: "17",
      description: "Pension, profit-sharing, etc., plans",
    },
    {
      pdfFieldName: `${PAGE1}f1_33[0]`,
      factName: "employee_benefits_total",
      format: "currency",
      irsLine: "18",
      description: "Employee benefit programs",
    },
    {
      pdfFieldName: `${PAGE1}f1_34[0]`,
      factName: "general_deduction_total",
      format: "currency",
      irsLine: "19",
      description: "Other deductions (attach statement)",
    },
    {
      pdfFieldName: `${PAGE1}f1_35[0]`,
      factName: "total_deductions",
      format: "currency",
      irsLine: "20",
      description: "Total deductions (add Lines 7 through 19)",
    },

    // ── Tax and payments (Lines 21 – 26) ─────────────────────────────────────
    {
      pdfFieldName: `${PAGE1}f1_36[0]`,
      factName: "ordinary_business_income",
      format: "currency",
      irsLine: "21",
      description: "Ordinary business income (loss) (Line 6 minus Line 20)",
    },
    {
      pdfFieldName: `${PAGE1}f1_37[0]`,
      manual: true,
      format: "currency",
      irsLine: "22a",
      description: "Tax: excess net passive income or LIFO recapture",
    },
    {
      pdfFieldName: `${PAGE1}f1_38[0]`,
      manual: true,
      format: "currency",
      irsLine: "22b",
      description: "Tax: built-in gains",
    },
    {
      pdfFieldName: `${PAGE1}f1_39[0]`,
      compute: (_ctx: FillContext) => "0",
      format: "currency",
      irsLine: "22c",
      description: "Total tax (Line 22a plus 22b)",
    },
    {
      pdfFieldName: `${PAGE1}f1_40[0]`,
      factName: "estimated_tax_payments_total",
      format: "currency",
      irsLine: "23",
      description: "Payments (Form 2439, etc.)",
    },
    {
      pdfFieldName: `${PAGE1}f1_41[0]`,
      factName: "estimated_tax_penalty",
      format: "currency",
      irsLine: "24",
      description: "Estimated tax penalty",
    },
    {
      pdfFieldName: `${PAGE1}f1_42[0]`,
      compute: (ctx: FillContext) => { const tax = 0; const payments = Number(ctx.facts.estimated_tax_payments_total ?? 0); return String(Math.max(0, tax - payments)); },
      format: "currency",
      irsLine: "25",
      description: "Amount owed",
    },
    {
      pdfFieldName: `${PAGE1}f1_43[0]`,
      compute: (ctx: FillContext) => { const payments = Number(ctx.facts.estimated_tax_payments_total ?? 0); return payments > 0 ? String(payments) : ""; },
      format: "currency",
      irsLine: "26",
      description: "Overpayment",
    },

    // ── Auto-generated mappings (remaining fields) ──────────────────
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_2[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q2"), format: "boolean", description: "Checkbox: p1_q2" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_6[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q6"), format: "boolean", description: "Checkbox: p1_q6" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_7[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q7"), format: "boolean", description: "Checkbox: p1_q7" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_8[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q8"), format: "boolean", description: "Checkbox: p1_q8" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_8[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q8"), format: "boolean", description: "Checkbox: p1_q8" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_9[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q9"), format: "boolean", description: "Checkbox: p1_q9" },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_52[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_53[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].Routing_Number[0].f1_54[0]", manual: true, description: "banking_info" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_10[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q10"), format: "boolean", description: "Checkbox: p1_q10" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_10[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q10"), format: "boolean", description: "Checkbox: p1_q10" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_11[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q11"), format: "boolean", description: "Checkbox: p1_q11" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_11[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q11"), format: "boolean", description: "Checkbox: p1_q11" },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_56[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_57[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_12[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q12"), format: "boolean", description: "Checkbox: p1_q12" },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_58[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_60[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_61[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_62[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_1[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q1"), format: "boolean", description: "Checkbox: p2_q1" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_1[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q1"), format: "boolean", description: "Checkbox: p2_q1" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_1[2]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q1"), format: "boolean", description: "Checkbox: p2_q1" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_2[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q2"), format: "boolean", description: "Checkbox: p2_q2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_2[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q2"), format: "boolean", description: "Checkbox: p2_q2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_3[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q3"), format: "boolean", description: "Checkbox: p2_q3" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_3[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q3"), format: "boolean", description: "Checkbox: p2_q3" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4a[0].BodyRow1[0].f2_7[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4a[0].BodyRow1[0].f2_8[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4a[0].BodyRow2[0].f2_9[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4a[0].BodyRow2[0].f2_10[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4a[0].BodyRow2[0].f2_11[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4a[0].BodyRow2[0].f2_12[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4a[0].BodyRow2[0].f2_13[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4a[0].BodyRow3[0].f2_14[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4a[0].BodyRow3[0].f2_15[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4a[0].BodyRow3[0].f2_16[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4a[0].BodyRow3[0].f2_17[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4a[0].BodyRow3[0].f2_18[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4a[0].BodyRow4[0].f2_19[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4a[0].BodyRow4[0].f2_20[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4a[0].BodyRow4[0].f2_21[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4a[0].BodyRow4[0].f2_22[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4a[0].BodyRow4[0].f2_23[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_4[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q4"), format: "boolean", description: "Checkbox: p2_q4" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_4[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q4"), format: "boolean", description: "Checkbox: p2_q4" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4b[0].BodyRow1[0].f2_24[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4b[0].BodyRow1[0].f2_25[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4b[0].BodyRow1[0].f2_26[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4b[0].BodyRow1[0].f2_27[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4b[0].BodyRow1[0].f2_28[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4b[0].BodyRow2[0].f2_29[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4b[0].BodyRow2[0].f2_30[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4b[0].BodyRow2[0].f2_31[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4b[0].BodyRow2[0].f2_32[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4b[0].BodyRow2[0].f2_33[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4b[0].BodyRow3[0].f2_34[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4b[0].BodyRow3[0].f2_35[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4b[0].BodyRow3[0].f2_36[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4b[0].BodyRow3[0].f2_37[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4b[0].BodyRow3[0].f2_38[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4b[0].BodyRow4[0].f2_39[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4b[0].BodyRow4[0].f2_40[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4b[0].BodyRow4[0].f2_41[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4b[0].BodyRow4[0].f2_42[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line4b[0].BodyRow4[0].f2_43[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_5[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q5"), format: "boolean", description: "Checkbox: p2_q5" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_5[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q5"), format: "boolean", description: "Checkbox: p2_q5" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_44[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_45[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_6[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q6"), format: "boolean", description: "Checkbox: p2_q6" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_6[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q6"), format: "boolean", description: "Checkbox: p2_q6" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_46[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_47[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_7[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q7"), format: "boolean", description: "Checkbox: p2_q7" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_7[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q7"), format: "boolean", description: "Checkbox: p2_q7" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_8[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q8"), format: "boolean", description: "Checkbox: p2_q8" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_48[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_9[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q9"), format: "boolean", description: "Checkbox: p2_q9" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_9[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q9"), format: "boolean", description: "Checkbox: p2_q9" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_10[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q10"), format: "boolean", description: "Checkbox: p2_q10" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_10[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q10"), format: "boolean", description: "Checkbox: p2_q10" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_11[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q11"), format: "boolean", description: "Checkbox: p2_q11" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_11[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q11"), format: "boolean", description: "Checkbox: p2_q11" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_1[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q1"), format: "boolean", description: "Checkbox: p3_q1" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_1[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q1"), format: "boolean", description: "Checkbox: p3_q1" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_2[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q2"), format: "boolean", description: "Checkbox: p3_q2" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_2[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q2"), format: "boolean", description: "Checkbox: p3_q2" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_3[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q3"), format: "boolean", description: "Checkbox: p3_q3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_3[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q3"), format: "boolean", description: "Checkbox: p3_q3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_4[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q4"), format: "boolean", description: "Checkbox: p3_q4" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_4[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q4"), format: "boolean", description: "Checkbox: p3_q4" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_5[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q5"), format: "boolean", description: "Checkbox: p3_q5" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_5[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q5"), format: "boolean", description: "Checkbox: p3_q5" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_6[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q6"), format: "boolean", description: "Checkbox: p3_q6" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_6[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q6"), format: "boolean", description: "Checkbox: p3_q6" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_7[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q7"), format: "boolean", description: "Checkbox: p3_q7" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_7[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q7"), format: "boolean", description: "Checkbox: p3_q7" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_23[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_24[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_25[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_26[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_27[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_28[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_29[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_30[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_31[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_32[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_33[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_34[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_35[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_36[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_7[2]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q7"), format: "boolean", description: "Checkbox: p3_q7" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_8[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q8"), format: "boolean", description: "Checkbox: p3_q8" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_43[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_44[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_45[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_46[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_47[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_48[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page4[0].f4_1[0]", staticValue: "", description: "Unmapped — page 4" },
    { pdfFieldName: "topmostSubform[0].Page4[0].f4_2[0]", staticValue: "", description: "Unmapped — page 4" },
    { pdfFieldName: "topmostSubform[0].Page4[0].f4_3[0]", staticValue: "", description: "Unmapped — page 4" },
    { pdfFieldName: "topmostSubform[0].Page4[0].f4_4[0]", staticValue: "", description: "Unmapped — page 4" },
    { pdfFieldName: "topmostSubform[0].Page5[0].SchM-1_Left[0].f5_9[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].SchM-1_Left[0].f5_10[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].SchM-1_Right[0].f5_18[0]", staticValue: "", description: "Unmapped — page 5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].Table_SchM-2[0].Line1[0].f5_21[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page5[0].Table_SchM-2[0].Line1[0].f5_22[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page5[0].Table_SchM-2[0].Line2[0].f5_24[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page5[0].Table_SchM-2[0].Line2[0].f5_25[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page5[0].Table_SchM-2[0].Line2[0].f5_26[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page5[0].Table_SchM-2[0].Line3[0].f5_29[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page5[0].Table_SchM-2[0].Line3[0].f5_30[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page5[0].Table_SchM-2[0].Line4[0].f5_32[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page5[0].Table_SchM-2[0].Line4[0].f5_33[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page5[0].Table_SchM-2[0].Line4[0].f5_34[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page5[0].Table_SchM-2[0].Line5[0].f5_37[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page5[0].Table_SchM-2[0].Line5[0].f5_38[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page5[0].Table_SchM-2[0].Line6[0].f5_40[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page5[0].Table_SchM-2[0].Line6[0].f5_41[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page5[0].Table_SchM-2[0].Line6[0].f5_42[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page5[0].Table_SchM-2[0].Line7[0].f5_44[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page5[0].Table_SchM-2[0].Line7[0].f5_45[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page5[0].Table_SchM-2[0].Line7[0].f5_46[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page5[0].Table_SchM-2[0].Line8[0].f5_49[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page5[0].Table_SchM-2[0].Line8[0].f5_50[0]", staticValue: "", description: "Table  Line " },
  ],
};
