import type { FormPdfMapping, FillContext } from "../types";
import { sbCheck, officer, currency } from "../types";

const P = "topmostSubform[0].Page1[0].";

export const F4562_MAPPING: FormPdfMapping = {
  formCode: "4562",
  pdfFileName: "f4562.pdf",
  taxYear: 2025,
  fields: [
    // -------------------------------------------------------------------------
    // Header fields
    // -------------------------------------------------------------------------
    {
      pdfFieldName: `${P}f1_1[0]`,
      compute: (ctx: FillContext) => ctx.meta.companyName,
      format: "string",
      irsLine: "Header",
      description: "Name of entity as shown on tax return",
    },
    {
      pdfFieldName: `${P}f1_2[0]`,
      manual: true, // TODO: wire to factName
      compute: (ctx: FillContext) => ctx.facts.principal_business_activity as string ?? "",
      format: "string",
      irsLine: "Header",
      description: "Business or activity to which this form relates",
    },
    {
      pdfFieldName: `${P}f1_3[0]`,
      compute: (ctx: FillContext) => ctx.meta.ein,
      format: "string",
      irsLine: "Header",
      description: "Employer Identification Number (EIN)",
    },

    // -------------------------------------------------------------------------
    // Part I — Election To Expense Certain Property Under Section 179
    // -------------------------------------------------------------------------
    {
      pdfFieldName: `${P}f1_4[0]`,
      compute: (ctx: FillContext) => {
        const yr = ctx.meta.taxYear;
        const limits: Record<number, number> = { 2023: 1160000, 2024: 1220000, 2025: 1250000, 2026: 1290000 };
        return String(limits[yr] ?? 1250000);
      },
      format: "currency",
      irsLine: "1",
      description: "Maximum amount (inflation-adjusted annually)",
    },
    {
      pdfFieldName: `${P}f1_5[0]`,
      factName: "depr_179_eligible_cost",
      format: "currency",
      irsLine: "2",
      description: "Total cost of section 179 property placed in service",
    },
    {
      pdfFieldName: `${P}f1_6[0]`,
      compute: (ctx: FillContext) => {
        const yr = ctx.meta.taxYear;
        const thresholds: Record<number, number> = { 2023: 2890000, 2024: 3050000, 2025: 3130000, 2026: 3220000 };
        return String(thresholds[yr] ?? 3130000);
      },
      format: "currency",
      irsLine: "3",
      description: "Threshold cost before phase-out begins (inflation-adjusted)",
    },
    {
      pdfFieldName: `${P}f1_9[0]`,
      compute: (ctx: FillContext) => {
        const yr = ctx.meta.taxYear;
        const limits: Record<number, number> = { 2023: 1160000, 2024: 1220000, 2025: 1250000, 2026: 1290000 };
        const max = limits[yr] ?? 1250000;
        const cost = Number(ctx.facts.depr_179_eligible_cost ?? ctx.facts.section_179_eligible_cost ?? 0);
        return String(Math.min(max, cost));
      },
      format: "currency",
      irsLine: "5",
      description: "Dollar limitation for tax year (line 1 minus line 4, not less than zero)",
    },
    {
      pdfFieldName: `${P}f1_12[0]`,
      factName: "taxable_income_before_nol",
      format: "currency",
      irsLine: "11",
      description: "Business income limitation for section 179 deduction",
    },
    {
      pdfFieldName: `${P}f1_13[0]`,
      factName: "depr_section_179_total",
      format: "currency",
      irsLine: "12",
      description: "Section 179 expense deduction (lesser of line 5, 6, or 11)",
    },

    // -------------------------------------------------------------------------
    // Part II — Special Depreciation Allowance and Other Depreciation
    // -------------------------------------------------------------------------
    {
      pdfFieldName: `${P}f1_14[0]`,
      factName: "depr_bonus_total",
      format: "currency",
      irsLine: "14",
      description: "Special depreciation allowance (bonus depreciation) for qualified property",
    },

    // -------------------------------------------------------------------------
    // Part III — MACRS Depreciation
    // -------------------------------------------------------------------------
    {
      pdfFieldName: `${P}f1_17[0]`,
      factName: "depr_macrs_prior_year",
      format: "currency",
      irsLine: "17",
      description: "MACRS deductions for assets placed in service in tax years beginning before 2025",
    },
    {
      pdfFieldName: `${P}f1_22[0]`,
      factName: "depr_total_all",
      format: "currency",
      irsLine: "22",
      description: "Total depreciation (add amounts in column (g), lines 15 through 21)",
    },

    // ── Auto-generated mappings (remaining fields) ──────────────────
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19e[0].f1_52[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19e[0].f1_53[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19e[0].f1_54[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19f[0].f1_56[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19f[0].f1_57[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19f[0].f1_58[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19f[0].f1_60[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19f[0].f1_61[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19g[0].f1_62[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19g[0].f1_64[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19g[0].f1_65[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19g[0].f1_66[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19h[0].f1_72[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19h[0].f1_73[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19i_1[0].f1_74[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19i_1[0].f1_75[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19i_1[0].f1_76[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19i_1[0].f1_77[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19i_1[0].f1_78[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19i_1[0].f1_79[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19i_2[0].f1_80[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19i_2[0].f1_81[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19i_2[0].f1_82[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19i_2[0].f1_83[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19i_2[0].f1_84[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19i_2[0].f1_85[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19j_1[0].f1_87[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19j_1[0].f1_88[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19j_1[0].f1_89[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19j_1[0].f1_90[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19j_1[0].f1_91[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19j_2[0].f1_92[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19j_2[0].f1_93[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19j_2[0].f1_94[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19j_2[0].f1_95[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19j_2[0].f1_96[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionBTable[0].Line19j_2[0].f1_97[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionCTable[0].Line20a[0].f1_98[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionCTable[0].Line20a[0].f1_99[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionCTable[0].Line20a[0].f1_100[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionCTable[0].Line20a[0].f1_101[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionCTable[0].Line20a[0].f1_102[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionCTable[0].Line20a[0].f1_103[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionCTable[0].Line20b[0].f1_104[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionCTable[0].Line20b[0].f1_105[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionCTable[0].Line20b[0].f1_106[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionCTable[0].Line20b[0].f1_107[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionCTable[0].Line20b[0].f1_108[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionCTable[0].Line20b[0].f1_109[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionCTable[0].Line20c[0].f1_110[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionCTable[0].Line20c[0].f1_111[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionCTable[0].Line20c[0].f1_112[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionCTable[0].Line20c[0].f1_113[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionCTable[0].Line20c[0].f1_114[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionCTable[0].Line20c[0].f1_115[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionCTable[0].Line20d[0].f1_116[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionCTable[0].Line20d[0].f1_117[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionCTable[0].Line20d[0].f1_118[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionCTable[0].Line20d[0].f1_119[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionCTable[0].Line20d[0].f1_120[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionCTable[0].Line20d[0].f1_121[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionCTable[0].Line20e[0].f1_122[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionCTable[0].Line20e[0].f1_123[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionCTable[0].Line20e[0].f1_126[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].SectionCTable[0].Line20e[0].f1_127[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_1[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q1"), format: "boolean", description: "Checkbox: p2_q1" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_1[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q1"), format: "boolean", description: "Checkbox: p2_q1" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_2[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q2"), format: "boolean", description: "Checkbox: p2_q2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_2[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q2"), format: "boolean", description: "Checkbox: p2_q2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_3[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q3"), format: "boolean", description: "Checkbox: p2_q3" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_3[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q3"), format: "boolean", description: "Checkbox: p2_q3" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_3[2]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q3"), format: "boolean", description: "Checkbox: p2_q3" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln26[0].BodyRow1[0].f2_7[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln26[0].BodyRow1[0].f2_8[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln26[0].BodyRow1[0].f2_9[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln26[0].BodyRow1[0].f2_10[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln26[0].BodyRow1[0].f2_11[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln26[0].BodyRow1[0].f2_12[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln26[0].BodyRow1[0].f2_13[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln26[0].BodyRow1[0].f2_14[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln26[0].BodyRow2[0].f2_15[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln26[0].BodyRow2[0].f2_16[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln26[0].BodyRow2[0].f2_17[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln26[0].BodyRow2[0].f2_18[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln26[0].BodyRow2[0].f2_19[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln26[0].BodyRow2[0].f2_20[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln26[0].BodyRow2[0].f2_21[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln26[0].BodyRow2[0].f2_22[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln26[0].BodyRow2[0].f2_23[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln26[0].BodyRow3[0].f2_24[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln26[0].BodyRow3[0].f2_25[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln26[0].BodyRow3[0].f2_26[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln26[0].BodyRow3[0].f2_27[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln26[0].BodyRow3[0].f2_28[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln26[0].BodyRow3[0].f2_29[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln26[0].BodyRow3[0].f2_30[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln26[0].BodyRow3[0].f2_31[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln26[0].BodyRow3[0].f2_32[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln27[0].BodyRow1[0].f2_33[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln27[0].BodyRow1[0].f2_34[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln27[0].BodyRow1[0].f2_35[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln27[0].BodyRow1[0].f2_36[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln27[0].BodyRow1[0].f2_37[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln27[0].BodyRow1[0].f2_38[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln27[0].BodyRow1[0].f2_39[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln27[0].BodyRow1[0].f2_40[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln27[0].BodyRow2[0].f2_41[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln27[0].BodyRow2[0].f2_42[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln27[0].BodyRow2[0].f2_43[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln27[0].BodyRow2[0].f2_44[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln27[0].BodyRow2[0].f2_45[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln27[0].BodyRow2[0].f2_46[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln27[0].BodyRow2[0].f2_47[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln27[0].BodyRow2[0].f2_48[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln27[0].BodyRow3[0].f2_49[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln27[0].BodyRow3[0].f2_50[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln27[0].BodyRow3[0].f2_51[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln27[0].BodyRow3[0].f2_52[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln27[0].BodyRow3[0].f2_53[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln27[0].BodyRow3[0].f2_54[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln27[0].BodyRow3[0].f2_55[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln27[0].BodyRow3[0].f2_56[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_57[0]", manual: true, description: "Depreciation schedule row" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_58[0]", manual: true, description: "Depreciation schedule row" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln30-33[0].Line30[0].f2_59[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln30-33[0].Line30[0].f2_60[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln30-33[0].Line30[0].f2_61[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln30-33[0].Line30[0].f2_62[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln30-33[0].Line30[0].f2_63[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln30-33[0].Line30[0].f2_64[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln30-33[0].Line31[0].f2_65[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln30-33[0].Line31[0].f2_66[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln30-33[0].Line31[0].f2_67[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln30-33[0].Line31[0].f2_68[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln30-33[0].Line31[0].f2_69[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln30-33[0].Line31[0].f2_70[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln30-33[0].Line32[0].f2_71[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln30-33[0].Line32[0].f2_72[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln30-33[0].Line32[0].f2_73[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln30-33[0].Line32[0].f2_74[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln30-33[0].Line32[0].f2_75[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln30-33[0].Line32[0].f2_76[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln30-33[0].Line33[0].f2_77[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln30-33[0].Line33[0].f2_78[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln30-33[0].Line33[0].f2_79[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln30-33[0].Line33[0].f2_80[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln30-33[0].Line33[0].f2_81[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Ln30-33[0].Line33[0].f2_82[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line34[0].c2_4[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q4"), format: "boolean", description: "Checkbox: p2_q4" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line34[0].c2_4[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q4"), format: "boolean", description: "Checkbox: p2_q4" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line34[0].c2_5[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q5"), format: "boolean", description: "Checkbox: p2_q5" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line34[0].c2_5[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q5"), format: "boolean", description: "Checkbox: p2_q5" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line34[0].c2_6[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q6"), format: "boolean", description: "Checkbox: p2_q6" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line34[0].c2_6[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q6"), format: "boolean", description: "Checkbox: p2_q6" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line34[0].c2_7[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q7"), format: "boolean", description: "Checkbox: p2_q7" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line34[0].c2_7[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q7"), format: "boolean", description: "Checkbox: p2_q7" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line34[0].c2_8[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q8"), format: "boolean", description: "Checkbox: p2_q8" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line34[0].c2_8[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q8"), format: "boolean", description: "Checkbox: p2_q8" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line34[0].c2_9[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q9"), format: "boolean", description: "Checkbox: p2_q9" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line34[0].c2_9[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q9"), format: "boolean", description: "Checkbox: p2_q9" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line35[0].c2_10[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q10"), format: "boolean", description: "Checkbox: p2_q10" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line35[0].c2_10[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q10"), format: "boolean", description: "Checkbox: p2_q10" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line35[0].c2_11[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q11"), format: "boolean", description: "Checkbox: p2_q11" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line35[0].c2_11[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q11"), format: "boolean", description: "Checkbox: p2_q11" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line35[0].c2_12[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q12"), format: "boolean", description: "Checkbox: p2_q12" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line35[0].c2_12[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q12"), format: "boolean", description: "Checkbox: p2_q12" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line35[0].c2_13[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q13"), format: "boolean", description: "Checkbox: p2_q13" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line35[0].c2_13[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q13"), format: "boolean", description: "Checkbox: p2_q13" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line35[0].c2_14[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q14"), format: "boolean", description: "Checkbox: p2_q14" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line35[0].c2_14[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q14"), format: "boolean", description: "Checkbox: p2_q14" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line35[0].c2_15[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q15"), format: "boolean", description: "Checkbox: p2_q15" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line35[0].c2_15[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q15"), format: "boolean", description: "Checkbox: p2_q15" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line36[0].c2_16[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q16"), format: "boolean", description: "Checkbox: p2_q16" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line36[0].c2_16[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q16"), format: "boolean", description: "Checkbox: p2_q16" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line36[0].c2_17[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q17"), format: "boolean", description: "Checkbox: p2_q17" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line36[0].c2_17[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q17"), format: "boolean", description: "Checkbox: p2_q17" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line36[0].c2_18[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q18"), format: "boolean", description: "Checkbox: p2_q18" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line36[0].c2_18[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q18"), format: "boolean", description: "Checkbox: p2_q18" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line36[0].c2_19[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q19"), format: "boolean", description: "Checkbox: p2_q19" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line36[0].c2_19[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q19"), format: "boolean", description: "Checkbox: p2_q19" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line36[0].c2_20[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q20"), format: "boolean", description: "Checkbox: p2_q20" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line36[0].c2_20[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q20"), format: "boolean", description: "Checkbox: p2_q20" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line36[0].c2_21[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q21"), format: "boolean", description: "Checkbox: p2_q21" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SectionBTable2[0].Line36[0].c2_21[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q21"), format: "boolean", description: "Checkbox: p2_q21" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_1[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q1"), format: "boolean", description: "Checkbox: p3_q1" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_1[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q1"), format: "boolean", description: "Checkbox: p3_q1" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_2[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q2"), format: "boolean", description: "Checkbox: p3_q2" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_2[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q2"), format: "boolean", description: "Checkbox: p3_q2" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_3[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q3"), format: "boolean", description: "Checkbox: p3_q3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_3[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q3"), format: "boolean", description: "Checkbox: p3_q3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_4[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q4"), format: "boolean", description: "Checkbox: p3_q4" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_4[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q4"), format: "boolean", description: "Checkbox: p3_q4" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_5[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q5"), format: "boolean", description: "Checkbox: p3_q5" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_5[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q5"), format: "boolean", description: "Checkbox: p3_q5" },
  ],
};
