import type { FormPdfMapping, FillContext } from "../types";

const PAGE1 = "topmostSubform[0].Page1[0].";

export const F4797_MAPPING: FormPdfMapping = {
  formCode: "4797",
  pdfFileName: "f4797.pdf",
  taxYear: 2024,
  fields: [
    // ── Entity header ─────────────────────────────────────────────────────────
    {
      pdfFieldName: `${PAGE1}f1_1[0]`,
      compute: (ctx: FillContext) => ctx.meta.companyName,
      format: "string",
      irsLine: "header",
      description: "Name shown on return",
    },
    {
      pdfFieldName: `${PAGE1}f1_2[0]`,
      compute: (ctx: FillContext) => ctx.meta.ein,
      format: "string",
      irsLine: "header",
      description: "Identifying number (EIN or SSN)",
    },

    // ── Part I – Sales or Exchanges of Property Used in a Trade or Business ──
    // Most Part I detail rows require sale-specific data not available from QBO.
    // Line 7 (combined gain/loss summary) would be populated by a separate
    // capital-gain fact once available.

    // ── Part II – Ordinary Gains and Losses ──────────────────────────────────
    // Line 18/19 detail rows require asset-level data; left as placeholders.
    {
      pdfFieldName: `${PAGE1}f1_86[0]`,
      compute: () => "0",
      format: "currency",
      irsLine: "18",
      description: "Ordinary gains/losses not from Part I or III (placeholder)",
    },

    // ── Part III – Gain From Disposition of Property Under Sections 1245, 1250
    // Asset-level depreciation recapture data not available from QBO.

    // ── Part IV – Recapture Amounts Under Sections 179 and 280F ─────────────
    // Requires per-asset basis data; left as placeholder.

    // ── Auto-generated mappings (remaining fields) ──────────────────
    { pdfFieldName: "topmostSubform[0].Page1[0].TableLine10[0].Row2[0].f1_52[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].TableLine10[0].Row2[0].f1_53[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].TableLine10[0].Row2[0].f1_54[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].TableLine10[0].Row3[0].f1_56[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].TableLine10[0].Row3[0].f1_57[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].TableLine10[0].Row3[0].f1_58[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].TableLine10[0].Row3[0].f1_60[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].TableLine10[0].Row3[0].f1_61[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].TableLine10[0].Row4[0].f1_62[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].TableLine10[0].Row4[0].f1_64[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].TableLine10[0].Row4[0].f1_65[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].TableLine10[0].Row4[0].f1_66[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_72[0]", manual: true, description: "Asset sale transaction row" },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_73[0]", manual: true, description: "Asset sale transaction row" },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_74[0]", manual: true, description: "Asset sale transaction row" },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_75[0]", manual: true, description: "Asset sale transaction row" },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_76[0]", manual: true, description: "Asset sale transaction row" },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_77[0]", manual: true, description: "Asset sale transaction row" },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable1[0].Row3[0].f2_7[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable1[0].Row3[0].f2_8[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable1[0].Row3[0].f2_9[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable1[0].Row4[0].f2_10[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable1[0].Row4[0].f2_11[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable1[0].Row4[0].f2_12[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row20[0].f2_13[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row20[0].f2_14[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row20[0].f2_15[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row20[0].f2_16[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row21[0].f2_17[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row21[0].f2_18[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row21[0].f2_19[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row21[0].f2_20[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row22[0].f2_21[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row22[0].f2_22[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row22[0].f2_23[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row22[0].f2_24[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row23[0].f2_25[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row23[0].f2_26[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row23[0].f2_27[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row23[0].f2_28[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row24[0].f2_29[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row24[0].f2_30[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row24[0].f2_31[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row24[0].f2_32[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row25a[0].f2_33[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row25a[0].f2_34[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row25a[0].f2_35[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row25a[0].f2_36[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row25b[0].f2_37[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row25b[0].f2_38[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row25b[0].f2_39[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row25b[0].f2_40[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row26a[0].f2_41[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row26a[0].f2_42[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row26a[0].f2_43[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row26a[0].f2_44[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row26b[0].f2_45[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row26b[0].f2_46[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row26b[0].f2_47[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row26b[0].f2_48[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row26c[0].f2_49[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row26c[0].f2_50[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row26c[0].f2_51[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row26c[0].f2_52[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row26d[0].f2_53[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row26d[0].f2_54[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row26d[0].f2_55[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row26d[0].f2_56[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row26e[0].f2_57[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row26e[0].f2_58[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row26e[0].f2_59[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row26e[0].f2_60[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row26f[0].f2_61[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row26f[0].f2_62[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row26f[0].f2_63[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row26f[0].f2_64[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row26g[0].f2_65[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row26g[0].f2_66[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row26g[0].f2_67[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row26g[0].f2_68[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row27a[0].f2_69[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row27a[0].f2_70[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row27a[0].f2_71[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row27a[0].f2_72[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row27b[0].f2_73[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row27b[0].f2_74[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row27b[0].f2_75[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row27b[0].f2_76[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row27c[0].f2_77[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row27c[0].f2_78[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row27c[0].f2_79[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row27c[0].f2_80[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row28a[0].f2_81[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row28a[0].f2_82[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row28a[0].f2_83[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row28a[0].f2_84[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row28b[0].f2_85[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row28b[0].f2_86[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row28b[0].f2_87[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row28b[0].f2_88[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row29a[0].f2_89[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row29a[0].f2_90[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row29a[0].f2_91[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row29a[0].f2_92[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row29b[0].f2_93[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row29b[0].f2_94[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row29b[0].f2_95[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIIITable2[0].Row29b[0].f2_96[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_97[0]", manual: true, description: "Asset sale transaction row" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_98[0]", manual: true, description: "Asset sale transaction row" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_99[0]", manual: true, description: "Asset sale transaction row" },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].Row33[0].f2_100[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].Row33[0].f2_101[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].Row34[0].f2_102[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].Row34[0].f2_103[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].Row35[0].f2_104[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].Row35[0].f2_105[0]", staticValue: "", description: "Table  Line " },
  ],
};
