import type { FormPdfMapping, FillContext } from "../types";
import { sbCheck, officer, currency } from "../types";

const PAGE1 = "topmostSubform[0].Page1[0].";

export const F7203_MAPPING: FormPdfMapping = {
  formCode: "7203",
  pdfFileName: "f7203.pdf",
  taxYear: 2024,
  fields: [
    // ── Entity / shareholder header ───────────────────────────────────────────
    {
      pdfFieldName: `${PAGE1}f1_01[0]`,
      compute: (ctx: FillContext) => ctx.meta.companyName,
      format: "string",
      irsLine: "header",
      description: "Name of shareholder",
    },
    {
      pdfFieldName: `${PAGE1}f1_02[0]`,
      compute: (ctx: FillContext) => ctx.meta.ein,
      format: "string",
      irsLine: "header",
      description: "Shareholder's identifying number (SSN or EIN)",
    },

    // ── Part I – Shareholder Stock Basis ─────────────────────────────────────
    // Lines 1–6 require per-shareholder stock basis data (beginning basis,
    // capital contributions, loans, distributions) not available from QBO.
    // All left as placeholders pending shareholder-level fact collection.
    {
      pdfFieldName: `${PAGE1}f1_03[0]`,
      compute: () => "0",
      format: "currency",
      irsLine: "1",
      description: "Stock basis at beginning of corporation's tax year (placeholder)",
    },
    {
      pdfFieldName: `${PAGE1}f1_04[0]`,
      compute: () => "0",
      format: "currency",
      irsLine: "2a",
      description: "Ordinary business income (placeholder)",
    },
    {
      pdfFieldName: `${PAGE1}f1_05[0]`,
      compute: () => "0",
      format: "currency",
      irsLine: "2b",
      description: "Separately stated income items (placeholder)",
    },

    // ── Part II – Shareholder Debt Basis ─────────────────────────────────────
    // Requires per-loan shareholder debt data; placeholder only.

    // ── Part III – Allowable Losses and Deductions ────────────────────────────
    // Computed from Parts I & II; placeholder only.

    // ── Auto-generated mappings (remaining fields) ──────────────────
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_6[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q6"), format: "boolean", description: "Checkbox: p1_q6" },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_SectionA[0].Header[0].aDebt1[0].c1_7[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q7"), format: "boolean", description: "Checkbox: p1_q7" },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_SectionA[0].Header[0].aDebt1[0].c1_7[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q7"), format: "boolean", description: "Checkbox: p1_q7" },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_SectionA[0].Header[0].bDebt2[0].c1_8[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q8"), format: "boolean", description: "Checkbox: p1_q8" },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_SectionA[0].Header[0].bDebt2[0].c1_8[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q8"), format: "boolean", description: "Checkbox: p1_q8" },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_SectionA[0].Header[0].cDebt3[0].c1_9[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q9"), format: "boolean", description: "Checkbox: p1_q9" },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_SectionA[0].Header[0].cDebt3[0].c1_9[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q9"), format: "boolean", description: "Checkbox: p1_q9" },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_SectionA[0].Line16[0].f2_39[0]", staticValue: "", description: "Table SectionA Line 16" },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_SectionA[0].Line20[0].f1_52[0]", staticValue: "", description: "Table SectionA Line 20" },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_SectionA[0].Line20[0].f1_53[0]", staticValue: "", description: "Table SectionA Line 20" },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_SectionA[0].Line20[0].f1_54[0]", staticValue: "", description: "Table SectionA Line 20" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line21[0].f2_01[0]", staticValue: "", description: "Table SectionB Line 21" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line21[0].f2_02[0]", staticValue: "", description: "Table SectionB Line 21" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line21[0].f2_03[0]", staticValue: "", description: "Table SectionB Line 21" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line21[0].f2_04[0]", staticValue: "", description: "Table SectionB Line 21" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line22[0].f2_05[0]", staticValue: "", description: "Table SectionB Line 22" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line22[0].f2_06[0]", staticValue: "", description: "Table SectionB Line 22" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line22[0].f2_07[0]", staticValue: "", description: "Table SectionB Line 22" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line22[0].f2_08[0]", staticValue: "", description: "Table SectionB Line 22" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line23[0].f2_09[0]", staticValue: "", description: "Table SectionB Line 23" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line23[0].f2_10[0]", staticValue: "", description: "Table SectionB Line 23" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line23[0].f2_11[0]", staticValue: "", description: "Table SectionB Line 23" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line23[0].f2_12[0]", staticValue: "", description: "Table SectionB Line 23" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line24[0].f2_13[0]", staticValue: "", description: "Table SectionB Line 24" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line24[0].f2_14[0]", staticValue: "", description: "Table SectionB Line 24" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line24[0].f2_15[0]", staticValue: "", description: "Table SectionB Line 24" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line24[0].f2_16[0]", staticValue: "", description: "Table SectionB Line 24" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line25[0].f2_17[0]", staticValue: "", description: "Table SectionB Line 25" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line25[0].f2_18[0]", staticValue: "", description: "Table SectionB Line 25" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line25[0].f2_19[0]", staticValue: "", description: "Table SectionB Line 25" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line25[0].f2_20[0]", staticValue: "", description: "Table SectionB Line 25" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line26[0].f2_21[0]", staticValue: "", description: "Table SectionB Line 26" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line26[0].f2_22[0]", staticValue: "", description: "Table SectionB Line 26" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line26[0].f2_23[0]", staticValue: "", description: "Table SectionB Line 26" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line26[0].f2_24[0]", staticValue: "", description: "Table SectionB Line 26" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line27[0].f2_25[0]", staticValue: "", description: "Table SectionB Line 27" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line27[0].f2_26[0]", staticValue: "", description: "Table SectionB Line 27" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line27[0].f2_27[0]", staticValue: "", description: "Table SectionB Line 27" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line27[0].f2_28[0]", staticValue: "", description: "Table SectionB Line 27" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line28[0].f2_29[0]", staticValue: "", description: "Table SectionB Line 28" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line28[0].f2_30[0]", staticValue: "", description: "Table SectionB Line 28" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line28[0].f2_31[0]", staticValue: "", description: "Table SectionB Line 28" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line28[0].f2_32[0]", staticValue: "", description: "Table SectionB Line 28" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line29[0].f2_33[0]", staticValue: "", description: "Table SectionB Line 29" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line29[0].f2_34[0]", staticValue: "", description: "Table SectionB Line 29" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line29[0].f2_35[0]", staticValue: "", description: "Table SectionB Line 29" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line29[0].f2_36[0]", staticValue: "", description: "Table SectionB Line 29" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line30[0].f2_37[0]", staticValue: "", description: "Table SectionB Line 30" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line30[0].f2_38[0]", staticValue: "", description: "Table SectionB Line 30" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line30[0].f2_39[0]", staticValue: "", description: "Table SectionB Line 30" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line30[0].f2_40[0]", staticValue: "", description: "Table SectionB Line 30" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line31[0].f2_41[0]", staticValue: "", description: "Table SectionB Line 31" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line31[0].f2_42[0]", staticValue: "", description: "Table SectionB Line 31" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line31[0].f2_43[0]", staticValue: "", description: "Table SectionB Line 31" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line31[0].f2_44[0]", staticValue: "", description: "Table SectionB Line 31" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionC[0].Line32[0].f2_45[0]", staticValue: "", description: "Table SectionC Line 32" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionC[0].Line32[0].f2_46[0]", staticValue: "", description: "Table SectionC Line 32" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionC[0].Line32[0].f2_47[0]", staticValue: "", description: "Table SectionC Line 32" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionC[0].Line32[0].f2_48[0]", staticValue: "", description: "Table SectionC Line 32" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionC[0].Line33[0].f2_49[0]", staticValue: "", description: "Table SectionC Line 33" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionC[0].Line33[0].f2_50[0]", staticValue: "", description: "Table SectionC Line 33" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionC[0].Line33[0].f2_51[0]", staticValue: "", description: "Table SectionC Line 33" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionC[0].Line33[0].f2_52[0]", staticValue: "", description: "Table SectionC Line 33" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionC[0].Line34[0].f2_53[0]", staticValue: "", description: "Table SectionC Line 34" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionC[0].Line34[0].f2_54[0]", staticValue: "", description: "Table SectionC Line 34" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionC[0].Line34[0].f2_55[0]", staticValue: "", description: "Table SectionC Line 34" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionC[0].Line34[0].f2_56[0]", staticValue: "", description: "Table SectionC Line 34" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line35[0].f2_57[0]", staticValue: "", description: "Table Part3 Line 35" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line35[0].f2_58[0]", staticValue: "", description: "Table Part3 Line 35" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line35[0].f2_59[0]", staticValue: "", description: "Table Part3 Line 35" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line35[0].f2_60[0]", staticValue: "", description: "Table Part3 Line 35" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line35[0].f2_61[0]", staticValue: "", description: "Table Part3 Line 35" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line36[0].f2_62[0]", staticValue: "", description: "Table Part3 Line 36" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line36[0].f2_63[0]", staticValue: "", description: "Table Part3 Line 36" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line36[0].f2_64[0]", staticValue: "", description: "Table Part3 Line 36" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line36[0].f2_65[0]", staticValue: "", description: "Table Part3 Line 36" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line36[0].f2_66[0]", staticValue: "", description: "Table Part3 Line 36" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line37[0].f2_67[0]", staticValue: "", description: "Table Part3 Line 37" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line37[0].f2_68[0]", staticValue: "", description: "Table Part3 Line 37" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line37[0].f2_69[0]", staticValue: "", description: "Table Part3 Line 37" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line37[0].f2_70[0]", staticValue: "", description: "Table Part3 Line 37" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line37[0].f2_71[0]", staticValue: "", description: "Table Part3 Line 37" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line38[0].f2_72[0]", staticValue: "", description: "Table Part3 Line 38" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line38[0].f2_73[0]", staticValue: "", description: "Table Part3 Line 38" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line38[0].f2_74[0]", staticValue: "", description: "Table Part3 Line 38" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line38[0].f2_75[0]", staticValue: "", description: "Table Part3 Line 38" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line38[0].f2_76[0]", staticValue: "", description: "Table Part3 Line 38" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line39[0].f2_77[0]", staticValue: "", description: "Table Part3 Line 39" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line39[0].f2_78[0]", staticValue: "", description: "Table Part3 Line 39" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line39[0].f2_79[0]", staticValue: "", description: "Table Part3 Line 39" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line39[0].f2_80[0]", staticValue: "", description: "Table Part3 Line 39" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line39[0].f2_81[0]", staticValue: "", description: "Table Part3 Line 39" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line40[0].f2_82[0]", staticValue: "", description: "Table Part3 Line 40" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line40[0].f2_83[0]", staticValue: "", description: "Table Part3 Line 40" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line40[0].f2_84[0]", staticValue: "", description: "Table Part3 Line 40" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line40[0].f2_85[0]", staticValue: "", description: "Table Part3 Line 40" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line40[0].f2_86[0]", staticValue: "", description: "Table Part3 Line 40" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line41[0].f2_87[0]", staticValue: "", description: "Table Part3 Line 41" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line41[0].f2_88[0]", staticValue: "", description: "Table Part3 Line 41" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line41[0].f2_90[0]", staticValue: "", description: "Table Part3 Line 41" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line41[0].f2_91[0]", staticValue: "", description: "Table Part3 Line 41" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line41[0].f2_92[0]", staticValue: "", description: "Table Part3 Line 41" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line42[0].f2_93[0]", staticValue: "", description: "Table Part3 Line 42" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line42[0].f2_94[0]", staticValue: "", description: "Table Part3 Line 42" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line42[0].f2_95[0]", staticValue: "", description: "Table Part3 Line 42" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line42[0].f2_96[0]", staticValue: "", description: "Table Part3 Line 42" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line42[0].f2_97[0]", staticValue: "", description: "Table Part3 Line 42" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line43[0].f2_98[0]", staticValue: "", description: "Table Part3 Line 43" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line43[0].f2_99[0]", staticValue: "", description: "Table Part3 Line 43" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line43[0].f2_100[0]", staticValue: "", description: "Table Part3 Line 43" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line43[0].f2_101[0]", staticValue: "", description: "Table Part3 Line 43" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line43[0].f2_102[0]", staticValue: "", description: "Table Part3 Line 43" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line44[0].f2_103[0]", staticValue: "", description: "Table Part3 Line 44" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line44[0].f2_104[0]", staticValue: "", description: "Table Part3 Line 44" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line44[0].f2_105[0]", staticValue: "", description: "Table Part3 Line 44" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line44[0].f2_106[0]", staticValue: "", description: "Table Part3 Line 44" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line44[0].f2_107[0]", staticValue: "", description: "Table Part3 Line 44" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line45[0].f2_108[0]", staticValue: "", description: "Table Part3 Line 45" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line45[0].f2_109[0]", staticValue: "", description: "Table Part3 Line 45" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line45[0].f2_110[0]", staticValue: "", description: "Table Part3 Line 45" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line45[0].f2_111[0]", staticValue: "", description: "Table Part3 Line 45" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line45[0].f2_112[0]", staticValue: "", description: "Table Part3 Line 45" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line46[0].f2_113[0]", staticValue: "", description: "Table Part3 Line 46" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line46[0].f2_114[0]", staticValue: "", description: "Table Part3 Line 46" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line46[0].f2_115[0]", staticValue: "", description: "Table Part3 Line 46" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line46[0].f2_116[0]", staticValue: "", description: "Table Part3 Line 46" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line46[0].f2_117[0]", staticValue: "", description: "Table Part3 Line 46" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line47[0].f2_118[0]", staticValue: "", description: "Table Part3 Line 47" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line47[0].f2_119[0]", staticValue: "", description: "Table Part3 Line 47" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line47[0].f2_120[0]", staticValue: "", description: "Table Part3 Line 47" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line47[0].f2_121[0]", staticValue: "", description: "Table Part3 Line 47" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Part3[0].Line47[0].f2_122[0]", staticValue: "", description: "Table Part3 Line 47" },
  ],
};
