import type { FormPdfMapping, FillContext } from "../types";

const PAGE1 = "topmostSubform[0].Page1[0].";

export const F8825_MAPPING: FormPdfMapping = {
  formCode: "8825",
  pdfFileName: "f8825.pdf",
  taxYear: 2024,
  fields: [
    // ── Entity header ─────────────────────────────────────────────────────────
    {
      pdfFieldName: `${PAGE1}f1_1[0]`,
      compute: (ctx: FillContext) => ctx.meta.companyName,
      format: "string",
      irsLine: "header",
      description: "Name",
    },
    {
      pdfFieldName: `${PAGE1}f1_2[0]`,
      compute: (ctx: FillContext) => ctx.meta.ein,
      format: "string",
      irsLine: "header",
      description: "Employer Identification Number (EIN)",
    },

    // ── Table_Line1 – Rental property detail rows ─────────────────────────────
    // Individual property address / type / rent columns require per-property
    // data not available from QBO aggregates; rows left as placeholders.
    {
      pdfFieldName: `${PAGE1}f1_3[0]`,
      compute: () => "",
      format: "string",
      irsLine: "1a",
      description: "Property 1 – street address (placeholder)",
    },
    {
      pdfFieldName: `${PAGE1}f1_4[0]`,
      compute: () => "",
      format: "string",
      irsLine: "1a",
      description: "Property 1 – city, state, ZIP (placeholder)",
    },
    {
      pdfFieldName: `${PAGE1}f1_5[0]`,
      compute: () => "",
      format: "string",
      irsLine: "1b",
      description: "Property 1 – type of property (placeholder)",
    },

    // ── Line 2 – Gross rents received ─────────────────────────────────────────
    {
      pdfFieldName: `${PAGE1}f1_7[0]`,
      factName: "rent_income_total",
      format: "currency",
      irsLine: "2",
      description: "Gross rents – property 1 total",
    },

    // ── Lines 3–14 – Rental expenses ─────────────────────────────────────────
    // Per-property expense breakdown requires data not available from QBO
    // rental category aggregates; left as placeholders.
    {
      pdfFieldName: `${PAGE1}f1_11[0]`,
      compute: () => "0",
      format: "currency",
      irsLine: "3",
      description: "Advertising (placeholder)",
    },
    {
      pdfFieldName: `${PAGE1}f1_15[0]`,
      compute: () => "0",
      format: "currency",
      irsLine: "4",
      description: "Auto and travel (placeholder)",
    },
    {
      pdfFieldName: `${PAGE1}f1_19[0]`,
      compute: () => "0",
      format: "currency",
      irsLine: "5",
      description: "Cleaning and maintenance (placeholder)",
    },
    {
      pdfFieldName: `${PAGE1}f1_23[0]`,
      compute: () => "0",
      format: "currency",
      irsLine: "6",
      description: "Commissions (placeholder)",
    },
    {
      pdfFieldName: `${PAGE1}f1_27[0]`,
      compute: () => "0",
      format: "currency",
      irsLine: "7",
      description: "Insurance (placeholder)",
    },
    {
      pdfFieldName: `${PAGE1}f1_31[0]`,
      compute: () => "0",
      format: "currency",
      irsLine: "8",
      description: "Legal and other professional fees (placeholder)",
    },
    {
      pdfFieldName: `${PAGE1}f1_35[0]`,
      compute: () => "0",
      format: "currency",
      irsLine: "9",
      description: "Interest expense (placeholder)",
    },
    {
      pdfFieldName: `${PAGE1}f1_39[0]`,
      compute: () => "0",
      format: "currency",
      irsLine: "10",
      description: "Repairs and maintenance (placeholder)",
    },
    {
      pdfFieldName: `${PAGE1}f1_43[0]`,
      compute: () => "0",
      format: "currency",
      irsLine: "11",
      description: "Taxes (placeholder)",
    },
    {
      pdfFieldName: `${PAGE1}f1_47[0]`,
      compute: () => "0",
      format: "currency",
      irsLine: "12",
      description: "Utilities (placeholder)",
    },
    {
      pdfFieldName: `${PAGE1}f1_51[0]`,
      compute: () => "0",
      format: "currency",
      irsLine: "13",
      description: "Wages and salaries (placeholder)",
    },
    {
      pdfFieldName: `${PAGE1}f1_55[0]`,
      compute: () => "0",
      format: "currency",
      irsLine: "14",
      description: "Depreciation (placeholder)",
    },
    {
      pdfFieldName: `${PAGE1}f1_59[0]`,
      compute: () => "0",
      format: "currency",
      irsLine: "15",
      description: "Other expenses (placeholder)",
    },

    // ── Line 16 – Total expenses ──────────────────────────────────────────────
    {
      pdfFieldName: `${PAGE1}f1_63[0]`,
      compute: () => "0",
      format: "currency",
      irsLine: "16",
      description: "Total expenses for each property (placeholder)",
    },

    // ── Lines 17–21 – Totals ──────────────────────────────────────────────────
    {
      pdfFieldName: `${PAGE1}f1_67[0]`,
      factName: "rent_income_total",
      format: "currency",
      irsLine: "17",
      description: "Total gross rents (all properties combined)",
    },
    {
      pdfFieldName: `${PAGE1}f1_68[0]`,
      compute: () => "0",
      format: "currency",
      irsLine: "18",
      description: "Total expenses (all properties combined) (placeholder)",
    },
    {
      pdfFieldName: `${PAGE1}f1_69[0]`,
      compute: () => "0",
      format: "currency",
      irsLine: "19",
      description: "Net gain (loss) from Form 4797 – rental (placeholder)",
    },
    {
      pdfFieldName: `${PAGE1}f1_70[0]`,
      compute: (ctx: FillContext) =>
        String(Number(ctx.facts["rent_income_total"] ?? 0)),
      format: "currency",
      irsLine: "20",
      description: "Net income (loss) from rental real estate",
    },
    {
      pdfFieldName: `${PAGE1}f1_71[0]`,
      compute: (ctx: FillContext) =>
        String(Number(ctx.facts["rent_income_total"] ?? 0)),
      format: "currency",
      irsLine: "21",
      description: "Net income (loss) after limitations",
    },

    // ── Auto-generated mappings (remaining fields) ──────────────────
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line7[0].f1_52[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line7[0].f1_53[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line7[0].f1_54[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line8[0].f1_56[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line8[0].f1_57[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line8[0].f1_58[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line9[0].f1_60[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line9[0].f1_61[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line9[0].f1_62[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line10[0].f1_64[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line10[0].f1_65[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line10[0].f1_66[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line12[0].f1_72[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line12[0].f1_73[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line12[0].f1_74[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line13[0].f1_75[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line13[0].f1_76[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line13[0].f1_77[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line13[0].f1_78[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line14[0].f1_99[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line14[0].f1_80[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line14[0].f1_81[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line14[0].f1_82[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line15[0].f1_83[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line15[0].f1_84[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line15[0].f1_85[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line16[0].f1_87[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line16[0].f1_88[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line16[0].f1_89[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line16[0].f1_90[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line17[0].f1_91[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line17[0].f1_92[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line17[0].f1_93[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line17[0].f1_94[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line18[0].f1_95[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line18[0].f1_96[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line18[0].f1_97[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line18[0].f1_98[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line19[0].f1_99[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line19[0].f1_100[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line19[0].f1_101[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Lines2-17[0].Line19[0].f1_102[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_103[0]", manual: true, description: "Rental property data" },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_104[0]", manual: true, description: "Rental property data" },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_105[0]", manual: true, description: "Rental property data" },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_106[0]", manual: true, description: "Rental property data" },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Line22b[0].Item1[0].f1_107[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Line22b[0].Item1[0].f1_108[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Line22b[0].Item2[0].f1_109[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Line22b[0].Item2[0].f1_110[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Line22b[0].Item3[0].f1_111[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table_Line22b[0].Item3[0].f1_112[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_113[0]", manual: true, description: "Rental property data" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line1[0].Row2[0].f2_7[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line1[0].Row2[0].Col_a[0].f2_8[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line1[0].Row2[0].Col_b[0].f2_9[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line1[0].Row2[0].Col_c[0].f2_10[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line1[0].Row2[0].Col_d[0].f2_11[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line1[0].Row2[0].Col_e[0].f2_12[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line1[0].Row3[0].f2_13[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line1[0].Row3[0].Col_a[0].f2_14[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line1[0].Row3[0].Col_b[0].f2_15[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line1[0].Row3[0].Col_c[0].f2_16[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line1[0].Row3[0].Col_d[0].f2_17[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line1[0].Row3[0].Col_e[0].f2_18[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line1[0].Row4[0].f2_19[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line1[0].Row4[0].Col_a[0].f2_20[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line1[0].Row4[0].Col_b[0].f2_21[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line1[0].Row4[0].Col_c[0].f2_22[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line1[0].Row4[0].Col_d[0].f2_23[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Line1[0].Row4[0].Col_e[0].f2_24[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].HeaderRow[0].f2_25[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].HeaderRow[0].f2_26[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].HeaderRow[0].f2_27[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].HeaderRow[0].f2_28[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line2a[0].f2_29[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line2a[0].f2_30[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line2a[0].f2_31[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line2a[0].f2_32[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line2b[0].f2_33[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line2b[0].f2_34[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line2b[0].f2_35[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line2b[0].f2_36[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line2c[0].f2_37[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line2c[0].f2_38[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line2c[0].f2_39[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line2c[0].f2_40[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line3[0].f2_41[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line3[0].f2_42[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line3[0].f2_43[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line3[0].f2_44[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line4[0].f2_45[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line4[0].f2_46[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line4[0].f2_47[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line4[0].f2_48[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line5[0].f2_49[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line5[0].f2_50[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line5[0].f2_51[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line5[0].f2_52[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line6[0].f2_53[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line6[0].f2_54[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line6[0].f2_55[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line6[0].f2_56[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line7[0].f2_57[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line7[0].f2_58[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line7[0].f2_59[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line7[0].f2_60[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line8[0].f2_61[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line8[0].f2_62[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line8[0].f2_63[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line8[0].f2_64[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line9[0].f2_65[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line9[0].f2_66[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line9[0].f2_67[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line9[0].f2_68[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line10[0].f2_69[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line10[0].f2_70[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line10[0].f2_71[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line10[0].f2_72[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line11[0].f2_73[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line11[0].f2_74[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line11[0].f2_75[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line11[0].f2_76[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line12[0].f2_77[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line12[0].f2_78[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line12[0].f2_79[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line12[0].f2_80[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line13[0].f2_81[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line13[0].f2_82[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line13[0].f2_83[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line13[0].f2_84[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line14[0].f2_85[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line14[0].f2_86[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line14[0].f2_87[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line14[0].f2_88[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line15[0].f2_89[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line15[0].f2_90[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line15[0].f2_91[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line15[0].f2_92[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line16[0].f2_93[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line16[0].f2_94[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line16[0].f2_95[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line16[0].f2_96[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line17[0].f2_97[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line17[0].f2_98[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line17[0].f2_99[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line17[0].f2_100[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line18[0].f2_101[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line18[0].f2_102[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line18[0].f2_103[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line18[0].f2_104[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line19[0].f2_105[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line19[0].f2_106[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line19[0].f2_107[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_Lines2-17[0].Line19[0].f2_108[0]", staticValue: "", description: "Table  Line " },
  ],
};
