import type { FormPdfMapping, FillContext } from "../types";
import { sbCheck, officer, currency } from "../types";

const PAGE1 = "topmostSubform[0].Page1[0].";

export const F8990_MAPPING: FormPdfMapping = {
  formCode: "8990",
  pdfFileName: "f8990.pdf",
  taxYear: 2024,
  fields: [
    // ── Entity header ─────────────────────────────────────────────────────────
    {
      pdfFieldName: `${PAGE1}f1_1[0]`,
      compute: (ctx: FillContext) => ctx.meta.companyName,
      format: "string",
      irsLine: "header",
      description: "Name",
    },
    {
      pdfFieldName: `${PAGE1}f1_2[0]`,
      compute: (ctx: FillContext) => ctx.meta.ein,
      format: "string",
      irsLine: "header",
      description: "Employer Identification Number (EIN)",
    },

    // ── Part I – Business Interest Expense ────────────────────────────────────
    {
      pdfFieldName: `${PAGE1}f1_3[0]`,
      factName: "interest_expense_total",
      format: "currency",
      irsLine: "1",
      description: "Current year business interest expense",
    },

    // Lines 2–5 require disallowed carryforward, floor plan, and partnership
    // pass-through data not available from QBO; left as placeholders.
    {
      pdfFieldName: `${PAGE1}f1_4[0]`,
      compute: () => "0",
      format: "currency",
      irsLine: "2",
      description: "Disallowed business interest expense carryforward (placeholder)",
    },
    {
      pdfFieldName: `${PAGE1}f1_5[0]`,
      compute: () => "0",
      format: "currency",
      irsLine: "3",
      description: "Floor plan financing interest expense (placeholder)",
    },
    {
      pdfFieldName: `${PAGE1}f1_6[0]`,
      compute: () => "0",
      format: "currency",
      irsLine: "4",
      description: "Business interest expense from partnerships (placeholder)",
    },
    {
      pdfFieldName: `${PAGE1}f1_7[0]`,
      factName: "interest_expense_total",
      format: "currency",
      irsLine: "5",
      description: "Total business interest expense (Lines 1–4)",
    },

    // ── Part II – ATI (Adjusted Taxable Income) ───────────────────────────────
    {
      pdfFieldName: `${PAGE1}f1_8[0]`,
      factName: "adjusted_taxable_income_163j",
      format: "currency",
      irsLine: "6",
      description: "Adjusted taxable income (ATI) for §163(j)",
    },
    {
      pdfFieldName: `${PAGE1}f1_9[0]`,
      compute: () => "0",
      format: "currency",
      irsLine: "7",
      description: "Business interest income (placeholder)",
    },
    {
      pdfFieldName: `${PAGE1}f1_10[0]`,
      compute: () => "0",
      format: "currency",
      irsLine: "8",
      description: "Floor plan financing interest expense included on Line 3 (placeholder)",
    },

    // ── Part III – Allowable Business Interest Expense ────────────────────────
    {
      pdfFieldName: `${PAGE1}f1_30[0]`,
      factName: "interest_expense_limitation_30pct",
      format: "currency",
      irsLine: "30",
      description: "30% ATI limitation on business interest expense",
    },

    // ── Auto-generated mappings (remaining fields) ──────────────────
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_1[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q1"), format: "boolean", description: "Checkbox: p1_q1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_2[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q2"), format: "boolean", description: "Checkbox: p1_q2" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_3[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q3"), format: "boolean", description: "Checkbox: p1_q3" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_7[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_8[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_9[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_10[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_11[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_12[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_13[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_14[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_15[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_16[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_17[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_18[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_21[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_22[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleA[0].Row3[0].f3_23[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleA[0].Row3[0].f3_24[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleA[0].Row3[0].f3_25[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleA[0].Row3[0].f3_26[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleA[0].Row3[0].f3_27[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleA[0].Row4[0].f3_28[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleA[0].Row4[0].f3_29[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleA[0].Row4[0].f3_30[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleA[0].Row4[0].f3_31[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleA[0].Row4[0].f3_32[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleA[0].Row4[0].f3_33[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleA[0].Row4[0].f3_34[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleA[0].Row4[0].f3_35[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleA[0].Row4[0].f3_36[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleA[0].Row5[0].f3_43[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleA[0].Row5[0].f3_44[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleA[0].Row5[0].f3_45[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleA[0].Row6[0].f3_46[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleA[0].Row6[0].f3_47[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleA[0].Row6[0].f3_48[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleA[0].Row6[0].f3_49[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleA[0].Row6[0].f3_50[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleA[0].Row6[0].f3_51[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleA[0].Row6[0].f3_52[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleA[0].Row6[0].f3_53[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleA[0].Row6[0].f3_54[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_55[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_56[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_57[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleB[0].Row1[0].f3_58[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleB[0].Row1[0].f3_59[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleB[0].Row1[0].f3_60[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleB[0].Row1[0].f3_61[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleB[0].Row2[0].f3_62[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleB[0].Row2[0].f3_63[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleB[0].Row2[0].f3_64[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleB[0].Row2[0].f3_65[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleB[0].Row3[0].f3_66[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleB[0].Row3[0].f3_67[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleB[0].Row3[0].f3_68[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleB[0].Row3[0].f3_69[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleB[0].Row4[0].f3_70[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleB[0].Row4[0].f3_71[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleB[0].Row4[0].f3_72[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleB[0].Row4[0].f3_73[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleB[0].Row5[0].f3_74[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleB[0].Row5[0].f3_75[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleB[0].Row5[0].f3_76[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_ScheduleB[0].Row5[0].f3_77[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_78[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_79[0]", staticValue: "", description: "Unmapped — page 3" },
  ],
};
