import type { FormPdfMapping, FillContext } from "../types";
import { sbCheck, officer, currency } from "../types";

const P = "topmostSubform[0].Page1[0].";

export const F990SA_MAPPING: FormPdfMapping = {
  formCode: "Sch A",
  pdfFileName: "f990sa.pdf",
  taxYear: 2025,
  fields: [
    // -------------------------------------------------------------------------
    // Header fields
    // -------------------------------------------------------------------------
    {
      pdfFieldName: `${P}f1_1[0]`,
      compute: (ctx: FillContext) => ctx.meta.companyName,
      format: "string",
      irsLine: "Header",
      description: "Name of organization",
    },
    {
      pdfFieldName: `${P}f1_2[0]`,
      compute: (ctx: FillContext) => ctx.meta.ein,
      format: "string",
      irsLine: "Header",
      description: "Employer Identification Number (EIN)",
    },

    // ── Auto-generated mappings (remaining fields) ──────────────────
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_1[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q1"), format: "boolean", description: "Checkbox: p1_q1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_1[2]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q1"), format: "boolean", description: "Checkbox: p1_q1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_1[3]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q1"), format: "boolean", description: "Checkbox: p1_q1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_1[4]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q1"), format: "boolean", description: "Checkbox: p1_q1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_1[5]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q1"), format: "boolean", description: "Checkbox: p1_q1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_1[6]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q1"), format: "boolean", description: "Checkbox: p1_q1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_1[7]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q1"), format: "boolean", description: "Checkbox: p1_q1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_1[8]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q1"), format: "boolean", description: "Checkbox: p1_q1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_1[9]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q1"), format: "boolean", description: "Checkbox: p1_q1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_1[10]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q1"), format: "boolean", description: "Checkbox: p1_q1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_1[11]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q1"), format: "boolean", description: "Checkbox: p1_q1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_2[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q2"), format: "boolean", description: "Checkbox: p1_q2" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_2[2]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q2"), format: "boolean", description: "Checkbox: p1_q2" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_2[3]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q2"), format: "boolean", description: "Checkbox: p1_q2" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_2[4]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q2"), format: "boolean", description: "Checkbox: p1_q2" },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table[0].BodyRow1[0].c1_3[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q3"), format: "boolean", description: "Checkbox: p1_q3" },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table[0].BodyRow2[0].c1_4[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q4"), format: "boolean", description: "Checkbox: p1_q4" },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table[0].BodyRow3[0].c1_5[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q5"), format: "boolean", description: "Checkbox: p1_q5" },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table[0].BodyRow4[0].c1_6[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q6"), format: "boolean", description: "Checkbox: p1_q6" },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table[0].BodyRow4[0].c1_6[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q6"), format: "boolean", description: "Checkbox: p1_q6" },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table[0].BodyRow5[0].c1_7[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q7"), format: "boolean", description: "Checkbox: p1_q7" },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table[0].BodyRow5[0].c1_7[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q7"), format: "boolean", description: "Checkbox: p1_q7" },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table[0].BodyRow6[0].R1[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table[0].BodyRow6[0].R2[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table[0].BodyRow6[0].R3[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page1[0].Table[0].BodyRow6[0].R4[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionA[0].Line2[0].f2_7[0]", staticValue: "", description: "Table SectionA Line 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionA[0].Line2[0].f2_8[0]", staticValue: "", description: "Table SectionA Line 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionA[0].Line2[0].f2_9[0]", staticValue: "", description: "Table SectionA Line 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionA[0].Line2[0].f2_10[0]", staticValue: "", description: "Table SectionA Line 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionA[0].Line2[0].f2_11[0]", staticValue: "", description: "Table SectionA Line 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionA[0].Line2[0].f2_12[0]", staticValue: "", description: "Table SectionA Line 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionA[0].Line3[0].f2_13[0]", staticValue: "", description: "Table SectionA Line 3" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionA[0].Line3[0].f2_14[0]", staticValue: "", description: "Table SectionA Line 3" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionA[0].Line3[0].f2_15[0]", staticValue: "", description: "Table SectionA Line 3" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionA[0].Line3[0].f2_16[0]", staticValue: "", description: "Table SectionA Line 3" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionA[0].Line3[0].f2_17[0]", staticValue: "", description: "Table SectionA Line 3" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionA[0].Line3[0].f2_18[0]", staticValue: "", description: "Table SectionA Line 3" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionA[0].Line4[0].f2_19[0]", staticValue: "", description: "Table SectionA Line 4" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionA[0].Line4[0].f2_20[0]", staticValue: "", description: "Table SectionA Line 4" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionA[0].Line4[0].f2_21[0]", staticValue: "", description: "Table SectionA Line 4" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionA[0].Line4[0].f2_22[0]", staticValue: "", description: "Table SectionA Line 4" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionA[0].Line4[0].f2_23[0]", staticValue: "", description: "Table SectionA Line 4" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionA[0].Line4[0].f2_24[0]", staticValue: "", description: "Table SectionA Line 4" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionA[0].Line5[0].R1[0]", staticValue: "", description: "Table SectionA Line 5" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionA[0].Line5[0].R2[0]", staticValue: "", description: "Table SectionA Line 5" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionA[0].Line5[0].R3[0]", staticValue: "", description: "Table SectionA Line 5" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionA[0].Line5[0].R4[0]", staticValue: "", description: "Table SectionA Line 5" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionA[0].Line5[0].R5[0]", staticValue: "", description: "Table SectionA Line 5" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionA[0].Line5[0].f2_25[0]", staticValue: "", description: "Table SectionA Line 5" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionA[0].Line6[0].R6[0]", staticValue: "", description: "Table SectionA Line 6" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionA[0].Line6[0].R7[0]", staticValue: "", description: "Table SectionA Line 6" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionA[0].Line6[0].R8[0]", staticValue: "", description: "Table SectionA Line 6" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionA[0].Line6[0].R9[0]", staticValue: "", description: "Table SectionA Line 6" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionA[0].Line6[0].R10[0]", staticValue: "", description: "Table SectionA Line 6" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionA[0].Line6[0].f2_26[0]", staticValue: "", description: "Table SectionA Line 6" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line7[0].f2_27[0]", staticValue: "", description: "Table SectionB Line 7" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line7[0].f2_28[0]", staticValue: "", description: "Table SectionB Line 7" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line7[0].f2_29[0]", staticValue: "", description: "Table SectionB Line 7" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line7[0].f2_30[0]", staticValue: "", description: "Table SectionB Line 7" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line7[0].f2_31[0]", staticValue: "", description: "Table SectionB Line 7" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line7[0].f2_32[0]", staticValue: "", description: "Table SectionB Line 7" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line8[0].f2_33[0]", staticValue: "", description: "Table SectionB Line 8" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line8[0].f2_34[0]", staticValue: "", description: "Table SectionB Line 8" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line8[0].f2_35[0]", staticValue: "", description: "Table SectionB Line 8" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line8[0].f2_36[0]", staticValue: "", description: "Table SectionB Line 8" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line8[0].f2_37[0]", staticValue: "", description: "Table SectionB Line 8" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line8[0].f2_38[0]", staticValue: "", description: "Table SectionB Line 8" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line9[0].f2_39[0]", staticValue: "", description: "Table SectionB Line 9" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line9[0].f2_40[0]", staticValue: "", description: "Table SectionB Line 9" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line9[0].f2_41[0]", staticValue: "", description: "Table SectionB Line 9" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line9[0].f2_42[0]", staticValue: "", description: "Table SectionB Line 9" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line9[0].f2_43[0]", staticValue: "", description: "Table SectionB Line 9" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line9[0].f2_44[0]", staticValue: "", description: "Table SectionB Line 9" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line10[0].f2_45[0]", staticValue: "", description: "Table SectionB Line 10" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line10[0].f2_46[0]", staticValue: "", description: "Table SectionB Line 10" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line10[0].f2_47[0]", staticValue: "", description: "Table SectionB Line 10" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line10[0].f2_48[0]", staticValue: "", description: "Table SectionB Line 10" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line10[0].f2_49[0]", staticValue: "", description: "Table SectionB Line 10" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line10[0].f2_50[0]", staticValue: "", description: "Table SectionB Line 10" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line11[0].R11[0]", staticValue: "", description: "Table SectionB Line 11" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line11[0].R12[0]", staticValue: "", description: "Table SectionB Line 11" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line11[0].R13[0]", staticValue: "", description: "Table SectionB Line 11" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line11[0].R14[0]", staticValue: "", description: "Table SectionB Line 11" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line11[0].R15[0]", staticValue: "", description: "Table SectionB Line 11" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table_SectionB[0].Line11[0].f2_51[0]", staticValue: "", description: "Table SectionB Line 11" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_52[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_1[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q1"), format: "boolean", description: "Checkbox: p2_q1" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_53[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_54[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_2[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q2"), format: "boolean", description: "Checkbox: p2_q2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_3[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q3"), format: "boolean", description: "Checkbox: p2_q3" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_4[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q4"), format: "boolean", description: "Checkbox: p2_q4" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_5[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q5"), format: "boolean", description: "Checkbox: p2_q5" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_6[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q6"), format: "boolean", description: "Checkbox: p2_q6" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecAPart3[0].Line4[0].f3_23[0]", staticValue: "", description: "Table SecAPart3 Line 4" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecAPart3[0].Line4[0].f3_24[0]", staticValue: "", description: "Table SecAPart3 Line 4" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecAPart3[0].Line5[0].f3_25[0]", staticValue: "", description: "Table SecAPart3 Line 5" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecAPart3[0].Line5[0].f3_26[0]", staticValue: "", description: "Table SecAPart3 Line 5" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecAPart3[0].Line5[0].f3_27[0]", staticValue: "", description: "Table SecAPart3 Line 5" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecAPart3[0].Line5[0].f3_28[0]", staticValue: "", description: "Table SecAPart3 Line 5" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecAPart3[0].Line5[0].f3_29[0]", staticValue: "", description: "Table SecAPart3 Line 5" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecAPart3[0].Line5[0].f3_30[0]", staticValue: "", description: "Table SecAPart3 Line 5" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecAPart3[0].Line6[0].f3_31[0]", staticValue: "", description: "Table SecAPart3 Line 6" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecAPart3[0].Line6[0].f3_32[0]", staticValue: "", description: "Table SecAPart3 Line 6" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecAPart3[0].Line6[0].f3_33[0]", staticValue: "", description: "Table SecAPart3 Line 6" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecAPart3[0].Line6[0].f3_34[0]", staticValue: "", description: "Table SecAPart3 Line 6" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecAPart3[0].Line6[0].f3_35[0]", staticValue: "", description: "Table SecAPart3 Line 6" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecAPart3[0].Line6[0].f3_36[0]", staticValue: "", description: "Table SecAPart3 Line 6" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecAPart3[0].Line7b[0].f3_43[0]", staticValue: "", description: "Table SecAPart3 Line 7b" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecAPart3[0].Line7b[0].f3_44[0]", staticValue: "", description: "Table SecAPart3 Line 7b" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecAPart3[0].Line7b[0].f3_45[0]", staticValue: "", description: "Table SecAPart3 Line 7b" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecAPart3[0].Line7b[0].f3_46[0]", staticValue: "", description: "Table SecAPart3 Line 7b" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecAPart3[0].Line7b[0].f3_47[0]", staticValue: "", description: "Table SecAPart3 Line 7b" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecAPart3[0].Line7b[0].f3_48[0]", staticValue: "", description: "Table SecAPart3 Line 7b" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecAPart3[0].Line7c[0].f3_49[0]", staticValue: "", description: "Table SecAPart3 Line 7c" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecAPart3[0].Line7c[0].f3_50[0]", staticValue: "", description: "Table SecAPart3 Line 7c" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecAPart3[0].Line7c[0].f3_51[0]", staticValue: "", description: "Table SecAPart3 Line 7c" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecAPart3[0].Line7c[0].f3_52[0]", staticValue: "", description: "Table SecAPart3 Line 7c" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecAPart3[0].Line7c[0].f3_53[0]", staticValue: "", description: "Table SecAPart3 Line 7c" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecAPart3[0].Line7c[0].f3_54[0]", staticValue: "", description: "Table SecAPart3 Line 7c" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecAPart3[0].Line8[0].R6[0]", staticValue: "", description: "Table SecAPart3 Line 8" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecAPart3[0].Line8[0].R7[0]", staticValue: "", description: "Table SecAPart3 Line 8" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecAPart3[0].Line8[0].R8[0]", staticValue: "", description: "Table SecAPart3 Line 8" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecAPart3[0].Line8[0].R9[0]", staticValue: "", description: "Table SecAPart3 Line 8" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecAPart3[0].Line8[0].R10[0]", staticValue: "", description: "Table SecAPart3 Line 8" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecAPart3[0].Line8[0].f3_55[0]", staticValue: "", description: "Table SecAPart3 Line 8" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line9[0].f3_56[0]", staticValue: "", description: "Table SecBPart3 Line 9" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line9[0].f3_57[0]", staticValue: "", description: "Table SecBPart3 Line 9" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line9[0].f3_58[0]", staticValue: "", description: "Table SecBPart3 Line 9" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line9[0].f3_59[0]", staticValue: "", description: "Table SecBPart3 Line 9" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line9[0].f3_60[0]", staticValue: "", description: "Table SecBPart3 Line 9" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line9[0].f3_61[0]", staticValue: "", description: "Table SecBPart3 Line 9" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line10a[0].f3_62[0]", staticValue: "", description: "Table SecBPart3 Line 10a" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line10a[0].f3_63[0]", staticValue: "", description: "Table SecBPart3 Line 10a" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line10a[0].f3_64[0]", staticValue: "", description: "Table SecBPart3 Line 10a" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line10a[0].f3_65[0]", staticValue: "", description: "Table SecBPart3 Line 10a" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line10a[0].f3_66[0]", staticValue: "", description: "Table SecBPart3 Line 10a" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line10a[0].f3_67[0]", staticValue: "", description: "Table SecBPart3 Line 10a" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line10b[0].f3_68[0]", staticValue: "", description: "Table SecBPart3 Line 10b" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line10b[0].f3_69[0]", staticValue: "", description: "Table SecBPart3 Line 10b" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line10b[0].f3_70[0]", staticValue: "", description: "Table SecBPart3 Line 10b" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line10b[0].f3_71[0]", staticValue: "", description: "Table SecBPart3 Line 10b" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line10b[0].f3_72[0]", staticValue: "", description: "Table SecBPart3 Line 10b" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line10b[0].f3_73[0]", staticValue: "", description: "Table SecBPart3 Line 10b" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line10c[0].f3_74[0]", staticValue: "", description: "Table SecBPart3 Line 10c" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line10c[0].f3_75[0]", staticValue: "", description: "Table SecBPart3 Line 10c" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line10c[0].f3_76[0]", staticValue: "", description: "Table SecBPart3 Line 10c" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line10c[0].f3_77[0]", staticValue: "", description: "Table SecBPart3 Line 10c" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line10c[0].f3_78[0]", staticValue: "", description: "Table SecBPart3 Line 10c" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line10c[0].f3_79[0]", staticValue: "", description: "Table SecBPart3 Line 10c" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line11[0].f3_80[0]", staticValue: "", description: "Table SecBPart3 Line 11" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line11[0].f3_81[0]", staticValue: "", description: "Table SecBPart3 Line 11" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line11[0].f3_82[0]", staticValue: "", description: "Table SecBPart3 Line 11" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line11[0].f3_83[0]", staticValue: "", description: "Table SecBPart3 Line 11" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line11[0].f3_84[0]", staticValue: "", description: "Table SecBPart3 Line 11" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line11[0].f3_85[0]", staticValue: "", description: "Table SecBPart3 Line 11" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line12[0].f3_86[0]", staticValue: "", description: "Table SecBPart3 Line 12" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line12[0].f3_87[0]", staticValue: "", description: "Table SecBPart3 Line 12" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line12[0].f3_88[0]", staticValue: "", description: "Table SecBPart3 Line 12" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line12[0].f3_89[0]", staticValue: "", description: "Table SecBPart3 Line 12" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line12[0].f3_90[0]", staticValue: "", description: "Table SecBPart3 Line 12" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line12[0].f3_91[0]", staticValue: "", description: "Table SecBPart3 Line 12" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line13[0].f3_92[0]", staticValue: "", description: "Table SecBPart3 Line 13" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line13[0].f3_93[0]", staticValue: "", description: "Table SecBPart3 Line 13" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line13[0].f3_94[0]", staticValue: "", description: "Table SecBPart3 Line 13" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line13[0].f3_95[0]", staticValue: "", description: "Table SecBPart3 Line 13" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line13[0].f3_96[0]", staticValue: "", description: "Table SecBPart3 Line 13" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table_SecBPart3[0].Line13[0].f3_97[0]", staticValue: "", description: "Table SecBPart3 Line 13" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_1[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q1"), format: "boolean", description: "Checkbox: p3_q1" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_98[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_99[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_100[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].f3_101[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_2[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q2"), format: "boolean", description: "Checkbox: p3_q2" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_3[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q3"), format: "boolean", description: "Checkbox: p3_q3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_4[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q4"), format: "boolean", description: "Checkbox: p3_q4" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_1[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q1"), format: "boolean", description: "Checkbox: p4_q1" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_1[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q1"), format: "boolean", description: "Checkbox: p4_q1" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_2[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q2"), format: "boolean", description: "Checkbox: p4_q2" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_2[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q2"), format: "boolean", description: "Checkbox: p4_q2" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_3[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q3"), format: "boolean", description: "Checkbox: p4_q3" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_3[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q3"), format: "boolean", description: "Checkbox: p4_q3" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_4[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q4"), format: "boolean", description: "Checkbox: p4_q4" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_4[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q4"), format: "boolean", description: "Checkbox: p4_q4" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_5[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q5"), format: "boolean", description: "Checkbox: p4_q5" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_5[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q5"), format: "boolean", description: "Checkbox: p4_q5" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_6[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q6"), format: "boolean", description: "Checkbox: p4_q6" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_6[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q6"), format: "boolean", description: "Checkbox: p4_q6" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_7[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q7"), format: "boolean", description: "Checkbox: p4_q7" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_7[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q7"), format: "boolean", description: "Checkbox: p4_q7" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_8[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q8"), format: "boolean", description: "Checkbox: p4_q8" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_8[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q8"), format: "boolean", description: "Checkbox: p4_q8" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_9[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q9"), format: "boolean", description: "Checkbox: p4_q9" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_9[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q9"), format: "boolean", description: "Checkbox: p4_q9" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_10[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q10"), format: "boolean", description: "Checkbox: p4_q10" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_10[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q10"), format: "boolean", description: "Checkbox: p4_q10" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_11[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q11"), format: "boolean", description: "Checkbox: p4_q11" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_11[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q11"), format: "boolean", description: "Checkbox: p4_q11" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_12[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q12"), format: "boolean", description: "Checkbox: p4_q12" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_12[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q12"), format: "boolean", description: "Checkbox: p4_q12" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_13[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q13"), format: "boolean", description: "Checkbox: p4_q13" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_13[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q13"), format: "boolean", description: "Checkbox: p4_q13" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_14[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q14"), format: "boolean", description: "Checkbox: p4_q14" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_14[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q14"), format: "boolean", description: "Checkbox: p4_q14" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_15[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q15"), format: "boolean", description: "Checkbox: p4_q15" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_15[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q15"), format: "boolean", description: "Checkbox: p4_q15" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_16[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q16"), format: "boolean", description: "Checkbox: p4_q16" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_16[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q16"), format: "boolean", description: "Checkbox: p4_q16" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_17[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q17"), format: "boolean", description: "Checkbox: p4_q17" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_17[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q17"), format: "boolean", description: "Checkbox: p4_q17" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_18[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q18"), format: "boolean", description: "Checkbox: p4_q18" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_18[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q18"), format: "boolean", description: "Checkbox: p4_q18" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_19[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q19"), format: "boolean", description: "Checkbox: p4_q19" },
    { pdfFieldName: "topmostSubform[0].Page4[0].c4_19[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p4_q19"), format: "boolean", description: "Checkbox: p4_q19" },
    { pdfFieldName: "topmostSubform[0].Page5[0].TagCorrectingSubform[0].c5_1[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q1"), format: "boolean", description: "Checkbox: p5_q1" },
    { pdfFieldName: "topmostSubform[0].Page5[0].TagCorrectingSubform[0].c5_1[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q1"), format: "boolean", description: "Checkbox: p5_q1" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_2[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q2"), format: "boolean", description: "Checkbox: p5_q2" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_2[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q2"), format: "boolean", description: "Checkbox: p5_q2" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_3[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q3"), format: "boolean", description: "Checkbox: p5_q3" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_3[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q3"), format: "boolean", description: "Checkbox: p5_q3" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_4[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q4"), format: "boolean", description: "Checkbox: p5_q4" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_4[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q4"), format: "boolean", description: "Checkbox: p5_q4" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_5[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q5"), format: "boolean", description: "Checkbox: p5_q5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_5[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q5"), format: "boolean", description: "Checkbox: p5_q5" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_6[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q6"), format: "boolean", description: "Checkbox: p5_q6" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_6[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q6"), format: "boolean", description: "Checkbox: p5_q6" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_7[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q7"), format: "boolean", description: "Checkbox: p5_q7" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_7[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q7"), format: "boolean", description: "Checkbox: p5_q7" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_8[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q8"), format: "boolean", description: "Checkbox: p5_q8" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_8[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q8"), format: "boolean", description: "Checkbox: p5_q8" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_9[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q9"), format: "boolean", description: "Checkbox: p5_q9" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_9[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q9"), format: "boolean", description: "Checkbox: p5_q9" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_10[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q10"), format: "boolean", description: "Checkbox: p5_q10" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_10[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q10"), format: "boolean", description: "Checkbox: p5_q10" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_10[2]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q10"), format: "boolean", description: "Checkbox: p5_q10" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_11[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q11"), format: "boolean", description: "Checkbox: p5_q11" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_11[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q11"), format: "boolean", description: "Checkbox: p5_q11" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_12[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q12"), format: "boolean", description: "Checkbox: p5_q12" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_12[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q12"), format: "boolean", description: "Checkbox: p5_q12" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_13[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q13"), format: "boolean", description: "Checkbox: p5_q13" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_13[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q13"), format: "boolean", description: "Checkbox: p5_q13" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_14[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q14"), format: "boolean", description: "Checkbox: p5_q14" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_14[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q14"), format: "boolean", description: "Checkbox: p5_q14" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_15[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q15"), format: "boolean", description: "Checkbox: p5_q15" },
    { pdfFieldName: "topmostSubform[0].Page5[0].c5_15[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p5_q15"), format: "boolean", description: "Checkbox: p5_q15" },
    { pdfFieldName: "topmostSubform[0].Page6[0].c6_1[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p6_q1"), format: "boolean", description: "Checkbox: p6_q1" },
    { pdfFieldName: "topmostSubform[0].Page6[0].c6_2[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p6_q2"), format: "boolean", description: "Checkbox: p6_q2" },
    { pdfFieldName: "topmostSubform[0].Page7[0].f7_1[0]", staticValue: "", description: "Unmapped — page 7" },
    { pdfFieldName: "topmostSubform[0].Page7[0].f7_2[0]", staticValue: "", description: "Unmapped — page 7" },
    { pdfFieldName: "topmostSubform[0].Page7[0].f7_3[0]", staticValue: "", description: "Unmapped — page 7" },
    { pdfFieldName: "topmostSubform[0].Page7[0].f7_4[0]", staticValue: "", description: "Unmapped — page 7" },
    { pdfFieldName: "topmostSubform[0].Page7[0].f7_5[0]", staticValue: "", description: "Unmapped — page 7" },
    { pdfFieldName: "topmostSubform[0].Page7[0].f7_6[0]", staticValue: "", description: "Unmapped — page 7" },
    { pdfFieldName: "topmostSubform[0].Page7[0].f7_7[0]", staticValue: "", description: "Unmapped — page 7" },
    { pdfFieldName: "topmostSubform[0].Page7[0].f7_8[0]", staticValue: "", description: "Unmapped — page 7" },
    { pdfFieldName: "topmostSubform[0].Page7[0].f7_9[0]", staticValue: "", description: "Unmapped — page 7" },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line1[0].f7_10[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line1[0].f7_11[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line1[0].f7_12[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line2[0].f7_13[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line2[0].f7_14[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line2[0].f7_15[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line3a[0].f7_16[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line3a[0].f7_17[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line3a[0].f7_18[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line3a[0].f7_19[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line3b[0].f7_20[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line3b[0].f7_21[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line3b[0].f7_22[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line3b[0].f7_23[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line1c[0].f7_24[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line1c[0].f7_25[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line1c[0].f7_26[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line1c[0].f7_27[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line1d[0].f7_28[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line1d[0].f7_29[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line1d[0].f7_30[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line1d[0].f7_31[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line1e[0].f7_32[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line1e[0].f7_33[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line1e[0].f7_34[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line1e[0].f7_35[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line1f[0].f7_36[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line1f[0].f7_37[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line1f[0].f7_38[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line1g[0].f7_39[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line1g[0].f7_40[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line1g[0].f7_41[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line1h[0].f7_42[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line1h[0].f7_43[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line1h[0].f7_44[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line1i[0].f7_45[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line1i[0].f7_46[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line1i[0].f7_47[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line1j[0].f7_48[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line1j[0].f7_49[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line1j[0].f7_50[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line4[0].Line4Text[0].f7_51[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line4a[0].f7_52[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line4a[0].f7_53[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line4a[0].f7_54[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line4b[0].f7_55[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line4b[0].f7_56[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line4b[0].f7_57[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line4c[0].f7_58[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line4c[0].f7_59[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line4c[0].f7_60[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line5[0].f7_61[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line5[0].f7_62[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line5[0].f7_63[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line6[0].f7_64[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line6[0].f7_65[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line6[0].f7_66[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line7[0].f7_67[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line7[0].f7_68[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line7[0].f7_69[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line8a[0].f7_70[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line8a[0].f7_71[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line8a[0].f7_72[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line8a[0].f7_73[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line8b[0].f7_74[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line8b[0].f7_75[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line8b[0].f7_76[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line8b[0].f7_77[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line8c[0].f7_78[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line8c[0].f7_79[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line8c[0].f7_80[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line8c[0].f7_81[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line8d[0].f7_82[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line8d[0].f7_83[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line8d[0].f7_84[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line8d[0].f7_85[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line8e[0].f7_86[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line8e[0].f7_87[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line8e[0].f7_88[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page7[0].TableSectionE[0].Line8e[0].f7_89[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page8[0].f8_1[0]", staticValue: "", description: "Unmapped — page 8" },
  ],
};
