import type { FormPdfMapping, FillContext } from "../types";
import { sbCheck, officer, currency } from "../types";

const P = "topmostSubform[0].Page1[0].";

export const F990SB_MAPPING: FormPdfMapping = {
  formCode: "Sch B",
  pdfFileName: "f990sb.pdf",
  taxYear: 2025,
  fields: [
    // -------------------------------------------------------------------------
    // Header fields
    // -------------------------------------------------------------------------
    {
      pdfFieldName: `${P}f1_1[0]`,
      compute: (ctx: FillContext) => ctx.meta.companyName,
      format: "string",
      irsLine: "Header",
      description: "Name of organization",
    },
    {
      pdfFieldName: `${P}f1_2[0]`,
      compute: (ctx: FillContext) => ctx.meta.ein,
      format: "string",
      irsLine: "Header",
      description: "Employer Identification Number (EIN)",
    },

    // ── Auto-generated mappings (remaining fields) ──────────────────
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_1[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q1"), format: "boolean", description: "Checkbox: p1_q1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_1[2]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q1"), format: "boolean", description: "Checkbox: p1_q1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_1[3]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q1"), format: "boolean", description: "Checkbox: p1_q1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_1[4]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q1"), format: "boolean", description: "Checkbox: p1_q1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_1[5]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q1"), format: "boolean", description: "Checkbox: p1_q1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_3[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q3"), format: "boolean", description: "Checkbox: p1_q3" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_3[2]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q3"), format: "boolean", description: "Checkbox: p1_q3" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table1[0].BodyRow1[0].f2_7[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table1[0].BodyRow1[0].Row1ColD[0].c2_1[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q1"), format: "boolean", description: "Checkbox: p2_q1" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table1[0].BodyRow1[0].Row1ColD[0].c2_1[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q1"), format: "boolean", description: "Checkbox: p2_q1" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table1[0].BodyRow1[0].Row1ColD[0].c2_1[2]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q1"), format: "boolean", description: "Checkbox: p2_q1" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table2[0].BodyRow2[0].f2_8[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table2[0].BodyRow2[0].Row2ColB[0].f2_9[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table2[0].BodyRow2[0].Row2ColB[0].f2_10[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table2[0].BodyRow2[0].Row2ColB[0].f2_11[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table2[0].BodyRow2[0].f2_12[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table2[0].BodyRow2[0].Row2ColD[0].c2_2[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q2"), format: "boolean", description: "Checkbox: p2_q2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table2[0].BodyRow2[0].Row2ColD[0].c2_2[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q2"), format: "boolean", description: "Checkbox: p2_q2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table2[0].BodyRow2[0].Row2ColD[0].c2_2[2]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q2"), format: "boolean", description: "Checkbox: p2_q2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table3[0].BodyRow3[0].f2_13[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table3[0].BodyRow3[0].Row3ColB[0].f2_14[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table3[0].BodyRow3[0].Row3ColB[0].f2_15[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table3[0].BodyRow3[0].Row3ColB[0].f2_16[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table3[0].BodyRow3[0].f2_17[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table3[0].BodyRow3[0].Row3ColD[0].c2_3[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q3"), format: "boolean", description: "Checkbox: p2_q3" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table3[0].BodyRow3[0].Row3ColD[0].c2_3[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q3"), format: "boolean", description: "Checkbox: p2_q3" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table3[0].BodyRow3[0].Row3ColD[0].c2_3[2]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q3"), format: "boolean", description: "Checkbox: p2_q3" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table4[0].BodyRow4[0].f2_18[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table4[0].BodyRow4[0].Row4ColB[0].f2_19[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table4[0].BodyRow4[0].Row4ColB[0].f2_20[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table4[0].BodyRow4[0].Row4ColB[0].f2_21[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table4[0].BodyRow4[0].f2_22[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table4[0].BodyRow4[0].Row4ColD[0].c2_4[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q4"), format: "boolean", description: "Checkbox: p2_q4" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table4[0].BodyRow4[0].Row4ColD[0].c2_4[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q4"), format: "boolean", description: "Checkbox: p2_q4" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table4[0].BodyRow4[0].Row4ColD[0].c2_4[2]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q4"), format: "boolean", description: "Checkbox: p2_q4" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table5[0].BodyRow5[0].f2_23[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table5[0].BodyRow5[0].Row5ColB[0].f2_24[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table5[0].BodyRow5[0].Row5ColB[0].f2_25[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table5[0].BodyRow5[0].Row5ColB[0].f2_26[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table5[0].BodyRow5[0].f2_27[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table5[0].BodyRow5[0].Row5ColD[0].c2_5[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q5"), format: "boolean", description: "Checkbox: p2_q5" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table5[0].BodyRow5[0].Row5ColD[0].c2_5[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q5"), format: "boolean", description: "Checkbox: p2_q5" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table5[0].BodyRow5[0].Row5ColD[0].c2_5[2]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q5"), format: "boolean", description: "Checkbox: p2_q5" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table6[0].BodyRow6[0].f2_28[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table6[0].BodyRow6[0].Row6ColB[0].f2_29[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table6[0].BodyRow6[0].Row6ColB[0].f2_30[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table6[0].BodyRow6[0].Row6ColB[0].f2_31[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table6[0].BodyRow6[0].f2_32[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table6[0].BodyRow6[0].Row6ColD[0].c2_6[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q6"), format: "boolean", description: "Checkbox: p2_q6" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table6[0].BodyRow6[0].Row6ColD[0].c2_6[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q6"), format: "boolean", description: "Checkbox: p2_q6" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Table6[0].BodyRow6[0].Row6ColD[0].c2_6[2]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q6"), format: "boolean", description: "Checkbox: p2_q6" },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table3[0].BodyRow3[0].Row3ColB[0].f3_23[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table3[0].BodyRow3[0].Row3ColB[0].f3_24[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table3[0].BodyRow3[0].f3_25[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table3[0].BodyRow3[0].f3_26[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table4[0].BodyRow4[0].f3_27[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table4[0].BodyRow4[0].Row4ColB[0].f3_28[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table4[0].BodyRow4[0].Row4ColB[0].f3_29[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table4[0].BodyRow4[0].Row4ColB[0].f3_30[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table4[0].BodyRow4[0].Row4ColB[0].f3_31[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table4[0].BodyRow4[0].Row4ColB[0].f3_32[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table4[0].BodyRow4[0].f3_33[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table4[0].BodyRow4[0].f3_34[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table5[0].BodyRow5[0].f3_35[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table5[0].BodyRow5[0].Row5ColB[0].f3_36[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table6[0].BodyRow6[0].f3_43[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table6[0].BodyRow6[0].Row6ColB[0].f3_44[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table6[0].BodyRow6[0].Row6ColB[0].f3_45[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table6[0].BodyRow6[0].Row6ColB[0].f3_46[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table6[0].BodyRow6[0].Row6ColB[0].f3_47[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table6[0].BodyRow6[0].Row6ColB[0].f3_48[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table6[0].BodyRow6[0].f3_49[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].Table6[0].BodyRow6[0].f3_50[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].f4_1[0]", staticValue: "", description: "Unmapped — page 4" },
    { pdfFieldName: "topmostSubform[0].Page4[0].f4_2[0]", staticValue: "", description: "Unmapped — page 4" },
    { pdfFieldName: "topmostSubform[0].Page4[0].PartIII[0].f4_3[0]", staticValue: "", description: "Unmapped — page 4" },
    { pdfFieldName: "topmostSubform[0].Page4[0].Item1[0].A[0].f4_4[0]", staticValue: "", description: "Unmapped — page 4" },
  ],
};
