import type { FormPdfMapping, FillContext } from "../types";
import { sbCheck, officer, currency } from "../types";

const P = "topmostSubform[0].Page1[0].";

export const F990T_MAPPING: FormPdfMapping = {
  formCode: "990-T",
  pdfFileName: "f990t.pdf",
  taxYear: 2025,
  fields: [
    // -------------------------------------------------------------------------
    // Header fields
    // -------------------------------------------------------------------------
    {
      pdfFieldName: `${P}PgHeader[0].f1_1[0]`,
      compute: (ctx: FillContext) => String(ctx.meta.taxYear),
      format: "string",
      irsLine: "Header",
      description: "Calendar year begin",
    },
    {
      pdfFieldName: `${P}PgHeader[0].f1_2[0]`,
      compute: (ctx: FillContext) => String(ctx.meta.taxYear),
      format: "string",
      irsLine: "Header",
      description: "Calendar year end",
    },
    {
      pdfFieldName: `${P}PgHeader[0].f1_3[0]`,
      compute: (ctx: FillContext) => String(ctx.meta.taxYear),
      format: "string",
      irsLine: "Header",
      description: "Calendar year footer",
    },
    {
      pdfFieldName: `${P}NameAddress_ReadOrder[0].f1_4[0]`,
      compute: (ctx: FillContext) => ctx.meta.companyName,
      format: "string",
      irsLine: "Header",
      description: "Name of organization",
    },
    {
      pdfFieldName: `${P}NameAddress_ReadOrder[0].f1_5[0]`,
      compute: (ctx: FillContext) => ctx.meta.ein,
      format: "string",
      irsLine: "Header",
      description: "Employer Identification Number (EIN)",
    },

    // ── Auto-generated mappings (remaining fields) ──────────────────
    { pdfFieldName: "topmostSubform[0].Page1[0].LinesA-C[0].c1_3[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q3"), format: "boolean", description: "Checkbox: p1_q3" },
    { pdfFieldName: "topmostSubform[0].Page1[0].LinesA-C[0].c1_3[2]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q3"), format: "boolean", description: "Checkbox: p1_q3" },
    { pdfFieldName: "topmostSubform[0].Page1[0].LinesA-C[0].c1_3[3]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q3"), format: "boolean", description: "Checkbox: p1_q3" },
    { pdfFieldName: "topmostSubform[0].Page1[0].LinesA-C[0].c1_3[4]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q3"), format: "boolean", description: "Checkbox: p1_q3" },
    { pdfFieldName: "topmostSubform[0].Page1[0].LinesA-C[0].c1_3[5]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q3"), format: "boolean", description: "Checkbox: p1_q3" },
    { pdfFieldName: "topmostSubform[0].Page1[0].LinesA-C[0].c1_3[6]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q3"), format: "boolean", description: "Checkbox: p1_q3" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_5[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q5"), format: "boolean", description: "Checkbox: p1_q5" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_5[2]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q5"), format: "boolean", description: "Checkbox: p1_q5" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_5[3]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q5"), format: "boolean", description: "Checkbox: p1_q5" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_5[4]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q5"), format: "boolean", description: "Checkbox: p1_q5" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_5[5]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q5"), format: "boolean", description: "Checkbox: p1_q5" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_6[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q6"), format: "boolean", description: "Checkbox: p1_q6" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_6[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q6"), format: "boolean", description: "Checkbox: p1_q6" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_6[2]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q6"), format: "boolean", description: "Checkbox: p1_q6" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_7[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q7"), format: "boolean", description: "Checkbox: p1_q7" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_8[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q8"), format: "boolean", description: "Checkbox: p1_q8" },
    { pdfFieldName: "topmostSubform[0].Page1[0].c1_8[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q8"), format: "boolean", description: "Checkbox: p1_q8" },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line2_ReadOrder[0].c1_9[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q9"), format: "boolean", description: "Checkbox: p1_q9" },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line2_ReadOrder[0].c1_9[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q9"), format: "boolean", description: "Checkbox: p1_q9" },
    { pdfFieldName: "topmostSubform[0].Page1[0].Line4_ReadOrder[0].c1_10[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p1_q10"), format: "boolean", description: "Checkbox: p1_q10" },
    { pdfFieldName: "topmostSubform[0].Page1[0].f1_52[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Line16b_ReadOrder[0].c2_1[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q1"), format: "boolean", description: "Checkbox: p2_q1" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_7[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_8[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_9[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_10[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_11[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_12[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_13[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_14[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_2[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q2"), format: "boolean", description: "Checkbox: p2_q2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_15[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_16[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_17[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_18[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_19[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Line1_ReadOrder[0].f2_20[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Line1_ReadOrder[0].c2_3[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q3"), format: "boolean", description: "Checkbox: p2_q3" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Line1_ReadOrder[0].c2_3[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q3"), format: "boolean", description: "Checkbox: p2_q3" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_4[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q4"), format: "boolean", description: "Checkbox: p2_q4" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_4[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q4"), format: "boolean", description: "Checkbox: p2_q4" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_21[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_22[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Line5Table[0].Row1[0].f2_23[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Line5Table[0].Row1[0].f2_24[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Line5Table[0].Row2[0].f2_25[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Line5Table[0].Row2[0].f2_26[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Line5Table[0].Row3[0].f2_27[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Line5Table[0].Row3[0].f2_28[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Line5Table[0].Row4[0].f2_29[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].Line5Table[0].Row4[0].f2_30[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_5[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q5"), format: "boolean", description: "Checkbox: p2_q5" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_5[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q5"), format: "boolean", description: "Checkbox: p2_q5" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_6[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q6"), format: "boolean", description: "Checkbox: p2_q6" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_6[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q6"), format: "boolean", description: "Checkbox: p2_q6" },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartV_SupplementalInformation[0].f2_31[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].SignHere[0].f2_32[0]", manual: true, description: "signature_or_preparer" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_7[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q7"), format: "boolean", description: "Checkbox: p2_q7" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_7[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q7"), format: "boolean", description: "Checkbox: p2_q7" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_33[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].c2_8[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p2_q8"), format: "boolean", description: "Checkbox: p2_q8" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_34[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_35[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_36[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_37[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].f2_38[0]", staticValue: "", description: "Unmapped — page 2" },
  ],
};
