import type { FormPdfMapping, FillContext } from "../types";
import { sbCheck, officer, currency } from "../types";

const P = "topmostSubform[0].Page1[0].";

export const F990EZ_MAPPING: FormPdfMapping = {
  formCode: "990-EZ",
  pdfFileName: "f990ez.pdf",
  taxYear: 2025,
  fields: [
    // -------------------------------------------------------------------------
    // Header fields
    // -------------------------------------------------------------------------
    {
      pdfFieldName: `${P}p1-t1[0]`,
      compute: (ctx: FillContext) => String(ctx.meta.taxYear),
      format: "string",
      irsLine: "Header",
      description: "Calendar year",
    },
    {
      pdfFieldName: `${P}p1-t2[0]`,
      compute: (ctx: FillContext) => ctx.meta.companyName,
      format: "string",
      irsLine: "Header",
      description: "Name of organization",
    },
    {
      pdfFieldName: `${P}p1-t3[0]`,
      compute: (ctx: FillContext) => ctx.meta.ein,
      format: "string",
      irsLine: "Header",
      description: "Employer Identification Number (EIN)",
    },

    // -------------------------------------------------------------------------
    // Part I — Revenue, Expenses, and Changes in Net Assets
    // -------------------------------------------------------------------------
    {
      pdfFieldName: `${P}f1_01[0]`,
      factName: "gross_receipts_total",
      format: "currency",
      irsLine: "1",
      description: "Contributions, gifts, grants, and similar amounts received",
    },
    {
      pdfFieldName: `${P}f1_09[0]`,
      factName: "wages_total",
      format: "currency",
      irsLine: "12",
      description: "Salaries, other compensation, and employee benefits",
    },
    {
      pdfFieldName: `${P}f1_13[0]`,
      factName: "general_deduction_total",
      format: "currency",
      irsLine: "16",
      description: "Other expenses",
    },

    // -------------------------------------------------------------------------
    // Part II — Balance Sheets
    // -------------------------------------------------------------------------
    {
      pdfFieldName: `${P}f1_25[0]`,
      factName: "total_assets",
      format: "currency",
      irsLine: "25",
      description: "Total assets (end of year)",
    },

    // ── Auto-generated mappings (remaining fields) ──────────────────
    { pdfFieldName: "topmostSubform[0].Page1[0].LineB[0].p1-cb1[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page1[0].LineB[0].p1-cb2[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page1[0].LineB[0].p1-cb3[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page1[0].LineB[0].p1-cb4[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page1[0].LineB[0].p1-cb5[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page1[0].LineB[0].p1-cb6[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page1[0].LineC[0].p1-t4[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].LineC[0].help[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page1[0].LineC[0].p1-t5[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].LineC[0].help[1]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page1[0].LineC[0].p1-t6[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].LineC[0].p1-t7[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t9[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].help[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t11[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].help[1]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t12[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-cb7[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-cb7[1]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t13[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].#subform[2].p1-cb9[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page1[0].#subform[2].help[2]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t14[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-cb10[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-cb10[1]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t14a[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-cb10[2]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-cb10[3]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-cb14[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-cb14[1]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-cb14[2]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-cb14[3]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t300[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t15[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].Part1[0].help[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-cb15[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page1[0].help[3]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t16[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].help[4]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t17[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].help[5]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t18[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].help[6]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t19[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t20[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t21[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t22[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t24[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t25[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t100[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t26[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t101[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t27[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t28[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t29[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t31[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t32[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t33[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t34[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].help[7]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t35[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].help[8]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t36[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t37[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t38[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].help[9]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t40[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t41[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t42[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t43[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t44[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page1[0].p1-t45[0]", staticValue: "", description: "Unmapped — page 1" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part2[0].help[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page2[0].p2_c1[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page2[0].p2-t346[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].p2-t347[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].p2-t348[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].p2-t349[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].p2-t351[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].p2-t352[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].p2-t353[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].p2-t354[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].p2-t356[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].p2-t357[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].p2-t358[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].p2-t359[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Part3[0].help[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page2[0].p2_c2[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page2[0].p2-t1[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].help[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Line28Text[0].p2-t2[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Line28Text[0].p2-t3[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Line28Text[0].help[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Line28Text[0].p2-t4[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Line28Text[0].p2-t5[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Line28Text[0].p2-c3[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page2[0].p2-t6[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].help[1]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Line29Text[0].p2-t7[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Line29Text[0].p2-t8[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Line29Text[0].p2-t9[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Line29Text[0].p2-t10[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Line29Text[0].p2-c4[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page2[0].p2-t11[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Line30Text[0].p2-t12[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Line30Text[0].p2-t13[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Line30Text[0].p2-t14[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Line30Text[0].p2-t15[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Line30Text[0].p2-c5[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page2[0].p2-t16[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Line31Text[0].p2-t17[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].Line31Text[0].p2-c6[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page2[0].p2-t18[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].p2-t19[0]", staticValue: "", description: "Unmapped — page 2" },
    { pdfFieldName: "topmostSubform[0].Page2[0].p2-c7[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page2[0].help[2]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page2[0].help[3]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow1[0].Row1[0].p2-t20[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow1[0].Row1[0].p2-t21[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow1[0].p2-t22[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow1[0].p2-t23[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow1[0].p2-t24[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow1[0].p2-t25[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow2[0].Row2[0].p2-t26[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow2[0].Row2[0].p2-t27[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow2[0].p2-t28[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow2[0].p2-t29[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow2[0].p2-t30[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow2[0].p2-t31[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow3[0].Row3[0].p2-t32[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow3[0].Row3[0].p2-t33[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow3[0].p2-t34[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow3[0].p2-t35[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow3[0].p2-t36[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow3[0].p2-t37[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow4[0].Row4[0].p2-t38[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow4[0].Row4[0].p2-t39[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow4[0].p2-t40[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow4[0].p2-t41[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow4[0].p2-t42[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow4[0].p2-t43[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow5[0].Row5[0].p2-t44[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow5[0].Row5[0].p2-t45[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow5[0].p2-t46[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow5[0].p2-t47[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow5[0].p2-t48[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow5[0].p2-t49[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow6[0].Row6[0].p2-t50[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow6[0].Row6[0].p2-t51[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow6[0].p2-t52[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow6[0].p2-t53[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow6[0].p2-t54[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow6[0].p2-t55[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow7[0].Row7[0].p2-t56[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow7[0].Row7[0].p2-t57[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow7[0].p2-t58[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow7[0].p2-t59[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow7[0].p2-t60[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow7[0].p2-t61[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow8[0].Row8[0].p2-t62[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow8[0].Row8[0].p2-t63[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow8[0].p2-t64[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow8[0].p2-t65[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow8[0].p2-t66[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow8[0].p2-t67[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow9[0].Row9[0].p2-t68[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow9[0].Row9[0].p2-t69[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow9[0].p2-t70[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow9[0].p2-t71[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow9[0].p2-t72[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow9[0].p2-t73[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow10[0].Row10[0].p2-t74[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow10[0].Row10[0].p2-t75[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow10[0].p2-t76[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow10[0].p2-t77[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow10[0].p2-t78[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow10[0].p2-t79[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow11[0].Row11[0].p2-t80[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow11[0].Row11[0].p2-t81[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow11[0].p2-t82[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow11[0].p2-t83[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow11[0].p2-t84[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page2[0].PartIVTable[0].BodyRow11[0].p2-t85[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_001[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q001"), format: "boolean", description: "Checkbox: p3_q001" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_002[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q002"), format: "boolean", description: "Checkbox: p3_q002" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_002[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q002"), format: "boolean", description: "Checkbox: p3_q002" },
    { pdfFieldName: "topmostSubform[0].Page3[0].help[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page3[0].help[1]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_003[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q003"), format: "boolean", description: "Checkbox: p3_q003" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_003[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q003"), format: "boolean", description: "Checkbox: p3_q003" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_004[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q004"), format: "boolean", description: "Checkbox: p3_q004" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_004[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q004"), format: "boolean", description: "Checkbox: p3_q004" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_005[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q005"), format: "boolean", description: "Checkbox: p3_q005" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_005[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q005"), format: "boolean", description: "Checkbox: p3_q005" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_006[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q006"), format: "boolean", description: "Checkbox: p3_q006" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_006[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q006"), format: "boolean", description: "Checkbox: p3_q006" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_007[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q007"), format: "boolean", description: "Checkbox: p3_q007" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_007[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q007"), format: "boolean", description: "Checkbox: p3_q007" },
    { pdfFieldName: "topmostSubform[0].Page3[0].help[2]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page3[0].p3-t1[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_008[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q008"), format: "boolean", description: "Checkbox: p3_q008" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_008[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q008"), format: "boolean", description: "Checkbox: p3_q008" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_009[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q009"), format: "boolean", description: "Checkbox: p3_q009" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_009[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q009"), format: "boolean", description: "Checkbox: p3_q009" },
    { pdfFieldName: "topmostSubform[0].Page3[0].help[3]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page3[0].p3-t2[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].p3-t3[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].p3-t4[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].p3-t5[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].p3-t6[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].p3-t7[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_010[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q010"), format: "boolean", description: "Checkbox: p3_q010" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_010[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q010"), format: "boolean", description: "Checkbox: p3_q010" },
    { pdfFieldName: "topmostSubform[0].Page3[0].help[4]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page3[0].p3-t8[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].p3-t9[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_011[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q011"), format: "boolean", description: "Checkbox: p3_q011" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_011[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q011"), format: "boolean", description: "Checkbox: p3_q011" },
    { pdfFieldName: "topmostSubform[0].Page3[0].p3-t10[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].p3-t11[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].p3-t14[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].p3-t12[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].p3-t15[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_012[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q012"), format: "boolean", description: "Checkbox: p3_q012" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_012[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q012"), format: "boolean", description: "Checkbox: p3_q012" },
    { pdfFieldName: "topmostSubform[0].Page3[0].p3-t16[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_013[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q013"), format: "boolean", description: "Checkbox: p3_q013" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_013[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q013"), format: "boolean", description: "Checkbox: p3_q013" },
    { pdfFieldName: "topmostSubform[0].Page3[0].p3-t17[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_014[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q014"), format: "boolean", description: "Checkbox: p3_q014" },
    { pdfFieldName: "topmostSubform[0].Page3[0].p3-t18[0]", staticValue: "", description: "Unmapped — page 3" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_015[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q015"), format: "boolean", description: "Checkbox: p3_q015" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_015[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q015"), format: "boolean", description: "Checkbox: p3_q015" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_016[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q016"), format: "boolean", description: "Checkbox: p3_q016" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_016[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q016"), format: "boolean", description: "Checkbox: p3_q016" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_017[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q017"), format: "boolean", description: "Checkbox: p3_q017" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_017[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q017"), format: "boolean", description: "Checkbox: p3_q017" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_018[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q018"), format: "boolean", description: "Checkbox: p3_q018" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_018[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q018"), format: "boolean", description: "Checkbox: p3_q018" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_019[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q019"), format: "boolean", description: "Checkbox: p3_q019" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_019[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q019"), format: "boolean", description: "Checkbox: p3_q019" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_020[0]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q020"), format: "boolean", description: "Checkbox: p3_q020" },
    { pdfFieldName: "topmostSubform[0].Page3[0].c3_020[1]", compute: (ctx: FillContext) => sbCheck(ctx, "p3_q020"), format: "boolean", description: "Checkbox: p3_q020" },
    { pdfFieldName: "topmostSubform[0].Page4[0].p4-c3[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page4[0].p4-c3[1]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page4[0].help[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page4[0].p4-c4[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page4[0].p4-c5[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page4[0].p4-c5[1]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page4[0].help[1]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page4[0].p4-c6[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page4[0].p4-c6[1]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page4[0].help[2]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page4[0].p4-cb7[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page4[0].p4-cb7[1]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page4[0].p4-cb8[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page4[0].p4-cb8[1]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page4[0].Line50Table[0].BodyRow1[0].Row1[0].p4-t1[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].Line50Table[0].BodyRow1[0].Row1[0].p4-t2[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].Line50Table[0].BodyRow1[0].p4-t3[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].Line50Table[0].BodyRow1[0].p4-t4[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].Line50Table[0].BodyRow1[0].p4-t100[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].Line50Table[0].BodyRow1[0].p4-t5[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].Line50Table[0].BodyRow2[0].Row2[0].p4-t7[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].Line50Table[0].BodyRow2[0].Row2[0].p4-t8[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].Line50Table[0].BodyRow2[0].p4-t9[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].Line50Table[0].BodyRow2[0].p4-t10[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].Line50Table[0].BodyRow2[0].p4-t101[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].Line50Table[0].BodyRow2[0].p4-t11[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].Line50Table[0].BodyRow3[0].Row3[0].p4-t13[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].Line50Table[0].BodyRow3[0].Row3[0].p4-t14[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].Line50Table[0].BodyRow3[0].p4-t15[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].Line50Table[0].BodyRow3[0].p4-t16[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].Line50Table[0].BodyRow3[0].p4-t102[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].Line50Table[0].BodyRow3[0].p4-t17[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].Line50Table[0].BodyRow4[0].Row4[0].p4-t19[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].Line50Table[0].BodyRow4[0].Row4[0].p4-t20[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].Line50Table[0].BodyRow4[0].p4-t21[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].Line50Table[0].BodyRow4[0].p4-t22[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].Line50Table[0].BodyRow4[0].p4-t102[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].Line50Table[0].BodyRow4[0].p4-t23[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].Line50Table[0].BodyRow5[0].Row5[0].p4-t24[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].Line50Table[0].BodyRow5[0].Row5[0].p4-t25[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].Line50Table[0].BodyRow5[0].p4-t26[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].Line50Table[0].BodyRow5[0].p4-t27[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].Line50Table[0].BodyRow5[0].p4-t103[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].Line50Table[0].BodyRow5[0].p4-t28[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].p4-t66[0]", staticValue: "", description: "Unmapped — page 4" },
    { pdfFieldName: "topmostSubform[0].Page4[0].PartVITable2[0].BodyRow1[0].Row1[0].p4-t32[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].PartVITable2[0].BodyRow1[0].Row1[0].p4-t33[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].PartVITable2[0].BodyRow1[0].p4-t34[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].PartVITable2[0].BodyRow1[0].p4-t35[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].PartVITable2[0].BodyRow2[0].Row2[0].p4-t36[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].PartVITable2[0].BodyRow2[0].Row2[0].p4-t37[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].PartVITable2[0].BodyRow2[0].p4-t38[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].PartVITable2[0].BodyRow2[0].p4-t39[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].PartVITable2[0].BodyRow3[0].Row3[0].p4-t40[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].PartVITable2[0].BodyRow3[0].Row3[0].p4-t41[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].PartVITable2[0].BodyRow3[0].p4-t42[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].PartVITable2[0].BodyRow3[0].p4-t43[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].PartVITable2[0].BodyRow4[0].Row4[0].p4-t44[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].PartVITable2[0].BodyRow4[0].Row4[0].p4-t45[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].PartVITable2[0].BodyRow4[0].p4-t46[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].PartVITable2[0].BodyRow4[0].p4-t47[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].PartVITable2[0].BodyRow5[0].Row5[0].p4-t48[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].PartVITable2[0].BodyRow5[0].Row5[0].p4-t49[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].PartVITable2[0].BodyRow5[0].p4-t50[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].PartVITable2[0].BodyRow5[0].p4-t51[0]", staticValue: "", description: "Table  Line " },
    { pdfFieldName: "topmostSubform[0].Page4[0].p4-t52[0]", staticValue: "", description: "Unmapped — page 4" },
    { pdfFieldName: "topmostSubform[0].Page4[0].p4-cb9[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page4[0].p4-cb9[1]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page4[0].help[3]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page4[0].p4-t53[0]", staticValue: "", description: "Unmapped — page 4" },
    { pdfFieldName: "topmostSubform[0].Page4[0].p4_100_0_[0]", staticValue: "", description: "Unmapped — page 4" },
    { pdfFieldName: "topmostSubform[0].Page4[0].p4-cb10[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page4[0].f4_65_0_[0]", staticValue: "", description: "Unmapped — page 4" },
    { pdfFieldName: "topmostSubform[0].Page4[0].f4_66_0_[0]", staticValue: "", description: "Unmapped — page 4" },
    { pdfFieldName: "topmostSubform[0].Page4[0].f4_68_0_[0]", staticValue: "", description: "Unmapped — page 4" },
    { pdfFieldName: "topmostSubform[0].Page4[0].f4_69_0_[0]", staticValue: "", description: "Unmapped — page 4" },
    { pdfFieldName: "topmostSubform[0].Page4[0].f4_73_0_[0]", staticValue: "", description: "Unmapped — page 4" },
    { pdfFieldName: "topmostSubform[0].Page4[0].p4-cb11[0]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
    { pdfFieldName: "topmostSubform[0].Page4[0].p4-cb11[1]", compute: (ctx: FillContext) => sbCheck(ctx, "checkbox"), format: "boolean", description: "Checkbox: checkbox" },
  ],
};
