/** Maps a form code to its MeF XML configuration */
export interface MefFormSchema {
  formCode: string;
  returnTypeCd: string;
  xmlRootElement: string;
  xmlNamespace: string;
  /** Fact name → XML element name */
  fieldMap: { factName: string; xmlElement: string; required?: boolean; defaultValue?: string }[];
}

export const MEF_SCHEMAS: Record<string, MefFormSchema> = {
  "1120": {
    formCode: "1120",
    returnTypeCd: "1120",
    xmlRootElement: "IRS1120",
    xmlNamespace: "urn:us:gov:treasury:irs:ir",
    fieldMap: [
      // Income
      { factName: "gross_receipts_total", xmlElement: "GrossReceiptsOrSalesAmt", required: true },
      { factName: "returns_allowances_total", xmlElement: "ReturnsAndAllowancesAmt" },
      { factName: "gross_profit", xmlElement: "GrossProfitAmt" },
      { factName: "cogs_total", xmlElement: "CostOfGoodsSoldAmt" },
      { factName: "dividend_income_total", xmlElement: "DividendsAndInclusionsAmt" },
      { factName: "interest_income_total", xmlElement: "InterestIncomeAmt" },
      { factName: "rent_income_total", xmlElement: "GrossRentsAmt" },
      { factName: "royalty_income_total", xmlElement: "GrossRoyaltiesAmt" },
      { factName: "capital_gain_total", xmlElement: "CapitalGainNetIncomeAmt" },
      { factName: "other_income_total", xmlElement: "OtherIncomeAmt" },
      { factName: "total_income", xmlElement: "TotalIncomeAmt", required: true },
      // Deductions
      { factName: "officer_compensation_total", xmlElement: "OfficersCompensationAmt" },
      { factName: "wages_total", xmlElement: "SalariesAndWagesAmt" },
      { factName: "repairs_total", xmlElement: "RepairsAndMaintenanceAmt" },
      { factName: "bad_debt_total", xmlElement: "BadDebtsAmt" },
      { factName: "rent_building_total", xmlElement: "RentsAmt" },
      { factName: "taxes_licenses_total", xmlElement: "TaxesAndLicensesAmt" },
      { factName: "interest_expense_total", xmlElement: "InterestAmt" },
      { factName: "charitable_contributions_allowable", xmlElement: "CharitableContributionsAmt" },
      { factName: "depreciation_total", xmlElement: "DepreciationAmt" },
      { factName: "advertising_total", xmlElement: "AdvertisingAmt" },
      { factName: "pension_profitsharing_total", xmlElement: "PensionProfSharingPlansAmt" },
      { factName: "employee_benefits_total", xmlElement: "EmployeeBenefitProgramAmt" },
      { factName: "general_deduction_total", xmlElement: "OtherDeductionsAmt" },
      { factName: "total_deductions", xmlElement: "TotalDeductionsAmt", required: true },
      // Tax computation
      { factName: "taxable_income_before_nol", xmlElement: "TaxableIncomeBeforeNOLDedAmt" },
      { factName: "special_deductions_drd", xmlElement: "SpecialDeductionsAmt" },
      { factName: "taxable_income", xmlElement: "TaxableIncomeAmt", required: true },
      { factName: "corporate_tax_21pct", xmlElement: "TotalTaxAmt", required: true },
      { factName: "estimated_tax_payments_total", xmlElement: "TotalPaymentsAndCreditsAmt" },
      { factName: "amount_owed", xmlElement: "AmountOwedAmt" },
      { factName: "overpayment_amount", xmlElement: "OverpaymentAmt" },
    ],
  },
  "1120-S": {
    formCode: "1120-S",
    returnTypeCd: "1120S",
    xmlRootElement: "IRS1120S",
    xmlNamespace: "urn:us:gov:treasury:irs:ir",
    fieldMap: [
      { factName: "gross_receipts_total", xmlElement: "GrossReceiptsOrSalesAmt", required: true },
      { factName: "returns_allowances_total", xmlElement: "ReturnsAndAllowancesAmt" },
      { factName: "cogs_total", xmlElement: "CostOfGoodsSoldAmt" },
      { factName: "gross_profit", xmlElement: "GrossProfitAmt" },
      { factName: "other_income_total", xmlElement: "OtherIncomeLossAmt" },
      { factName: "total_income", xmlElement: "TotalIncomeLossAmt", required: true },
      { factName: "officer_compensation_total", xmlElement: "CompensationOfOfficersAmt" },
      { factName: "wages_total", xmlElement: "SalariesAndWagesAmt" },
      { factName: "repairs_total", xmlElement: "RepairsAndMaintenanceAmt" },
      { factName: "bad_debt_total", xmlElement: "BadDebtsAmt" },
      { factName: "rent_building_total", xmlElement: "RentsAmt" },
      { factName: "taxes_licenses_total", xmlElement: "TaxesAndLicensesAmt" },
      { factName: "interest_expense_total", xmlElement: "InterestAmt" },
      { factName: "depreciation_total", xmlElement: "DepreciationAmt" },
      { factName: "advertising_total", xmlElement: "AdvertisingAmt" },
      { factName: "general_deduction_total", xmlElement: "OtherDeductionsAmt" },
      { factName: "total_deductions", xmlElement: "TotalDeductionsAmt", required: true },
      { factName: "ordinary_business_income", xmlElement: "OrdinaryBusinessIncomeLossAmt", required: true },
    ],
  },
  "1065": {
    formCode: "1065",
    returnTypeCd: "1065",
    xmlRootElement: "IRS1065",
    xmlNamespace: "urn:us:gov:treasury:irs:ir",
    fieldMap: [
      { factName: "gross_receipts_total", xmlElement: "GrossReceiptsOrSalesAmt", required: true },
      { factName: "returns_allowances_total", xmlElement: "ReturnsAndAllowancesAmt" },
      { factName: "cogs_total", xmlElement: "CostOfGoodsSoldAmt" },
      { factName: "gross_profit", xmlElement: "GrossProfitAmt" },
      { factName: "other_income_total", xmlElement: "OtherIncomeLossAmt" },
      { factName: "total_income", xmlElement: "TotalIncomeLossAmt", required: true },
      { factName: "wages_total", xmlElement: "SalariesAndWagesAmt" },
      { factName: "guaranteed_payments_total", xmlElement: "GuaranteedPaymentsToPartnersAmt" },
      { factName: "repairs_total", xmlElement: "RepairsAndMaintenanceAmt" },
      { factName: "bad_debt_total", xmlElement: "BadDebtsAmt" },
      { factName: "rent_building_total", xmlElement: "RentsAmt" },
      { factName: "taxes_licenses_total", xmlElement: "TaxesAndLicensesAmt" },
      { factName: "interest_expense_total", xmlElement: "InterestAmt" },
      { factName: "depreciation_total", xmlElement: "DepreciationAmt" },
      { factName: "general_deduction_total", xmlElement: "OtherDeductionsAmt" },
      { factName: "total_deductions", xmlElement: "TotalDeductionsAmt", required: true },
      { factName: "ordinary_business_income", xmlElement: "OrdinaryBusinessIncomeLossAmt", required: true },
    ],
  },
  "Sch C": {
    formCode: "Sch C",
    returnTypeCd: "1040",
    xmlRootElement: "IRS1040ScheduleC",
    xmlNamespace: "urn:us:gov:treasury:irs:ir",
    fieldMap: [
      { factName: "gross_receipts_total", xmlElement: "GrossReceiptsOrSalesAmt", required: true },
      { factName: "returns_allowances_total", xmlElement: "ReturnsAndAllowancesAmt" },
      { factName: "cogs_total", xmlElement: "CostOfGoodsSoldAmt" },
      { factName: "gross_profit", xmlElement: "GrossProfitAmt" },
      { factName: "other_income_total", xmlElement: "OtherIncomeAmt" },
      { factName: "total_income", xmlElement: "GrossIncomeAmt", required: true },
      { factName: "advertising_total", xmlElement: "AdvertisingAmt" },
      { factName: "auto_expense_total", xmlElement: "CarAndTruckExpensesAmt" },
      { factName: "commission_total", xmlElement: "CommissionsAndFeesAmt" },
      { factName: "contract_labor_total", xmlElement: "ContractLaborAmt" },
      { factName: "depreciation_total", xmlElement: "DepreciationAndSection179Amt" },
      { factName: "employee_benefits_total", xmlElement: "EmployeeBenefitProgramAmt" },
      { factName: "insurance_total", xmlElement: "InsuranceAmt" },
      { factName: "interest_expense_total", xmlElement: "MortgageOrOtherInterestAmt" },
      { factName: "professional_fees_total", xmlElement: "LegalAndProfessionalServicesAmt" },
      { factName: "office_expense_total", xmlElement: "OfficeExpenseAmt" },
      { factName: "rent_equipment_total", xmlElement: "RentLeaseVehicleMachEquipAmt" },
      { factName: "rent_building_total", xmlElement: "RentLeaseOtherBusPropAmt" },
      { factName: "repairs_total", xmlElement: "RepairsAndMaintenanceAmt" },
      { factName: "supplies_total", xmlElement: "SuppliesAmt" },
      { factName: "taxes_licenses_total", xmlElement: "TaxesAndLicensesAmt" },
      { factName: "travel_total", xmlElement: "TravelAmt" },
      { factName: "meals_subject_to_limitation_total", xmlElement: "MealsAmt" },
      { factName: "utilities_total", xmlElement: "UtilitiesAmt" },
      { factName: "wages_total", xmlElement: "WagesAmt" },
      { factName: "general_deduction_total", xmlElement: "OtherExpensesAmt" },
      { factName: "total_deductions", xmlElement: "TotalExpensesAmt", required: true },
      { factName: "net_income_before_tax", xmlElement: "NetProfitOrLossAmt", required: true },
    ],
  },
  "990": {
    formCode: "990",
    returnTypeCd: "990",
    xmlRootElement: "IRS990",
    xmlNamespace: "urn:us:gov:treasury:irs:ir",
    fieldMap: [
      { factName: "gross_receipts_total", xmlElement: "CYContributionsGrantsAmt", required: true },
      { factName: "program_service_revenue_total", xmlElement: "CYProgramServiceRevenueAmt" },
      { factName: "interest_income_total", xmlElement: "CYInvestmentIncomeAmt" },
      { factName: "other_income_total", xmlElement: "CYOtherRevenueAmt" },
      { factName: "grants_paid_total", xmlElement: "CYGrantsAndSimilarPaidAmt" },
      { factName: "wages_total", xmlElement: "CYSalariesCompEmpBnftPaidAmt" },
      { factName: "general_deduction_total", xmlElement: "CYOtherExpensesAmt" },
      { factName: "total_assets", xmlElement: "TotalAssetsEOYAmt" },
      { factName: "total_liabilities", xmlElement: "TotalLiabilitiesEOYAmt" },
    ],
  },
};
