import type { UnifiedFormSchema } from "../types";

export const F1120_SCHEMA: UnifiedFormSchema = {
  formCode: "1120",
  formTitle: "U.S. Corporation Income Tax Return",
  formSubtitle: "Department of the Treasury — Internal Revenue Service",
  ombNumber: "1545-0123",
  taxYear: 2025,

  xml: {
    rootElement: "IRS1120",
    namespace: "urn:us:gov:treasury:irs:ir",
    returnTypeCd: "1120",
  },

  pdf: {
    fileName: "f1120.pdf",
  },

  sections: [
    { id: "header", title: "Entity Information" },
    { id: "income", title: "Income", sideLabel: "Income" },
    { id: "deductions", title: "Deductions", sideLabel: "Deductions" },
    { id: "tax_computation", title: "Tax, Refundable Credits, and Payments", sideLabel: "Tax and Payments" },
  ],

  fields: [
    // =========================================================================
    // Header — Entity Information
    // =========================================================================
    {
      fieldId: "header_name",
      irsLine: "Header",
      label: "Company name",
      pdfFieldName: "topmostSubform[0].Page1[0].NameFieldsReadOrder[0].f1_4[0]",
      format: "string",
      fieldType: "text",
      metaSource: "companyName",
      section: "header",
      editable: true,
    },
    {
      fieldId: "header_address",
      irsLine: "Header",
      label: "Street address",
      pdfFieldName: "topmostSubform[0].Page1[0].NameFieldsReadOrder[0].f1_5[0]",
      format: "string",
      fieldType: "text",
      metaSource: "address",
      section: "header",
      editable: true,
    },
    {
      fieldId: "header_city",
      irsLine: "Header",
      label: "City",
      pdfFieldName: "topmostSubform[0].Page1[0].NameFieldsReadOrder[0].f1_6[0]",
      format: "string",
      fieldType: "text",
      metaSource: "city",
      section: "header",
      editable: true,
    },
    {
      fieldId: "header_state",
      irsLine: "Header",
      label: "State",
      pdfFieldName: "topmostSubform[0].Page1[0].NameFieldsReadOrder[0].f1_7[0]",
      format: "string",
      fieldType: "text",
      metaSource: "state",
      section: "header",
      editable: true,
    },
    {
      fieldId: "header_zip",
      irsLine: "Header",
      label: "ZIP code",
      pdfFieldName: "topmostSubform[0].Page1[0].NameFieldsReadOrder[0].f1_8[0]",
      format: "string",
      fieldType: "text",
      metaSource: "zip",
      section: "header",
      editable: true,
    },
    {
      fieldId: "header_ein",
      irsLine: "B",
      label: "Employer Identification Number (EIN)",
      pdfFieldName: "topmostSubform[0].Page1[0].NameFieldsReadOrder[0].f1_9[0]",
      format: "ein",
      fieldType: "text",
      metaSource: "ein",
      section: "header",
      editable: true,
    },
    {
      fieldId: "header_date_incorporated",
      irsLine: "C",
      label: "Date incorporated",
      factName: "date_incorporated",
      pdfFieldName: "topmostSubform[0].Page1[0].NameFieldsReadOrder[0].f1_10[0]",
      format: "date",
      fieldType: "text",
      section: "header",
      editable: true,
    },
    {
      fieldId: "header_total_assets",
      irsLine: "D",
      label: "Total assets",
      xmlElement: "TotalAssetsEOYAmt",
      factName: "total_assets",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_11[0]",
      format: "currency",
      fieldType: "amount",
      section: "header",
      editable: true,
    },

    // =========================================================================
    // Income — Lines 1a through 11
    // =========================================================================
    {
      fieldId: "income_1a",
      irsLine: "1a",
      label: "Gross receipts or sales",
      xmlElement: "GrossReceiptsOrSalesAmt",
      factName: "gross_receipts_total",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_14[0]",
      format: "currency",
      fieldType: "amount",
      section: "income",
      editable: true,
      xmlRequired: true,
    },
    {
      fieldId: "income_1b",
      irsLine: "1b",
      label: "Returns and allowances",
      xmlElement: "ReturnsAndAllowancesAmt",
      factName: "returns_allowances_total",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_15[0]",
      format: "currency",
      fieldType: "amount",
      section: "income",
      editable: true,
    },
    {
      fieldId: "income_1c",
      irsLine: "1c",
      label: "Balance (gross receipts minus returns and allowances)",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_16[0]",
      format: "currency",
      fieldType: "computed",
      computeExpr: { op: "-", operands: ["income_1a", "income_1b"] },
      section: "income",
      editable: false,
      bold: true,
    },
    {
      fieldId: "income_2",
      irsLine: "2",
      label: "Cost of goods sold (Schedule A, line 8)",
      xmlElement: "CostOfGoodsSoldAmt",
      factName: "cogs_total",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_17[0]",
      format: "currency",
      fieldType: "amount",
      section: "income",
      editable: true,
    },
    {
      fieldId: "income_3",
      irsLine: "3",
      label: "Gross profit (line 1c minus line 2)",
      xmlElement: "GrossProfitAmt",
      factName: "gross_profit",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_18[0]",
      format: "currency",
      fieldType: "computed",
      computeExpr: { op: "-", operands: ["income_1c", "income_2"] },
      section: "income",
      editable: false,
      bold: true,
    },
    {
      fieldId: "income_4",
      irsLine: "4",
      label: "Dividends and inclusions (Schedule C, line 23, column (a))",
      xmlElement: "DividendsAndInclusionsAmt",
      factName: "dividend_income_total",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_19[0]",
      format: "currency",
      fieldType: "amount",
      section: "income",
      editable: true,
    },
    {
      fieldId: "income_5",
      irsLine: "5",
      label: "Interest",
      xmlElement: "InterestIncomeAmt",
      factName: "interest_income_total",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_20[0]",
      format: "currency",
      fieldType: "amount",
      section: "income",
      editable: true,
    },
    {
      fieldId: "income_6",
      irsLine: "6",
      label: "Gross rents",
      xmlElement: "GrossRentsAmt",
      factName: "rent_income_total",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_21[0]",
      format: "currency",
      fieldType: "amount",
      section: "income",
      editable: true,
    },
    {
      fieldId: "income_7",
      irsLine: "7",
      label: "Gross royalties",
      xmlElement: "GrossRoyaltiesAmt",
      factName: "royalty_income_total",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_22[0]",
      format: "currency",
      fieldType: "amount",
      section: "income",
      editable: true,
    },
    {
      fieldId: "income_8",
      irsLine: "8",
      label: "Capital gain net income (attach Schedule D)",
      xmlElement: "CapitalGainNetIncomeAmt",
      factName: "capital_gain_total",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_23[0]",
      format: "currency",
      fieldType: "amount",
      section: "income",
      editable: true,
    },
    {
      fieldId: "income_9",
      irsLine: "9",
      label: "Net gain or loss from Form 4797 (Part II, line 17)",
      factName: "capital_gain_total",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_24[0]",
      format: "currency",
      fieldType: "amount",
      section: "income",
      editable: true,
    },
    {
      fieldId: "income_10",
      irsLine: "10",
      label: "Other income (attach statement)",
      xmlElement: "OtherIncomeAmt",
      factName: "other_income_total",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_25[0]",
      format: "currency",
      fieldType: "amount",
      section: "income",
      editable: true,
    },
    {
      fieldId: "income_11",
      irsLine: "11",
      label: "Total income (add lines 3 through 10)",
      xmlElement: "TotalIncomeAmt",
      factName: "total_income",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_26[0]",
      format: "currency",
      fieldType: "computed",
      computeExpr: { op: "+", operands: ["income_3", "income_4", "income_5", "income_6", "income_7", "income_8", "income_9", "income_10"] },
      section: "income",
      editable: false,
      bold: true,
      xmlRequired: true,
    },

    // =========================================================================
    // Deductions — Lines 12 through 27
    // =========================================================================
    {
      fieldId: "deduction_12",
      irsLine: "12",
      label: "Compensation of officers (attach Form 1125-E if applicable)",
      xmlElement: "OfficersCompensationAmt",
      factName: "officer_compensation_total",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_27[0]",
      format: "currency",
      fieldType: "amount",
      section: "deductions",
      editable: true,
    },
    {
      fieldId: "deduction_13",
      irsLine: "13",
      label: "Salaries and wages (less employment credits)",
      xmlElement: "SalariesAndWagesAmt",
      factName: "wages_total",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_28[0]",
      format: "currency",
      fieldType: "amount",
      section: "deductions",
      editable: true,
    },
    {
      fieldId: "deduction_14",
      irsLine: "14",
      label: "Repairs and maintenance",
      xmlElement: "RepairsAndMaintenanceAmt",
      factName: "repairs_total",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_29[0]",
      format: "currency",
      fieldType: "amount",
      section: "deductions",
      editable: true,
    },
    {
      fieldId: "deduction_15",
      irsLine: "15",
      label: "Bad debts",
      xmlElement: "BadDebtsAmt",
      factName: "bad_debt_total",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_30[0]",
      format: "currency",
      fieldType: "amount",
      section: "deductions",
      editable: true,
    },
    {
      fieldId: "deduction_16",
      irsLine: "16",
      label: "Rents",
      xmlElement: "RentsAmt",
      factName: "rent_building_total",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_31[0]",
      format: "currency",
      fieldType: "amount",
      section: "deductions",
      editable: true,
    },
    {
      fieldId: "deduction_17",
      irsLine: "17",
      label: "Taxes and licenses",
      xmlElement: "TaxesAndLicensesAmt",
      factName: "taxes_licenses_total",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_32[0]",
      format: "currency",
      fieldType: "amount",
      section: "deductions",
      editable: true,
    },
    {
      fieldId: "deduction_18",
      irsLine: "18",
      label: "Interest (see instructions)",
      xmlElement: "InterestAmt",
      factName: "interest_expense_total",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_33[0]",
      format: "currency",
      fieldType: "amount",
      section: "deductions",
      editable: true,
    },
    {
      fieldId: "deduction_19",
      irsLine: "19",
      label: "Charitable contributions (see instructions for 10% limitation)",
      xmlElement: "CharitableContributionsAmt",
      factName: "charitable_contributions_total",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_34[0]",
      format: "currency",
      fieldType: "amount",
      section: "deductions",
      editable: true,
    },
    {
      fieldId: "deduction_20",
      irsLine: "20",
      label: "Depreciation from Form 4562 not claimed on Schedule A or elsewhere",
      xmlElement: "DepreciationAmt",
      factName: "depreciation_total",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_35[0]",
      format: "currency",
      fieldType: "amount",
      section: "deductions",
      editable: true,
    },
    {
      fieldId: "deduction_21",
      irsLine: "21",
      label: "Depletion",
      factName: "depletion_total",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_36[0]",
      format: "currency",
      fieldType: "amount",
      section: "deductions",
      editable: true,
    },
    {
      fieldId: "deduction_22",
      irsLine: "22",
      label: "Advertising",
      xmlElement: "AdvertisingAmt",
      factName: "advertising_total",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_37[0]",
      format: "currency",
      fieldType: "amount",
      section: "deductions",
      editable: true,
    },
    {
      fieldId: "deduction_23",
      irsLine: "23",
      label: "Pension, profit-sharing, etc., plans",
      xmlElement: "PensionProfSharingPlansAmt",
      factName: "pension_profitsharing_total",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_38[0]",
      format: "currency",
      fieldType: "amount",
      section: "deductions",
      editable: true,
    },
    {
      fieldId: "deduction_24",
      irsLine: "24",
      label: "Employee benefit programs",
      xmlElement: "EmployeeBenefitProgramAmt",
      factName: "employee_benefits_total",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_39[0]",
      format: "currency",
      fieldType: "amount",
      section: "deductions",
      editable: true,
    },
    {
      fieldId: "deduction_25",
      irsLine: "25",
      label: "Reserved for future use (intentionally blank)",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_40[0]",
      format: "currency",
      fieldType: "static",
      staticValue: "",
      section: "deductions",
      editable: false,
    },
    {
      fieldId: "deduction_26",
      irsLine: "26",
      label: "Other deductions (attach statement)",
      xmlElement: "OtherDeductionsAmt",
      factName: "general_deduction_total",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_41[0]",
      format: "currency",
      fieldType: "amount",
      section: "deductions",
      editable: true,
    },
    {
      fieldId: "deduction_27",
      irsLine: "27",
      label: "Total deductions (add lines 12 through 26)",
      xmlElement: "TotalDeductionsAmt",
      factName: "total_deductions",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_42[0]",
      format: "currency",
      fieldType: "computed",
      computeExpr: {
        op: "+",
        operands: [
          "deduction_12", "deduction_13", "deduction_14", "deduction_15",
          "deduction_16", "deduction_17", "deduction_18", "deduction_19",
          "deduction_20", "deduction_21", "deduction_22", "deduction_23",
          "deduction_24", "deduction_26",
        ],
      },
      section: "deductions",
      editable: false,
      bold: true,
      xmlRequired: true,
    },

    // =========================================================================
    // Tax Computation — Lines 28 through 35
    // =========================================================================
    {
      fieldId: "tax_28",
      irsLine: "28",
      label: "Taxable income before net operating loss deduction and special deductions (line 11 minus line 27)",
      xmlElement: "TaxableIncomeBeforeNOLDedAmt",
      factName: "taxable_income_before_nol",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_43[0]",
      format: "currency",
      fieldType: "computed",
      computeExpr: { op: "-", operands: ["income_11", "deduction_27"] },
      section: "tax_computation",
      editable: false,
      bold: true,
    },
    {
      fieldId: "tax_29a",
      irsLine: "29a",
      label: "Net operating loss (NOL) deduction",
      factName: "nol_deduction_total",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_44[0]",
      format: "currency",
      fieldType: "amount",
      section: "tax_computation",
      editable: true,
    },
    {
      fieldId: "tax_29b",
      irsLine: "29b",
      label: "Special deductions (Schedule C, line 24, column (c))",
      xmlElement: "SpecialDeductionsAmt",
      factName: "special_deductions_drd",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_45[0]",
      format: "currency",
      fieldType: "amount",
      section: "tax_computation",
      editable: true,
    },
    {
      fieldId: "tax_30",
      irsLine: "30",
      label: "Taxable income (line 28 minus lines 29a and 29b; see instructions)",
      xmlElement: "TaxableIncomeAmt",
      factName: "taxable_income",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_46[0]",
      format: "currency",
      fieldType: "computed",
      computeExpr: { op: "-", operands: ["tax_28", "tax_29a", "tax_29b"] },
      section: "tax_computation",
      editable: false,
      bold: true,
      xmlRequired: true,
    },
    {
      fieldId: "tax_31",
      irsLine: "31",
      label: "Total tax (Schedule J, Part I, line 11)",
      xmlElement: "TotalTaxAmt",
      factName: "corporate_tax_21pct",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_47[0]",
      format: "currency",
      fieldType: "amount",
      section: "tax_computation",
      editable: true,
      bold: true,
      xmlRequired: true,
    },
    {
      fieldId: "tax_32",
      irsLine: "32",
      label: "Total payments and credits (Schedule J, Part II, line 21)",
      xmlElement: "TotalPaymentsAndCreditsAmt",
      factName: "estimated_tax_payments_total",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_48[0]",
      format: "currency",
      fieldType: "amount",
      section: "tax_computation",
      editable: true,
    },
    {
      fieldId: "tax_33",
      irsLine: "33",
      label: "Estimated tax penalty (see instructions; check if Form 2220 is attached)",
      factName: "estimated_tax_penalty",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_49[0]",
      format: "currency",
      fieldType: "amount",
      section: "tax_computation",
      editable: true,
    },
    {
      fieldId: "tax_34",
      irsLine: "34",
      label: "Amount owed (if line 31 plus line 33 is greater than line 32)",
      xmlElement: "AmountOwedAmt",
      factName: "amount_owed",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_50[0]",
      format: "currency",
      fieldType: "computed",
      computeExpr: { op: "-", operands: ["tax_31", "tax_32"] },
      section: "tax_computation",
      editable: false,
      bold: true,
    },
    {
      fieldId: "tax_35",
      irsLine: "35",
      label: "Overpayment (if line 32 is larger than the total of lines 31 and 33)",
      xmlElement: "OverpaymentAmt",
      factName: "overpayment_amount",
      pdfFieldName: "topmostSubform[0].Page1[0].f1_51[0]",
      format: "currency",
      fieldType: "computed",
      computeExpr: { op: "-", operands: ["tax_32", "tax_31", "tax_33"] },
      section: "tax_computation",
      editable: false,
      bold: true,
    },
  ],
};
