export const metadata = {
  title: "Terms of Service | TaxEngine",
};

export default function TermsPage() {
  return (
    <main className="max-w-3xl mx-auto px-6 py-12 text-stone-800">
      <h1 className="text-2xl font-semibold mb-2">Terms of Service</h1>
      <p className="text-sm text-stone-500 mb-8">Last updated: March 30, 2026</p>

      <section className="space-y-6 text-sm leading-relaxed">
        <div>
          <h2 className="font-semibold mb-1">1. Service Description</h2>
          <p>
            TaxEngine is a tax preparation analysis tool that integrates with QuickBooks Online
            ("QBO") to help businesses identify required IRS forms, generate pre-filled tax
            documents, and surface potential compliance issues. The Service reads your QBO data in
            read-only mode and produces tax analysis outputs for review by qualified tax
            professionals.
          </p>
        </div>

        <div>
          <h2 className="font-semibold mb-1">2. Eligibility</h2>
          <p>
            You must be at least 18 years of age and have the legal authority to bind the business
            entity whose QBO data you connect to the Service. By using the Service, you represent
            that you have such authority.
          </p>
        </div>

        <div>
          <h2 className="font-semibold mb-1">3. QuickBooks Online Access</h2>
          <p>
            To use the Service, you must authorize TaxEngine to access your QBO account via
            Intuit's OAuth 2.0 protocol. You may revoke this access at any time by disconnecting
            within the application or through your Intuit account settings. TaxEngine requests
            only read-only access and will never create, modify, or delete any records in your QBO
            account.
          </p>
        </div>

        <div>
          <h2 className="font-semibold mb-1">4. Acceptable Use</h2>
          <p>You agree to use the Service only for lawful purposes. You may not:</p>
          <ul className="list-disc pl-5 mt-1 space-y-1">
            <li>Use the Service to facilitate tax evasion, fraud, or other illegal activity</li>
            <li>Attempt to gain unauthorized access to the Service or its infrastructure</li>
            <li>Interfere with or disrupt the Service or connected third-party services</li>
            <li>Resell, sublicense, or redistribute the Service without written consent</li>
            <li>Use automated means to scrape or extract data from the Service</li>
          </ul>
        </div>

        <div>
          <h2 className="font-semibold mb-1">5. Not Tax Advice</h2>
          <p>
            TaxEngine is a tax preparation tool, not a licensed tax advisor, CPA, or attorney. All
            tax determinations, form selections, and computed values generated by the Service are
            provided for informational purposes only and should be reviewed by a qualified tax
            professional before filing with the IRS or any tax authority. TaxEngine does not
            guarantee the accuracy, completeness, or timeliness of any tax analysis.
          </p>
        </div>

        <div>
          <h2 className="font-semibold mb-1">6. Intellectual Property</h2>
          <p>
            The Service, including its software, algorithms, user interface, and documentation, is
            the intellectual property of TaxEngine and is protected by applicable copyright and
            trade secret laws. Your use of the Service does not grant you ownership of any
            intellectual property rights in the Service.
          </p>
        </div>

        <div>
          <h2 className="font-semibold mb-1">7. Third-Party Services</h2>
          <p>
            The Service integrates with QuickBooks Online (provided by Intuit Inc.) and may use
            other third-party services for hosting and data storage. Your use of these third-party
            services is subject to their respective terms and privacy policies. TaxEngine is not
            responsible for the availability or performance of third-party services.
          </p>
        </div>

        <div>
          <h2 className="font-semibold mb-1">8. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by applicable law, TaxEngine and its officers,
            directors, employees, and agents shall not be liable for any indirect, incidental,
            special, consequential, or punitive damages, including but not limited to loss of
            profits, data, or business opportunities, arising from your use of or inability to
            use the Service, including any tax penalties, interest, or assessments resulting from
            reliance on the Service's output.
          </p>
        </div>

        <div>
          <h2 className="font-semibold mb-1">9. Indemnification</h2>
          <p>
            You agree to indemnify, defend, and hold harmless TaxEngine from any claims, damages,
            losses, or expenses (including reasonable attorneys' fees) arising from your use of
            the Service, violation of these Terms, or infringement of any third-party rights.
          </p>
        </div>

        <div>
          <h2 className="font-semibold mb-1">10. Termination</h2>
          <p>
            You may stop using the Service and disconnect your QBO account at any time. We may
            suspend or terminate your access to the Service at our discretion if you violate
            these Terms or if required to comply with legal obligations.
          </p>
        </div>

        <div>
          <h2 className="font-semibold mb-1">11. Changes to Terms</h2>
          <p>
            We may update these Terms from time to time. Continued use of the Service after
            changes are posted constitutes acceptance of the updated Terms. We will update the
            "Last updated" date at the top of this page.
          </p>
        </div>

        <div>
          <h2 className="font-semibold mb-1">12. Governing Law</h2>
          <p>
            These Terms are governed by the laws of the United States. Any disputes shall be
            resolved in the applicable federal or state courts.
          </p>
        </div>

        <div>
          <h2 className="font-semibold mb-1">13. Contact</h2>
          <p>
            For questions about these Terms, contact us at{" "}
            <a href="mailto:legal@taxengine.app" className="text-blue-600 underline">
              legal@taxengine.app
            </a>
            .
          </p>
        </div>
      </section>
    </main>
  );
}
